/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : c8d0c97f-550f-4104-bb5c-27af740ca2f2
    Object             : Index SCore.WorkflowStatus.IX_WorkflowStatus_Active_ID_Guid
    Difference         : MissingInTarget
    Comparison hash    : DB538AC9D132185519CAF9FC5E073DD0BFA1E1A1FC5390821A42FE0D27C68B82
    Definition SHA-256 : A91C4C69E7BC87E58B81D0CB61BFC4CED7668D907020E7D6D5F28729B69E2596
    Purpose            : Finalize phase: create the source index from the declarative snapshot.
    Generated UTC      : 2026-08-11T08:37:08.9321862Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRY
    BEGIN TRANSACTION;
    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'[SCore].[WorkflowStatus]', N'U') AND name = N'IX_WorkflowStatus_Active_ID_Guid')
    BEGIN
        CREATE NONCLUSTERED INDEX [IX_WorkflowStatus_Active_ID_Guid] ON [SCore].[WorkflowStatus] ([ID] ASC) INCLUDE ([Guid]) WHERE ([RowStatus]<>(0) AND [RowStatus]<>(254)) WITH (PAD_INDEX = OFF, FILLFACTOR = 80, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
    END;
    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
