/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 4a5bb612-3eee-45d8-a7c2-35674a681dc8
    Object             : Index SCore.DataObjectTransition.IX_DataObjectTransition_Active_DataObjectGuid_ID
    Difference         : MissingInTarget
    Comparison hash    : 7F99A99D62B67FEFA06D3DCEC63B08D9C3495730498B50FA481A431B89481129
    Definition SHA-256 : 91DD432EC805D82243FB0CE70F4936443C1F1C7356630908E2AAE85120E7D94E
    Purpose            : Finalize phase: create the source index from the declarative snapshot.
    Generated UTC      : 2026-08-11T08:37:08.8981827Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRY
    BEGIN TRANSACTION;
    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'[SCore].[DataObjectTransition]', N'U') AND name = N'IX_DataObjectTransition_Active_DataObjectGuid_ID')
    BEGIN
        CREATE NONCLUSTERED INDEX [IX_DataObjectTransition_Active_DataObjectGuid_ID] ON [SCore].[DataObjectTransition] ([DataObjectGuid] ASC, [ID] DESC) INCLUDE ([StatusID], [DateTimeUTC], [Comment]) WHERE ([RowStatus]<>(0) AND [RowStatus]<>(254)) WITH (PAD_INDEX = OFF, FILLFACTOR = 80, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
    END;
    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
