/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 5700c65c-f1a4-4e12-a04c-e8ec3c970b64
    Object             : Index SMigration.Onboarding_Run.IX_SMigration_Onboarding_Run_Active
    Difference         : MissingInTarget
    Comparison hash    : C9E791D47F8D71A69A2ACBB0F5D652AFFDD675D60271998026E2EA77283F3662
    Definition SHA-256 : B3E2D3FB14C6780DDD0C20565496041B7311CC4EDDE7666F5D47E0A588F4A7F4
    Purpose            : Finalize phase: create the source index from the declarative snapshot.
    Generated UTC      : 2026-08-11T08:37:08.9728089Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRY
    BEGIN TRANSACTION;
    IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id = OBJECT_ID(N'[SMigration].[Onboarding_Run]', N'U') AND name = N'IX_SMigration_Onboarding_Run_Active')
    BEGIN
        CREATE NONCLUSTERED INDEX [IX_SMigration_Onboarding_Run_Active] ON [SMigration].[Onboarding_Run] ([CreatedUtc] DESC, [SourceDatabase] ASC, [TargetDatabaseName] ASC) WHERE ([RowStatus]<>(0) AND [RowStatus]<>(254)) WITH (PAD_INDEX = OFF, FILLFACTOR = 80, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];
    END;
    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
