/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : f76ab424-a5b3-48ec-aa9e-e3633ae9a8c3
    Object             : Index SMigration.Onboarding_EntityScope.IX_Onboarding_EntityScope_DisplayOrder
    Difference         : MissingInTarget
    Comparison hash    : F257AB39028AEF11213C858F448A1894E2A9C5D25472205A37FDBFCC709C1D5D
    Definition SHA-256 : 92CFE7B9C63458BAB93443C8F842389F097C460D6E4D0710F9DE5EAD10C7BAD8
    Purpose            : Read-only preflight for the selected index operation.
    Generated UTC      : 2026-08-11T08:37:08.9531870Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;
IF OBJECT_ID(N'[SMigration].[Onboarding_EntityScope]', N'U') IS NULL THROW 51430, 'Index parent table does not exist.', 1;
IF COL_LENGTH(N'[SMigration].[Onboarding_EntityScope]', N'DisplayOrder') IS NULL THROW 51431, 'Index column does not exist.', 1;
IF COL_LENGTH(N'[SMigration].[Onboarding_EntityScope]', N'Code') IS NULL THROW 51431, 'Index column does not exist.', 1;
IF DATA_SPACE_ID(N'PRIMARY') IS NULL THROW 51432, 'Index data space does not exist in the target.', 1;
GO
