/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 5700c65c-f1a4-4e12-a04c-e8ec3c970b64
    Object             : Index SMigration.Onboarding_Run.IX_SMigration_Onboarding_Run_Active
    Difference         : MissingInTarget
    Comparison hash    : C9E791D47F8D71A69A2ACBB0F5D652AFFDD675D60271998026E2EA77283F3662
    Definition SHA-256 : B3E2D3FB14C6780DDD0C20565496041B7311CC4EDDE7666F5D47E0A588F4A7F4
    Purpose            : Read-only preflight for the selected index operation.
    Generated UTC      : 2026-08-11T08:37:08.9728089Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;
IF OBJECT_ID(N'[SMigration].[Onboarding_Run]', N'U') IS NULL THROW 51430, 'Index parent table does not exist.', 1;
IF COL_LENGTH(N'[SMigration].[Onboarding_Run]', N'CreatedUtc') IS NULL THROW 51431, 'Index column does not exist.', 1;
IF COL_LENGTH(N'[SMigration].[Onboarding_Run]', N'SourceDatabase') IS NULL THROW 51431, 'Index column does not exist.', 1;
IF COL_LENGTH(N'[SMigration].[Onboarding_Run]', N'TargetDatabaseName') IS NULL THROW 51431, 'Index column does not exist.', 1;
IF DATA_SPACE_ID(N'PRIMARY') IS NULL THROW 51432, 'Index data space does not exist in the target.', 1;
GO
