/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : aba050d6-6e58-440b-ab1c-bfadc66c1f33
    Object             : Index SMigration.Onboarding_RunEntitySelections.IX_Onboarding_RunEntitySelections_RunGuid
    Difference         : MissingInTarget
    Comparison hash    : DEB211084EB5E66859E08F964608B2295B5AD8F615E48B57C1227BA7B16D07D1
    Definition SHA-256 : 0B42DA4175F8B4D5660BD1B5C7599360A130982BE4F28F8ECC06139B0E2D7C81
    Purpose            : Read-only preflight for the selected index operation.
    Generated UTC      : 2026-08-11T08:37:08.9968219Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;
IF OBJECT_ID(N'[SMigration].[Onboarding_RunEntitySelections]', N'U') IS NULL THROW 51430, 'Index parent table does not exist.', 1;
IF COL_LENGTH(N'[SMigration].[Onboarding_RunEntitySelections]', N'RunGuid') IS NULL THROW 51431, 'Index column does not exist.', 1;
IF COL_LENGTH(N'[SMigration].[Onboarding_RunEntitySelections]', N'EntityCode') IS NULL THROW 51431, 'Index column does not exist.', 1;
IF COL_LENGTH(N'[SMigration].[Onboarding_RunEntitySelections]', N'IsSelected') IS NULL THROW 51431, 'Index column does not exist.', 1;
IF DATA_SPACE_ID(N'PRIMARY') IS NULL THROW 51432, 'Index data space does not exist in the target.', 1;
GO
