SET IDENTITY_INSERT SCore.WorkflowStatus ON
GO
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (-1, 1, '00000000-0000-0000-0000-000000000000', -1, N'N/A', N'Used when importing legacy statuses', 1, 1, 1, 1, 1, 1, N'#B3E5FC', N'fa-database', 0, 0, 1, 1, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (2, 1, 'eb867fa0-9608-4cc7-93be-cc8e8140e8f0', -1, N'Ready for Quote', N'The enquiry is ready for quote review.', 1, 1, 0, 1, 1, 1, N'#CFD8DC', N'fa-clipboard-check', 1, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (3, 1, '708c00e6-f45f-4cb2-8e91-a80b8b8e802e', -1, N'Declined', N'The client has declined to quote.', 1, 1, 0, 1, 1, 2, N'#CFD8DC', N'fa-thumbs-down', 1, 1, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (4, 1, '9ff22cea-a2a6-4907-9b2d-e62df8150913', -1, N'1st Chase', N'First chase date.', 1, 1, 0, 1, 1, 3, N'#CFD8DC', N'fa-envelope-open', 0, 0, 1, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (5, 1, '1f01c16b-1a73-4844-a938-fe357405fd93', -1, N'2nd Chase', N'Second chase date.', 1, 1, 0, 1, 1, 4, N'#CFD8DC', N'fa-envelope', 0, 0, 1, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (6, 1, '25d5491c-42a8-4b04-b3ac-d648af0f8032', -1, N'Sent', N'The quote has been sent.', 1, 1, 0, 1, 1, 4, N'#CFD8DC', N'fa-paper-plane', 1, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (7, 1, '21a29aee-2d99-4da3-8182-f31813b0c498', -1, N'Accepted', N'The quote has been accepted.', 1, 1, 0, 1, 1, 5, N'#CFD8DC', N'fa-thumbs-up', 0, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (8, 1, '0a6a71f7-b39f-4213-997e-2b3a13b6144c', -1, N'Rejected', N'The quote has been rejected', 0, 1, 0, 1, 1, 6, N'#CFD8DC', N'fa-times-circle', 1, 1, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (9, 1, '6708fdb6-29a7-4505-a209-f1e785386122', -1, N'Dormant', N'The job has become dormant.', 0, 0, 1, 1, 1, 7, N'#CFD8DC', N'fa-bed', 0, 1, 1, 0, 0, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (10, 1, '18d8e36b-43be-4bde-9d0b-1f34b460ad64', -1, N'Cancelled', N'The job has been cancelled.', 0, 0, 1, 1, 1, 8, N'#CFD8DC', N'fa-ban', 1, 1, 0, 0, 0, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (11, 1, '20d22623-283b-4088-9ceb-d944ac3e6516', -1, N'Completed', N'The job has been completed.', 0, 0, 1, 1, 1, 9, N'#CFD8DC', N'fa-check-circle', 1, 1, 0, 0, 0, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (12, 1, '8c7f7526-559f-4ccf-8fc2-db0da67e793d', -1, N'Dead', N'The record is dead.', 1, 1, 1, 1, 1, 10, N'#CFD8DC', N'fa-skull-crossbones', 1, 1, 0, 0, 0, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (14, 1, '02a2237f-2ae7-4e05-926f-38e8b7d050a0', -1, N'Ready to Send', N'The Quote is ready to send', 0, 1, 0, 1, 1, 7, N'#CFD8DC', N'fa-flag-checkered', 1, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (15, 1, 'bf88fc8a-16f6-4829-977f-85d5624a5c83', -1, N'Part-Sent', N'Automatically generated status', 0, 0, 0, 1, 1, -1, N'#000000', N'bi-gear', 0, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (21, 1, 'a132b2a1-c824-4bec-9b4e-07fe9fdb70ee', -1, N'Part-Sent 3', N'Automatically generated status', 0, 0, 0, 1, 1, -1, N'#000000', N'bi-gear', 0, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (24, 1, '47ab419d-cb6b-4f5d-a18b-533cedbed775', -1, N'Part-Sent 4', N'Automatically generated status', 0, 0, 0, 1, 1, -1, N'#000000', N'bi-gear', 0, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (25, 1, '4bfdb215-3e27-4829-bb44-0468c92dac82', -1, N'Complete for Review', N'This job is finished and awaiting managerial or peer review.', 0, 0, 1, 1, 1, 11, N'#CFD8DC', N'fa-clipboard-check', 1, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (26, 1, '90407454-9fed-4aac-ab20-669c5821fe7a', -1, N'Reviewed', N'The job has been reviewed.', 0, 0, 1, 1, 1, 12, N'#CFD8DC', N'fa-check-double', 1, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (27, 1, 'e6fac201-f98b-4b3a-ab55-83dc9f802d00', -1, N'Expired', N'Automatically generated status', 1, 1, 0, 1, 1, -1, N'#000000', N'bi-gear', 0, 1, 0, 0, 0, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (28, 1, '1504e82f-35ca-4d6e-8c3e-e4701a68c90d', -1, N'Not Started', N'Automatically generated status', 0, 0, 1, 1, 1, -1, N'#000000', N'bi-gear', 0, 0, 0, 0, 0, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (29, 1, 'b88f95c2-41c9-4cc6-ad9f-d9223c4e852a', -1, N'Quoting', N'Automatically generated status', 1, 0, 0, 1, 1, -1, N'#000000', N'bi-gear', 0, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (30, 1, '46c5a517-3c7b-4a1b-8796-d084d5de1f8a', -1, N'Live', N'Automatically generated status', 0, 0, 1, 1, 1, -1, N'#000000', N'bi-gear', 0, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (31, 1, '6042639d-ef8a-4b6f-9182-a69a7119c117', -1, N'Complete', N'Automatically generated status', 1, 1, 0, 1, 1, -1, N'#000000', N'bi-gear', 0, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (32, 1, '2d40ca7e-3a4c-477f-a7f5-7e6d6c5c7849', -1, N'Part Sent', N'Automatically generated status', 1, 0, 0, 1, 1, -1, N'#000000', N'bi-gear', 0, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (33, 1, '9e0a10c7-94a0-4e25-afb1-14240d906c12', -1, N'New', N'Automatically generated status', 1, 1, 0, 1, 1, -1, N'#000000', N'bi-gear', 0, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (34, 1, '286a39a3-e965-4c54-926c-3b272e6d8165', -1, N'Part Complete', N'Automatically generated status', 1, 1, 0, 1, 1, -1, N'#000000', N'bi-gear', 0, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (35, 1, 'fc9aa6a3-79db-4533-a6a9-b831610f2bdc', -1, N'Job Started', N'The job has been started.', 0, 0, 1, 1, 1, 11, N'#AAFF00', N'fa-rocket', 1, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (36, 1, 'e458c3d3-f3ca-4ef6-9f46-fe06b61f7ca0', -1, N'Deadline Missed', N'Automatically generated status', 1, 0, 0, 1, 1, -1, N'#000000', N'bi-gear', 0, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (37, 1, 'b9ba4510-6358-4c0a-bba1-5feb33c54f84', -1, N'Declined', N'Automatically generated status', 1, 0, 0, 1, 1, -1, N'#000000', N'bi-gear', 0, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (38, 1, 'b41290f9-c0ce-44e2-a5e7-364d6cd52446', 3, N'Withdrawn', N'', 1, 0, 0, 1, 0, 0, N'', N'', 0, 1, 0, 1, 0, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (39, 1, 'bb4fabda-00ea-4dc2-beed-9e5c1a70fcf2', 3, N'Test Status', N'', 1, 1, 1, 1, 0, 10, N'', N'', 0, 0, 0, 0, 0, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (40, 1, '01966eee-0c33-42a4-b5e3-e4466ec3b2d0', -1, N'Deadline Approaching', N'Automatically generated status', 1, 1, 0, 1, 1, -1, N'#000000', N'bi-gear', 0, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (41, 254, '6ed4279a-e299-4d33-8ed5-cb8b78b3f13d', -1, N'Ready to Send', N'Automatically generated status', 1, 1, 0, 1, 1, -1, N'#000000', N'bi-gear', 0, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (43, 1, '57de08fb-89a3-4986-84c1-784b930da681', -1, N'Live Job', N'Automatically generated status', 1, 0, 0, 1, 1, -1, N'#000000', N'bi-gear', 0, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (48, 1, '3dab4339-a1c0-4abe-860a-4915a6cf94b6', -1, N'New', N'Automatically generated status', 1, 1, 1, 1, 1, -1, N'#000000', N'bi-gear', 0, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (50, 1, '9a60f983-24ba-4733-907e-c5cce0b691cb', -1, N'Quoting', N'Automatically generated status', 1, 1, 0, 1, 1, -1, N'#000000', N'bi-gear', 0, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (52, 1, '5c9cd674-7520-44d2-9464-2a681f2f2ba4', -1, N'Ready to Send', N'Automatically generated status', 1, 1, 0, 1, 1, -1, N'#000000', N'bi-send', 0, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (53, 1, '85b522aa-134c-4e6c-884a-ff7264d7dd2e', -1, N'Rejected', N'Automatically generated status', 1, 1, 0, 1, 1, -1, N'#000000', N'bi-x-circle', 1, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (54, 1, '675ca95d-f03d-4dbc-b83c-3d21bf138635', 16, N'Bid Team Review', N'Review for bid review Team', 1, 0, 0, 1, 0, 0, N'', N'', 1, 0, 0, 1, 1, 1);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (57, 1, '5118dd68-20ba-4771-8262-bb3ec6cccbf5', -1, N'Part Accepted', N'', 1, 1, 1, 1, 1, 0, N'#FFFFFF', N'', 0, 0, 0, 0, 1, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (58, 1, '6a489de9-f2d1-4262-ab1a-62233d368584', -1, N'Quote Expired', N'', 1, 1, 1, 1, 1, 0, N'#FFFFFF', N'', 0, 0, 0, 0, 0, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (59, 1, '89014854-89dd-4c7f-a7ba-b73356a9e8db', -1, N'For Review', N'For Review Prior to Send To Client', 0, 1, 0, 1, 0, 0, N'', N'', 1, 0, 0, 1, 1, 1);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (60, 1, '5ed9c55a-4e14-44f6-a106-ae0f5c5ec38d', -1, N'Closure Request', N'Review Closure Request', 0, 0, 1, 1, 0, 0, N'#CFD8DC', N'fa-clipboard-check', 1, 0, 0, 1, 1, 1);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (61, 1, 'e6776db3-812f-4328-b81e-fefd494ea049', -1, N'Approve Closure', N'Reviewer Approved Closure', 0, 0, 1, 1, 0, 0, N'#CFD8DC', N'fa-thumbs-up', 1, 1, 0, 0, 0, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (62, 1, '48507119-2f28-490c-83a6-ce8f85e5af7f', -1, N'Closure Rejected', N'Reviewer Rejects Closure', 0, 0, 1, 1, 0, 0, N'#CFD8DC', N'fa-thumbs-down', 1, 0, 0, 1, 1, 0);
GO
SET IDENTITY_INSERT SCore.WorkflowStatus OFF
GO
SET IDENTITY_INSERT SCore.WorkflowStatus ON
GO
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (66, 1, '60b8d960-8f6c-495d-b2e7-f19ebd5506ee', -1, N'Declined To Quote', N'Engineering Rejection - Declined To Quote', 1, 0, 0, 1, 0, 0, N'', N'', 1, 1, 0, 0, 0, 0);
INSERT SCore.WorkflowStatus(ID, RowStatus, Guid, OrganisationalUnitId, Name, Description, ShowInEnquiries, ShowInQuotes, ShowInJobs, Enabled, IsPredefined, SortOrder, Colour, Icon, SendNotification, IsCompleteStatus, IsCustomerWaitingStatus, RequiresUsersAction, IsActiveStatus, AuthorisationNeeded) VALUES (67, 1, '3070a373-0e0a-4261-b942-66cb512ee1b6', -1, N'Approved For Quote', N'Engineering Approval - Ready To Quote', 1, 0, 0, 1, 0, 0, N'', N'', 1, 0, 0, 0, 1, 0);
GO
SET IDENTITY_INSERT SCore.WorkflowStatus OFF
GO