-- 
-- Script was generated by Devart dbForge Schema Compare for SQL Server, Version 7.1.45.0
-- Product Home Page: https://www.devart.com/dbforge/sql/schemacompare
-- Script date 08/05/2025 15:38:33
-- Source server version: 16.00.0000
-- Target server version: 16.00.1000
-- Target connection string: Data Source=soc-sqldevbre01.esgl.co.uk\General;Integrated Security=True;User ID=ESGL\Richard.Brindley
-- Run this script against Concursus_Test to synchronize it with [Schema]
-- Please backup your target database before running this script
-- 

SET CONCAT_NULL_YIELDS_NULL, ANSI_NULLS, ANSI_PADDING, QUOTED_IDENTIFIER, ANSI_WARNINGS, ARITHABORT, XACT_ABORT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS OFF
GO

--
-- Drop full-text index from table [SCrm].[Accounts]
--
DROP FULLTEXT INDEX ON [SCrm].[Accounts]
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

--
-- Start Transaction
--
BEGIN TRANSACTION
GO

--
-- Drop foreign key [FK_QuoteTemplates_ContractBandId] on table [SSop].[QuoteTemplates]
--
ALTER TABLE [SSop].[QuoteTemplates]
  DROP CONSTRAINT [FK_QuoteTemplates_ContractBandId]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_GridViewColumnDefinition_GridViewDefinition] on table [SUserInterface].[GridViewColumnDefinitions]
--
ALTER TABLE [SUserInterface].[GridViewColumnDefinitions]
  DROP CONSTRAINT [FK_GridViewColumnDefinition_GridViewDefinition]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_GridViewActions_GridViewDefinition] on table [SUserInterface].[GridViewActions]
--
ALTER TABLE [SUserInterface].[GridViewActions]
  DROP CONSTRAINT [FK_GridViewActions_GridViewDefinition]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_GridViewWidgetQueries_GridViewDefinitions] on table [SUserInterface].[GridViewWidgetQueries]
--
ALTER TABLE [SUserInterface].[GridViewWidgetQueries]
  DROP CONSTRAINT [FK_GridViewWidgetQueries_GridViewDefinitions]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Accounts_AccountContacts] on table [SCrm].[Accounts]
--
ALTER TABLE [SCrm].[Accounts]
  DROP CONSTRAINT [FK_Accounts_AccountContacts]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Jobs_Contacts] on table [SJob].[Jobs]
--
ALTER TABLE [SJob].[Jobs]
  DROP CONSTRAINT [FK_Jobs_Contacts]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Jobs_Contacts1] on table [SJob].[Jobs]
--
ALTER TABLE [SJob].[Jobs]
  DROP CONSTRAINT [FK_Jobs_Contacts1]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Jobs_Contacts3] on table [SJob].[Jobs]
--
ALTER TABLE [SJob].[Jobs]
  DROP CONSTRAINT [FK_Jobs_Contacts3]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Enquiries_AccountContacts] on table [SSop].[Enquiries]
--
ALTER TABLE [SSop].[Enquiries]
  DROP CONSTRAINT [FK_Enquiries_AccountContacts]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Enquiries_AccountContacts1] on table [SSop].[Enquiries]
--
ALTER TABLE [SSop].[Enquiries]
  DROP CONSTRAINT [FK_Enquiries_AccountContacts1]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Enquiries_AccountContacts2] on table [SSop].[Enquiries]
--
ALTER TABLE [SSop].[Enquiries]
  DROP CONSTRAINT [FK_Enquiries_AccountContacts2]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Accounts_AccountAddresses] on table [SCrm].[Accounts]
--
ALTER TABLE [SCrm].[Accounts]
  DROP CONSTRAINT [FK_Accounts_AccountAddresses]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Jobs_Addresses] on table [SJob].[Jobs]
--
ALTER TABLE [SJob].[Jobs]
  DROP CONSTRAINT [FK_Jobs_Addresses]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Jobs_Addresses1] on table [SJob].[Jobs]
--
ALTER TABLE [SJob].[Jobs]
  DROP CONSTRAINT [FK_Jobs_Addresses1]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Jobs_Addresses2] on table [SJob].[Jobs]
--
ALTER TABLE [SJob].[Jobs]
  DROP CONSTRAINT [FK_Jobs_Addresses2]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Enquiries_AccountAddresses] on table [SSop].[Enquiries]
--
ALTER TABLE [SSop].[Enquiries]
  DROP CONSTRAINT [FK_Enquiries_AccountAddresses]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Enquiries_Addresses] on table [SSop].[Enquiries]
--
ALTER TABLE [SSop].[Enquiries]
  DROP CONSTRAINT [FK_Enquiries_Addresses]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Enquiries_Addresses1] on table [SSop].[Enquiries]
--
ALTER TABLE [SSop].[Enquiries]
  DROP CONSTRAINT [FK_Enquiries_Addresses1]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_AccountAddresses_Accounts] on table [SCrm].[AccountAddresses]
--
ALTER TABLE [SCrm].[AccountAddresses]
  DROP CONSTRAINT [FK_AccountAddresses_Accounts]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_AccountContacts_Accounts] on table [SCrm].[AccountContacts]
--
ALTER TABLE [SCrm].[AccountContacts]
  DROP CONSTRAINT [FK_AccountContacts_Accounts]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_AccountMemos_Accounts] on table [SCrm].[AccountMemos]
--
ALTER TABLE [SCrm].[AccountMemos]
  DROP CONSTRAINT [FK_AccountMemos_Accounts]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_AccountMergeBatch_Accounts] on table [SCrm].[AccountMergeBatch]
--
ALTER TABLE [SCrm].[AccountMergeBatch]
  DROP CONSTRAINT [FK_AccountMergeBatch_Accounts]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_AccountMergeBatch_Accounts1] on table [SCrm].[AccountMergeBatch]
--
ALTER TABLE [SCrm].[AccountMergeBatch]
  DROP CONSTRAINT [FK_AccountMergeBatch_Accounts1]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Contacts_Accounts] on table [SCrm].[Contacts]
--
ALTER TABLE [SCrm].[Contacts]
  DROP CONSTRAINT [FK_Contacts_Accounts]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_FinanceMemo_Accounts] on table [SFin].[FinanceMemo]
--
ALTER TABLE [SFin].[FinanceMemo]
  DROP CONSTRAINT [FK_FinanceMemo_Accounts]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Transactions_Accounts] on table [SFin].[Transactions]
--
ALTER TABLE [SFin].[Transactions]
  DROP CONSTRAINT [FK_Transactions_Accounts]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Jobs_Accounts] on table [SJob].[Jobs]
--
ALTER TABLE [SJob].[Jobs]
  DROP CONSTRAINT [FK_Jobs_Accounts]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Jobs_Accounts1] on table [SJob].[Jobs]
--
ALTER TABLE [SJob].[Jobs]
  DROP CONSTRAINT [FK_Jobs_Accounts1]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Jobs_Accounts2] on table [SJob].[Jobs]
--
ALTER TABLE [SJob].[Jobs]
  DROP CONSTRAINT [FK_Jobs_Accounts2]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_ProjectDirectory_Accounts] on table [SJob].[ProjectDirectory]
--
ALTER TABLE [SJob].[ProjectDirectory]
  DROP CONSTRAINT [FK_ProjectDirectory_Accounts]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Contracts_Accounts] on table [SSop].[Contracts]
--
ALTER TABLE [SSop].[Contracts]
  DROP CONSTRAINT [FK_Contracts_Accounts]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Enquiries_Accounts] on table [SSop].[Enquiries]
--
ALTER TABLE [SSop].[Enquiries]
  DROP CONSTRAINT [FK_Enquiries_Accounts]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Enquiries_Accounts1] on table [SSop].[Enquiries]
--
ALTER TABLE [SSop].[Enquiries]
  DROP CONSTRAINT [FK_Enquiries_Accounts1]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Enquiries_Accounts2] on table [SSop].[Enquiries]
--
ALTER TABLE [SSop].[Enquiries]
  DROP CONSTRAINT [FK_Enquiries_Accounts2]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Quotes_Accounts] on table [SSop].[Quotes]
--
ALTER TABLE [SSop].[Quotes]
  DROP CONSTRAINT [FK_Quotes_Accounts]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Quotes_Accounts1] on table [SSop].[Quotes]
--
ALTER TABLE [SSop].[Quotes]
  DROP CONSTRAINT [FK_Quotes_Accounts1]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Properties_Accounts] on table [SJob].[Assets]
--
ALTER TABLE [SJob].[Assets]
  DROP CONSTRAINT [FK_Properties_Accounts]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Properties_Accounts1] on table [SJob].[Assets]
--
ALTER TABLE [SJob].[Assets]
  DROP CONSTRAINT [FK_Properties_Accounts1]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Properties_Accounts2] on table [SJob].[Assets]
--
ALTER TABLE [SJob].[Assets]
  DROP CONSTRAINT [FK_Properties_Accounts2]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_Properties_Accounts3] on table [SJob].[Assets]
--
ALTER TABLE [SJob].[Assets]
  DROP CONSTRAINT [FK_Properties_Accounts3]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_ProjectDirectory_Contacts] on table [SJob].[ProjectDirectory]
--
ALTER TABLE [SJob].[ProjectDirectory]
  DROP CONSTRAINT [FK_ProjectDirectory_Contacts]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create table [SCore].[NonActivityTypes]
--
CREATE TABLE [SCore].[NonActivityTypes] (
  [ID] [int] IDENTITY,
  [Guid] [uniqueidentifier] NOT NULL DEFAULT (newid()),
  [Name] [nvarchar](100) NOT NULL,
  [RowStatus] [tinyint] NOT NULL DEFAULT (1),
  [RowVersion] [timestamp],
  PRIMARY KEY CLUSTERED ([ID]) WITH (FILLFACTOR = 80)
)
ON [PRIMARY]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create or alter procedure [SCore].[PopulateBankHolidaysUK]
--
GO
CREATE OR ALTER PROCEDURE [SCore].[PopulateBankHolidaysUK]
    @StartYear INT,
    @EndYear INT
AS
BEGIN
    SET NOCOUNT ON;
   
    DECLARE @CurrentYear INT = @StartYear;
    
    WHILE @CurrentYear <= @EndYear
    BEGIN
        DECLARE @EasterSunday DATE = SCore.tvf_GetEasterSunday(@CurrentYear);
        
        -- UK-wide holidays
        INSERT INTO SCore.BankHolidaysUK
        SELECT
            Date = DATEADD(HOUR, 12, CAST(d AS DATETIME)),
            DayName = DATENAME(WEEKDAY, d),
            MonthName = DATENAME(MONTH, d),
			YearInWords = DATEPART(YYYY, d)            ,
            FormattedDate = (CONVERT(VARCHAR(10), d, 103) + ' 12:00:00'),
            HolidayName = hn,
            IsBankHoliday = 1,
            Region = 'UK',
            FiscalQuarter = DATEPART(QUARTER, d),
            FiscalYear = @CurrentYear,
            DayOfYear = DATEPART(DAYOFYEAR, d),
            WeekOfYear = DATEPART(WEEK, d)
        FROM (
            -- New Year's Day
            SELECT d = CASE WHEN DATEPART(WEEKDAY, DATEFROMPARTS(@CurrentYear, 1, 1)) IN (1,7)
                        THEN DATEADD(DAY, CASE DATEPART(WEEKDAY, DATEFROMPARTS(@CurrentYear, 1, 1)) WHEN 7 THEN 2 ELSE 1 END, DATEFROMPARTS(@CurrentYear, 1, 1))
                        ELSE DATEFROMPARTS(@CurrentYear, 1, 1) END,
                   hn = 'New Year''s Day'
            
            UNION ALL
            
            -- Good Friday
            SELECT DATEADD(DAY, -2, @EasterSunday), 'Good Friday'
            
            UNION ALL
            
            -- Easter Monday
            SELECT DATEADD(DAY, 1, @EasterSunday), 'Easter Monday'
            
            UNION ALL
            
            ---- Early May Bank Holiday (first Monday in May)
            --SELECT DATEADD(DAY, (1 - DATEPART(WEEKDAY, DATEFROMPARTS(@CurrentYear, 5, 1)) + 1) % 7, DATEFROMPARTS(@CurrentYear, 5, 1)), 'Early May Bank Holiday'

			-- Early May Bank Holiday (first Monday in May)
			SELECT DATEADD(DAY, (9 - DATEPART(WEEKDAY, DATEFROMPARTS(@CurrentYear, 5, 1))) % 7, DATEFROMPARTS(@CurrentYear, 5, 1)), 'Early May Bank Holiday'

            
            UNION ALL
            
            -- Spring Bank Holiday (last Monday in May)
            SELECT DATEADD(DAY, -((DATEPART(WEEKDAY, DATEFROMPARTS(@CurrentYear, 5, 31)) + 5) % 7), DATEFROMPARTS(@CurrentYear, 5, 31)), 'Spring Bank Holiday'

            
            UNION ALL
            
         

			-- Summer Bank Holiday (last Monday in August)
			SELECT DATEADD(DAY, -((DATEPART(WEEKDAY, DATEFROMPARTS(@CurrentYear, 8, 31)) + 5) % 7),  DATEFROMPARTS(@CurrentYear, 8, 31)),'Summer Bank Holiday'

            
            UNION ALL
            
           -- Christmas Day
			SELECT CASE 
					 WHEN DATEPART(WEEKDAY, DATEFROMPARTS(@CurrentYear, 12, 25)) = 7 -- Saturday
					   THEN DATEFROMPARTS(@CurrentYear, 12, 27) -- Monday after
					 WHEN DATEPART(WEEKDAY, DATEFROMPARTS(@CurrentYear, 12, 25)) = 1 -- Sunday
					   THEN DATEFROMPARTS(@CurrentYear, 12, 27) -- Monday after
					 ELSE DATEFROMPARTS(@CurrentYear, 12, 25) -- Actual day (25th)
				   END,
				   'Christmas Day'

            
            UNION ALL
            

			-- Boxing Day
			SELECT 
				CASE 
					WHEN DATEPART(WEEKDAY, DATEFROMPARTS(@CurrentYear, 12, 26)) = 7 -- Saturday
						THEN DATEFROMPARTS(@CurrentYear, 12, 28)  -- Monday
					WHEN DATEPART(WEEKDAY, DATEFROMPARTS(@CurrentYear, 12, 26)) = 1 -- Sunday
						THEN DATEFROMPARTS(@CurrentYear, 12, 28)  -- Monday (not Tuesday)
					ELSE DATEFROMPARTS(@CurrentYear, 12, 26)       -- Actual day
				END,
				'Boxing Day'


        ) uk_holidays
        WHERE NOT EXISTS (SELECT 1 FROM SCore.BankHolidaysUK WHERE Date = d)

        -- Regional holidays
		INSERT INTO SCore.BankHolidaysUK
		SELECT
			DATEADD(HOUR, 12, CAST(d AS DATETIME)),
			DATENAME(WEEKDAY, d),
			DATENAME(MONTH, d),
			DATENAME(YEAR, d),
			CONVERT(VARCHAR(10), d, 103) + ' 12:00:00',
			hn,
			1,
			Region,
			DATEPART(QUARTER, d),
			@CurrentYear,
			DATEPART(DAYOFYEAR, d),
			DATEPART(WEEK, d)
		FROM (
			-- Scotland: St Andrew's Day
			SELECT d = CASE 
						WHEN DATEPART(WEEKDAY, DATEFROMPARTS(@CurrentYear, 11, 30)) = 7  -- Saturday
							THEN DATEFROMPARTS(@CurrentYear, 12, 1)
						WHEN DATEPART(WEEKDAY, DATEFROMPARTS(@CurrentYear, 11, 30)) = 6  -- Friday
							THEN DATEADD(DAY, 2, DATEFROMPARTS(@CurrentYear, 11, 30))
						ELSE DATEFROMPARTS(@CurrentYear, 11, 30) 
					  END,
				   hn = 'St Andrew''s Day',
				   'Scotland' AS Region
    
			UNION ALL
    
			-- Northern Ireland: Battle of the Boyne
			SELECT DATEADD(DAY, 
						  (1 - DATEPART(WEEKDAY, DATEFROMPARTS(@CurrentYear, 7, 12)) + 1) % 7, 
						  DATEFROMPARTS(@CurrentYear, 7, 12)),
				   'Battle of the Boyne',
				   'Northern Ireland'
		) regional_holidays
		WHERE NOT EXISTS (SELECT 1 FROM SCore.BankHolidaysUK WHERE Date = d)

        SET @CurrentYear += 1
    END
END;

GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create or alter procedure [SCore].[NonActivityTypesDelete]
--
GO


CREATE OR ALTER PROCEDURE [SCore].[NonActivityTypesDelete]
  @Guid      UNIQUEIDENTIFIER
AS
  BEGIN
   EXEC SCore.DeleteDataObject @Guid = @Guid	-- uniqueidentifier
	

	UPDATE	SCore.NonActivityTypes
	SET		RowStatus = 254
	WHERE	(Guid = @Guid)
  END;

GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop default constraint [DF__GridViewD__Drawe__62B136C0] on table [SUserInterface].[GridViewDefinitions]
--
ALTER TABLE [SUserInterface].[GridViewDefinitions]
  DROP CONSTRAINT [DF_GridViewDefinitions_DrawerIcon]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop default constraint [DF__GridViewD__Langu__1F653F45] on table [SUserInterface].[GridViewDefinitions]
--
ALTER TABLE [SUserInterface].[GridViewDefinitions]
  DROP CONSTRAINT [DF_GridViewDefinitions_LanguageLabelId]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Add default constraint [DF_GridViewDefinitions_LanguageLabelId] on table [SUserInterface].[GridViewDefinitions]
--
ALTER TABLE [SUserInterface].[GridViewDefinitions]
  ADD CONSTRAINT [DF_GridViewDefinitions_LanguageLabelId] DEFAULT (-1) FOR [LanguageLabelId]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Add default constraint [DF_GridViewDefinitions_DrawIconId] on table [SUserInterface].[GridViewDefinitions]
--
ALTER TABLE [SUserInterface].[GridViewDefinitions]
  ADD CONSTRAINT [DF_GridViewDefinitions_DrawIconId] DEFAULT (-1) FOR [DrawerIconId]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_GridViewColumnDefinition_GridViewDefinition] on table [SUserInterface].[GridViewColumnDefinitions]
--
ALTER TABLE [SUserInterface].[GridViewColumnDefinitions] WITH NOCHECK
  ADD CONSTRAINT [FK_GridViewColumnDefinition_GridViewDefinition] FOREIGN KEY ([GridViewDefinitionId]) REFERENCES [SUserInterface].[GridViewDefinitions] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_GridViewActions_GridViewDefinition] on table [SUserInterface].[GridViewActions]
--
ALTER TABLE [SUserInterface].[GridViewActions] WITH NOCHECK
  ADD CONSTRAINT [FK_GridViewActions_GridViewDefinition] FOREIGN KEY ([GridViewDefinitionId]) REFERENCES [SUserInterface].[GridViewDefinitions] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_GridViewWidgetQueries_GridViewDefinitions] on table [SUserInterface].[GridViewWidgetQueries]
--
ALTER TABLE [SUserInterface].[GridViewWidgetQueries] WITH NOCHECK
  ADD CONSTRAINT [FK_GridViewWidgetQueries_GridViewDefinitions] FOREIGN KEY ([GridViewDefinitionId]) REFERENCES [SUserInterface].[GridViewDefinitions] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_NonActivityEvents_Groups] on table [SCore].[NonActivityEvents]
--
ALTER TABLE [SCore].[NonActivityEvents]
  DROP CONSTRAINT [FK_NonActivityEvents_Groups]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_NonActivityEvents_Identities] on table [SCore].[NonActivityEvents]
--
ALTER TABLE [SCore].[NonActivityEvents]
  DROP CONSTRAINT [FK_NonActivityEvents_Identities]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop default constraint [DF_NonActivityEvents_MemberId] on table [SCore].[NonActivityEvents]
--
ALTER TABLE [SCore].[NonActivityEvents]
  DROP CONSTRAINT [DF_NonActivityEvents_MemberId]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop default constraint [DF_NonActivityEvents_TeamId] on table [SCore].[NonActivityEvents]
--
ALTER TABLE [SCore].[NonActivityEvents]
  DROP CONSTRAINT [DF_NonActivityEvents_TeamId]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop column [EventName] from table [SCore].[NonActivityEvents]
--
ALTER TABLE [SCore].[NonActivityEvents]
  DROP COLUMN [EventName]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop column [MemberId] from table [SCore].[NonActivityEvents]
--
ALTER TABLE [SCore].[NonActivityEvents]
  DROP COLUMN [MemberId]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Rename column [TeamId] to [MemberIdentityId] on table [SCore].[NonActivityEvents]
--
DECLARE @res int
EXEC @res = sp_rename N'[SCore].[NonActivityEvents].[TeamId]', N'MemberIdentityId', 'COLUMN'
IF @res <> 0
  RAISERROR ('Error while Rename column [TeamId] to [MemberIdentityId] on table [SCore].[NonActivityEvents]', 11, 1 );
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create column [TeamGroupId] on table [SCore].[NonActivityEvents]
--
ALTER TABLE [SCore].[NonActivityEvents]
  ADD [TeamGroupId] [int] NOT NULL CONSTRAINT [DF_NonActivityEvents_TeamId] DEFAULT (-1)
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create column [AbsenceTypeID] on table [SCore].[NonActivityEvents]
--
ALTER TABLE [SCore].[NonActivityEvents]
  ADD [AbsenceTypeID] [int] NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Add default constraint [DF_NonActivityEvents_MemberId] on table [SCore].[NonActivityEvents]
--
ALTER TABLE [SCore].[NonActivityEvents]
  ADD CONSTRAINT [DF_NonActivityEvents_MemberId] DEFAULT (-1) FOR [MemberIdentityId]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_NonActivityEvents_AbsenceTypes] on table [SCore].[NonActivityEvents]
--
ALTER TABLE [SCore].[NonActivityEvents]
  ADD CONSTRAINT [FK_NonActivityEvents_AbsenceTypes] FOREIGN KEY ([AbsenceTypeID]) REFERENCES [SCore].[NonActivityTypes] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_NonActivityEvents_Groups] on table [SCore].[NonActivityEvents]
--
ALTER TABLE [SCore].[NonActivityEvents]
  ADD CONSTRAINT [FK_NonActivityEvents_Groups] FOREIGN KEY ([TeamGroupId]) REFERENCES [SCore].[Groups] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_NonActivityEvents_Identities] on table [SCore].[NonActivityEvents]
--
ALTER TABLE [SCore].[NonActivityEvents]
  ADD CONSTRAINT [FK_NonActivityEvents_Identities] FOREIGN KEY ([MemberIdentityId]) REFERENCES [SCore].[Identities] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create or alter function [SCore].[tvf_GetScheduledAbsences]
--
GO
CREATE OR ALTER FUNCTION [SCore].[tvf_GetScheduledAbsences]
(
    @UserId INT,
    @StartDate DATE = NULL,
    @EndDate DATE = NULL
)
RETURNS TABLE
AS
RETURN
(
    SELECT 
        NA.ID,
        NAT.Name AS Name,
        NA.StartTime,
        NA.EndTime,
        NA.Guid,
        NA.RowStatus,
        NA.RowVersion,
		NA.TeamGroupId,
		NA.MemberIdentityId,
		NA.AbsenceTypeID
    FROM 
        SCore.NonActivityEvents AS NA
	LEFT JOIN SCore.NonActivityTypes AS NAT ON (NA.AbsenceTypeID = NAT.ID)
    WHERE 
        NA.MemberIdentityId = @UserId AND
		NA.RowStatus NOT IN (0, 254) AND
        (@StartDate IS NULL OR NA.StartTime >= @StartDate) AND
        (@EndDate IS NULL OR NA.StartTime < @EndDate)
);
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create or alter procedure [SCore].[NonActivityTypesUpsert]
--
GO



CREATE OR ALTER PROCEDURE [SCore].[NonActivityTypesUpsert]
  (
    @Name        NVARCHAR(100),
    @Guid        UNIQUEIDENTIFIER OUT
  )
AS
  BEGIN
    SET NOCOUNT ON;

    DECLARE @IsInsert BIT = 0;

    EXEC SCore.UpsertDataObject
      @Guid       = @Guid,					
      @SchemeName = N'SCore',			
      @ObjectName = N'NonActivityTypes',		
      @IsInsert   = @IsInsert OUTPUT;	

    IF (@IsInsert = 1)
      BEGIN
        INSERT INTO SCore.NonActivityTypes
                  (
                    RowStatus,
                    Guid,
                    Name
                  )
        VALUES
                (
                  1,
                  @Guid,
                  @Name
                );
      END;
    ELSE
      BEGIN
        UPDATE  SCore.NonActivityTypes
        SET     Name = @Name
        WHERE
          (Guid = @Guid);
      END;
  END;
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create or alter procedure [SCore].[NonActivityEventsUpsert]
--
GO
CREATE OR ALTER PROCEDURE [SCore].[NonActivityEventsUpsert]
(
	@AbsenceTypeGuid UNIQUEIDENTIFIER,
	@StartTime DATETIME,
	@EndTime DATETIME,
	@TeamId SMALLINT,
	@MemberId SMALLINT,
	@Guid UNIQUEIDENTIFIER
) 
AS
BEGIN


	DECLARE @AbsenceTypeID INT;

	 SELECT  @AbsenceTypeID = ID 
    FROM    SCore.NonActivityTypes 
    WHERE   ([Guid] = @AbsenceTypeGuid)


	DECLARE	@IsInsert bit
	EXEC SCore.UpsertDataObject @Guid = @Guid,					-- uniqueidentifier
							@SchemeName = N'SCore',				-- nvarchar(255)
							@ObjectName = N'NonActivityEvents',				-- nvarchar(255)
							@IncludeDefaultSecurity = 0,
							@IsInsert = @IsInsert OUTPUT	-- bit


	IF (@IsInsert = 1)
    BEGIN 
        INSERT  SCore.NonActivityEvents 
        (
            RowStatus,
            Guid,
			AbsenceTypeID,
			StartTime,
			EndTime,
			TeamGroupId,
			MemberIdentityId
			
        )
        VALUES
        (
            1,
            @Guid,
			@AbsenceTypeID,
            @StartTime,
			@EndTime,
			@TeamId,
			@MemberId
        )
    END
    ELSE
    BEGIN 
        UPDATE  SCore.NonActivityEvents
        SET     RowStatus = 1,
                AbsenceTypeID = @AbsenceTypeID,
				StartTime = @StartTime,
				EndTime = @EndTime,
				TeamGroupId = @TeamId,
				MemberIdentityId = @MemberId
        WHERE   ([Guid] = @Guid)
    END


END;
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop primary key [PK_Accounts] on table [SCrm].[Accounts]
--
ALTER TABLE [SCrm].[Accounts]
  DROP CONSTRAINT [PK_Accounts]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create primary key [PK_Accounts] on table [SCrm].[Accounts]
--
ALTER TABLE [SCrm].[Accounts]
  ADD CONSTRAINT [PK_Accounts] PRIMARY KEY CLUSTERED ([ID]) WITH (PAD_INDEX = ON)
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Accounts_AccountContacts] on table [SCrm].[Accounts]
--
ALTER TABLE [SCrm].[Accounts]
  ADD CONSTRAINT [FK_Accounts_AccountContacts] FOREIGN KEY ([MainAccountContactId]) REFERENCES [SCrm].[AccountContacts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Accounts_AccountAddresses] on table [SCrm].[Accounts]
--
ALTER TABLE [SCrm].[Accounts]
  ADD CONSTRAINT [FK_Accounts_AccountAddresses] FOREIGN KEY ([MainAccountAddressId]) REFERENCES [SCrm].[AccountAddresses] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_AccountAddresses_Accounts] on table [SCrm].[AccountAddresses]
--
ALTER TABLE [SCrm].[AccountAddresses]
  ADD CONSTRAINT [FK_AccountAddresses_Accounts] FOREIGN KEY ([AccountID]) REFERENCES [SCrm].[Accounts] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_AccountContacts_Accounts] on table [SCrm].[AccountContacts]
--
ALTER TABLE [SCrm].[AccountContacts]
  ADD CONSTRAINT [FK_AccountContacts_Accounts] FOREIGN KEY ([AccountID]) REFERENCES [SCrm].[Accounts] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_AccountMemos_Accounts] on table [SCrm].[AccountMemos]
--
ALTER TABLE [SCrm].[AccountMemos]
  ADD CONSTRAINT [FK_AccountMemos_Accounts] FOREIGN KEY ([AccountID]) REFERENCES [SCrm].[Accounts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_AccountMergeBatch_Accounts] on table [SCrm].[AccountMergeBatch]
--
ALTER TABLE [SCrm].[AccountMergeBatch]
  ADD CONSTRAINT [FK_AccountMergeBatch_Accounts] FOREIGN KEY ([SourceAccountId]) REFERENCES [SCrm].[Accounts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_AccountMergeBatch_Accounts1] on table [SCrm].[AccountMergeBatch]
--
ALTER TABLE [SCrm].[AccountMergeBatch]
  ADD CONSTRAINT [FK_AccountMergeBatch_Accounts1] FOREIGN KEY ([TargetAccountId]) REFERENCES [SCrm].[Accounts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Contacts_Accounts] on table [SCrm].[Contacts]
--
ALTER TABLE [SCrm].[Contacts]
  ADD CONSTRAINT [FK_Contacts_Accounts] FOREIGN KEY ([PrimaryAccountID]) REFERENCES [SCrm].[Accounts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_FinanceMemo_Accounts] on table [SFin].[FinanceMemo]
--
ALTER TABLE [SFin].[FinanceMemo]
  ADD CONSTRAINT [FK_FinanceMemo_Accounts] FOREIGN KEY ([AccountID]) REFERENCES [SCrm].[Accounts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Transactions_Accounts] on table [SFin].[Transactions]
--
ALTER TABLE [SFin].[Transactions]
  ADD CONSTRAINT [FK_Transactions_Accounts] FOREIGN KEY ([AccountID]) REFERENCES [SCrm].[Accounts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Jobs_Accounts] on table [SJob].[Jobs]
--
ALTER TABLE [SJob].[Jobs]
  ADD CONSTRAINT [FK_Jobs_Accounts] FOREIGN KEY ([AgentAccountID]) REFERENCES [SCrm].[Accounts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Jobs_Accounts1] on table [SJob].[Jobs]
--
ALTER TABLE [SJob].[Jobs]
  ADD CONSTRAINT [FK_Jobs_Accounts1] FOREIGN KEY ([ClientAccountID]) REFERENCES [SCrm].[Accounts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Jobs_Accounts2] on table [SJob].[Jobs]
--
ALTER TABLE [SJob].[Jobs]
  ADD CONSTRAINT [FK_Jobs_Accounts2] FOREIGN KEY ([FinanceAccountID]) REFERENCES [SCrm].[Accounts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_ProjectDirectory_Accounts] on table [SJob].[ProjectDirectory]
--
ALTER TABLE [SJob].[ProjectDirectory]
  ADD CONSTRAINT [FK_ProjectDirectory_Accounts] FOREIGN KEY ([AccountID]) REFERENCES [SCrm].[Accounts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Contracts_Accounts] on table [SSop].[Contracts]
--
ALTER TABLE [SSop].[Contracts]
  ADD CONSTRAINT [FK_Contracts_Accounts] FOREIGN KEY ([AccountID]) REFERENCES [SCrm].[Accounts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Enquiries_Accounts] on table [SSop].[Enquiries]
--
ALTER TABLE [SSop].[Enquiries]
  ADD CONSTRAINT [FK_Enquiries_Accounts] FOREIGN KEY ([ClientAccountId]) REFERENCES [SCrm].[Accounts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Enquiries_Accounts1] on table [SSop].[Enquiries]
--
ALTER TABLE [SSop].[Enquiries]
  ADD CONSTRAINT [FK_Enquiries_Accounts1] FOREIGN KEY ([AgentAccountId]) REFERENCES [SCrm].[Accounts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Enquiries_Accounts2] on table [SSop].[Enquiries]
--
ALTER TABLE [SSop].[Enquiries]
  ADD CONSTRAINT [FK_Enquiries_Accounts2] FOREIGN KEY ([FinanceAccountId]) REFERENCES [SCrm].[Accounts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Quotes_Accounts] on table [SSop].[Quotes]
--
ALTER TABLE [SSop].[Quotes]
  ADD CONSTRAINT [FK_Quotes_Accounts] FOREIGN KEY ([ClientAccountId]) REFERENCES [SCrm].[Accounts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Quotes_Accounts1] on table [SSop].[Quotes]
--
ALTER TABLE [SSop].[Quotes]
  ADD CONSTRAINT [FK_Quotes_Accounts1] FOREIGN KEY ([AgentAccountId]) REFERENCES [SCrm].[Accounts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Properties_Accounts] on table [SJob].[Assets]
--
ALTER TABLE [SJob].[Assets]
  ADD CONSTRAINT [FK_Properties_Accounts] FOREIGN KEY ([LocalAuthorityAccountID]) REFERENCES [SCrm].[Accounts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Properties_Accounts1] on table [SJob].[Assets]
--
ALTER TABLE [SJob].[Assets]
  ADD CONSTRAINT [FK_Properties_Accounts1] FOREIGN KEY ([FireAuthorityAccountID]) REFERENCES [SCrm].[Accounts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Properties_Accounts2] on table [SJob].[Assets]
--
ALTER TABLE [SJob].[Assets]
  ADD CONSTRAINT [FK_Properties_Accounts2] FOREIGN KEY ([WaterAuthorityAccountID]) REFERENCES [SCrm].[Accounts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Properties_Accounts3] on table [SJob].[Assets]
--
ALTER TABLE [SJob].[Assets]
  ADD CONSTRAINT [FK_Properties_Accounts3] FOREIGN KEY ([OwnerAccountId]) REFERENCES [SCrm].[Accounts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create or alter function [SJob].[tvf_AssetQuotes]
--
GO
CREATE OR ALTER FUNCTION [SJob].[tvf_AssetQuotes] 
(
    @UserId INT,
	@ParentGuid UNIQUEIDENTIFIER
)
RETURNS TABLE
    --WITH SCHEMABINDING
AS
RETURN 
SELECT  q.ID,
        q.RowStatus,
        q.RowVersion,
        q.Guid,
        q.Number,
		q.Date,
		LEFT(q.Overview, 200) AS Overview,
		i.Guid QuotingUserGuid,
		i.FullName AS QuotingUserName,
		qc.FullName AS QuotingConsultant
FROM    SSop.Quotes q
JOIN	SSop.EnquiryServices es on (es.Id = q.EnquiryServiceID)
join	SSop.Enquiries e on (e.Id = es.EnquiryId)
JOIN	SJob.Assets p ON (p.ID = e.PropertyId)
JOIN    SCore.Identities i ON (q.QuotingUserId = i.ID)
JOIN	SCore.Identities qc ON (qc.ID = q.QuotingConsultantId)
WHERE   (q.RowStatus  NOT IN (0, 254))
	AND	(q.Id > 0)
	AND	(p.ID > 0)
AND	(EXISTS
			(
		SELECT
				1
		FROM
				SCore.ObjectSecurityForUser_CanRead(q.Guid, @UserId) oscr
			)
		)
	AND	(p.Guid = @ParentGuid)
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create or alter function [SJob].[tvf_AccountQuotes]
--
GO
CREATE OR ALTER FUNCTION [SJob].[tvf_AccountQuotes] 
(
    @UserId INT,
	@ParentGuid UNIQUEIDENTIFIER
)
RETURNS TABLE
    --WITH SCHEMABINDING
AS
RETURN
SELECT
		q.ID,
		q.RowStatus,
		q.RowVersion,
		q.Guid,
		q.Number,
		q.Date,
		LEFT(q.Overview, 200) AS Overview,
		i.Guid				  QuotingUserGuid,
		i.FullName			  AS QuotingUserName,
		qc.FullName			  AS QuotingConsultant
FROM
		SSop.Quotes q
JOIN	SSop.EnquiryServices es on (es.Id = q.EnquiryServiceID)
JOIN	SSop.Enquiries e on (e.Id = es.EnquiryId)
JOIN
		SCrm.Accounts a ON ((a.ID = e.ClientAccountId)
					OR (a.ID = e.AgentAccountId)
					OR (a.ID = e.FinanceAccountId))
JOIN
		SCore.Identities i ON (q.QuotingUserId = i.ID)
JOIN
		SCore.Identities qc ON (qc.ID = q.QuotingConsultantId)
WHERE
		(q.RowStatus NOT IN (0, 254))
		AND (q.ID > 0)
		AND (a.Guid = @ParentGuid)
		AND (EXISTS
		(
			SELECT
					1
			FROM
					SCore.ObjectSecurityForUser_CanRead(q.Guid, @UserId) oscr
		)
		)
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create or alter procedure [SSop].[EnquiryCreateQuotes]
--
GO
CREATE OR ALTER PROCEDURE [SSop].[EnquiryCreateQuotes]
	(@Guid UNIQUEIDENTIFIER)
AS
BEGIN

	IF (EXISTS
	 (
		 SELECT 1
		 FROM	SSop.Enquiries AS q
		 WHERE	(q.Guid					 = @Guid)
			AND (q.IsReadyForQuoteReview = 0)
	 )
	   )
	BEGIN
		;
		THROW 60000, N'The enquiry must be marked ready for review first.', 1;
	END;

	IF (NOT EXISTS
	 (
		 SELECT 1
		 FROM	SSop.EnquiryServices AS es
		 JOIN	SSop.Enquiries		 AS e ON (e.ID = es.EnquiryId)
		 WHERE	(e.Guid = @Guid)
			AND (NOT EXISTS
			 (
				 SELECT 1
				 FROM	SSop.Quotes AS q
				 WHERE	(q.EnquiryServiceID = es.ID)
					AND (q.RowStatus NOT IN (0, 254))
			 )
				)
	 )
	   )
	BEGIN
		;
		THROW 60000, N'Nothing to create', 1;
	END;

	/* Get the details of the enquiry. */
	DECLARE @PropertyGuid			   UNIQUEIDENTIFIER,
			@PropertyNameNumber		   NVARCHAR(50),
			@PropertyAddressLine1	   NVARCHAR(50),
			@PropertyAddressLine2	   NVARCHAR(50),
			@PropertyAddressLine3	   NVARCHAR(50),
			@PropertyTown			   NVARCHAR(50),
			@PropertyCountyGuid		   UNIQUEIDENTIFIER,
			@PropertyPostCode		   NVARCHAR(50),
			@PropertyCountryGuid	   UNIQUEIDENTIFIER,
			@ClientAccountGuid		   UNIQUEIDENTIFIER,
			@ClientAddressGuid		   UNIQUEIDENTIFIER,
			@ClientContactGuid		   UNIQUEIDENTIFIER,
			@ClientName				   NVARCHAR(250),
			@ClientAddressNameNumber   NVARCHAR(50),
			@ClientAddressLine1		   NVARCHAR(50),
			@ClientAddressLine2		   NVARCHAR(50),
			@ClientAddressLine3		   NVARCHAR(50),
			@ClientAddressTown		   NVARCHAR(50),
			@ClientAddressCountyGuid   UNIQUEIDENTIFIER,
			@ClientAddressPostCode	   NVARCHAR(50),
			@ClientAddressCountryGuid  UNIQUEIDENTIFIER,
			@AgentAccountGuid		   UNIQUEIDENTIFIER,
			@AgentAddressGuid		   UNIQUEIDENTIFIER,
			@AgentContactGuid		   UNIQUEIDENTIFIER,
			@AgentName				   NVARCHAR(250),
			@AgentAddressNameNumber	   NVARCHAR(50),
			@AgentAddressLine1		   NVARCHAR(50),
			@AgentAddressLine2		   NVARCHAR(50),
			@AgentAddressLine3		   NVARCHAR(50),
			@AgentAddressTown		   NVARCHAR(50),
			@AgentAddressCountyGuid	   UNIQUEIDENTIFIER,
			@AgentAddressPostCode	   NVARCHAR(50),
			@AgentAddressCountryGuid   UNIQUEIDENTIFIER,
			@AccountStatusGuid		   UNIQUEIDENTIFIER,
			@QuotingUserGuid		   UNIQUEIDENTIFIER,
			@FinanceAccountGuid		   UNIQUEIDENTIFIER,
			@FinanceAddressGuid		   UNIQUEIDENTIFIER,
			@FinanceContactGuid		   UNIQUEIDENTIFIER,
			@FinanceName			   NVARCHAR(250),
			@FinanceAddressNameNumber  NVARCHAR(50),
			@FinanceAddressLine1	   NVARCHAR(50),
			@FinanceAddressLine2	   NVARCHAR(50),
			@FinanceAddressLine3	   NVARCHAR(50),
			@FinanceAddressTown		   NVARCHAR(50),
			@FinanceAddressCountyGuid  UNIQUEIDENTIFIER,
			@FinanceAddressPostCode	   NVARCHAR(50),
			@FinanceAddressCountryGuid UNIQUEIDENTIFIER,
			@ProjectGuid			   UNIQUEIDENTIFIER,
			@IsClientFinanceAccount	   BIT,
			@JobTypeId                 INT, --[CBLD-590]
			@BillingInstruction		   NVARCHAR(MAX); --It was missing


	SELECT	@PropertyGuid			   = uprn.Guid,
			@PropertyNameNumber		   = e.PropertyNameNumber,
			@PropertyAddressLine1	   = e.PropertyAddressLine1,
			@PropertyAddressLine2	   = e.PropertyAddressLine2,
			@PropertyAddressLine3	   = e.PropertyAddressLine3,
			@PropertyTown			   = e.PropertyTown,
			@PropertyCountyGuid		   = uprnc.Guid,
			@PropertyPostCode		   = e.PropertyPostCode,
			@PropertyCountryGuid	   = uprncr.Guid,
			@ClientAccountGuid		   = c.Guid,
			@ClientAddressGuid		   = c_add.Guid,
			@ClientContactGuid		   = c_con.Guid,
			@ClientName				   = e.ClientName,
			@ClientAddressNameNumber   = e.ClientAddressNameNumber,
			@ClientAddressLine1		   = e.ClientAddressLine1,
			@ClientAddressLine2		   = e.ClientAddressLine2,
			@ClientAddressLine3		   = e.ClientAddressLine3,
			@ClientAddressTown		   = e.ClientAddressTown,
			@ClientAddressCountyGuid   = c_add_c.Guid,
			@ClientAddressPostCode	   = e.ClientAddressPostCode,
			@ClientAddressCountryGuid  = c_add_cr.Guid,
			@AgentAccountGuid		   = a.Guid,
			@AgentAddressGuid		   = a_add.Guid,
			@AgentContactGuid		   = a_con.Guid,
			@AgentName				   = e.AgentName,
			@AgentAddressNameNumber	   = e.AgentAddressNameNumber,
			@AgentAddressLine1		   = e.AgentAddressLine1,
			@AgentAddressLine2		   = e.AgentAddressLine2,
			@AgentAddressLine3		   = e.AgentAddressLine3,
			@AgentAddressTown		   = e.AgentTown,
			@AgentAddressCountyGuid	   = a_add_c.Guid,
			@AgentAddressPostCode	   = e.AgentAddressPostCode,
			@AgentAddressCountryGuid   = a_add_cr.Guid,
			@FinanceAccountGuid		   = f.Guid,
			@FinanceAddressGuid		   = f_add.Guid,
			@FinanceContactGuid		   = f_con.Guid,
			@FinanceName			   = e.FinanceAccountName,
			@FinanceAddressNameNumber  = e.FinanceAddressNameNumber,
			@FinanceAddressLine1	   = e.FinanceAddressLine1,
			@FinanceAddressLine2	   = e.FinanceAddressLine2,
			@FinanceAddressLine3	   = e.FinanceAddressLine3,
			@FinanceAddressTown		   = e.FinanceTown,
			@FinanceAddressCountyGuid  = f_add_c.Guid,
			@FinanceAddressPostCode	   = e.FinancePostCode,
			@FinanceAddressCountryGuid = f_add_cr.Guid,
			@QuotingUserGuid		   = i.Guid,
			@IsClientFinanceAccount	   = e.IsClientFinanceAccount,
			@ProjectGuid			   = p.Guid
	FROM	SSop.Enquiries			  AS e
	JOIN	SCore.OrganisationalUnits AS ou ON (ou.ID			  = e.OrganisationalUnitID)
	JOIN	SCore.Identities		  AS i ON (i.ID				  = e.CreatedByUserId)
	JOIN	SJob.Assets			  AS uprn ON (uprn.ID		  = e.PropertyId)
	JOIN	SCrm.Counties			  AS uprnc ON (uprnc.ID		  = e.PropertyCountyId)
	JOIN	SCrm.Countries			  AS uprncr ON (uprncr.ID	  = e.PropertyCountryId)
	JOIN	SCrm.Accounts			  AS c ON (c.ID				  = e.ClientAccountId)
	JOIN	SCrm.AccountAddresses	  AS c_add ON (c_add.ID		  = e.ClientAddressId)
	JOIN	SCrm.Counties			  AS c_add_c ON (c_add_c.ID	  = e.ClientAddressCountyId)
	JOIN	SCrm.Countries			  AS c_add_cr ON (c_add_cr.ID = e.ClientAddressCountryId)
	JOIN	SCrm.AccountContacts	  AS c_con ON (c_con.ID		  = e.ClientAccountContactId)
	JOIN	SCrm.Accounts			  AS a ON (a.ID				  = e.AgentAccountId)
	JOIN	SCrm.AccountAddresses	  AS a_add ON (a_add.ID		  = e.AgentAddressId)
	JOIN	SCrm.Counties			  AS a_add_c ON (a_add_c.ID	  = e.AgentCountyId)
	JOIN	SCrm.Countries			  AS a_add_cr ON (a_add_cr.ID = e.AgentCountryId)
	JOIN	SCrm.Accounts			  AS f ON (f.ID				  = e.FinanceAccountId)
	JOIN	SCrm.AccountAddresses	  AS f_add ON (f_add.ID		  = e.FinanceAddressId)
	JOIN	SCrm.Counties			  AS f_add_c ON (f_add_c.ID	  = e.FinanceCountyId)
	JOIN	SCrm.Countries			  AS f_add_cr ON (f_add_cr.ID = f_add_c.CountryID)
	JOIN	SCrm.AccountContacts	  AS f_con ON (f_con.ID		  = e.FinanceContactId)
	JOIN	SCrm.AccountContacts	  AS a_con ON (a_con.ID		  = e.AgentAccountContactId)
	JOIN	SSop.Projects			  AS p ON (p.ID				  = e.ProjectId)
	WHERE	(e.Guid = @Guid);

	/* Convert new structure details */
	IF (@PropertyGuid = '00000000-0000-0000-0000-000000000000')
	BEGIN
		SET @PropertyGuid = NEWID ();

		EXEC SJob.AssetsUpsert @ParentAssetGuid = '00000000-0000-0000-0000-000000000000',		-- uniqueidentifier
								   @Name = N'',															-- nvarchar(100)
								   @Number = @PropertyNameNumber,										-- nvarchar(50)
								   @AddressLine1 = @PropertyAddressLine1,								-- nvarchar(50)
								   @AddressLine2 = @PropertyAddressLine2,								-- nvarchar(50)
								   @AddressLine3 = @PropertyAddressLine3,								-- nvarchar(50)
								   @Town = @PropertyTown,												-- nvarchar(50)
								   @CountyGuid = @PropertyCountyGuid,									-- nvarchar(50)
								   @Postcode = @PropertyPostCode,										-- nvarchar(50)
								   @CountryGuid = @PropertyCountryGuid,
								   @LocalAuthorityAccountGuid = '00000000-0000-0000-0000-000000000000', -- uniqueidentifier
								   @FireAuthorityAccountGuid = '00000000-0000-0000-0000-000000000000',	-- uniqueidentifier
								   @WaterAuthorityAccountGuid = '00000000-0000-0000-0000-000000000000', -- uniqueidentifier
								   @Latitude = 0,														-- decimal(9, 6)
								   @Longitude = 0,														-- decimal(9, 6)
								   @IsHighRiskBuilding = 0,
								   @IsComplexBuilding = 0,
								   @BuildingHeightInMetres = 0,
								   @OwnerAccountGuid = '00000000-0000-0000-0000-000000000000',
								   @Guid = @PropertyGuid;												-- uniqueidentifier

	END;

	SELECT	@AccountStatusGuid = s.Guid
	FROM	SCrm.AccountStatus AS s
	WHERE	(s.Name = N'Prospect');

	/* Convert new client details */
	IF (@ClientAccountGuid = '00000000-0000-0000-0000-000000000000')
   AND	(@ClientName <> N'')
	BEGIN
		SET @ClientAccountGuid = NEWID ();

		EXEC SCrm.AccountsUpsert @Name = @ClientName,											-- nvarchar(250)
								 @Code = N'',													-- nvarchar(10)
								 @AccountStatusGuid = @AccountStatusGuid,						-- uniqueidentifier
								 @ParentAccountGuid = '00000000-0000-0000-0000-000000000000',	-- uniqueidentifier
								 @IsPurchaseLedger = 0,											-- bit
								 @IsSalesLedger = 1,											-- bit
								 @IsLocalAuthority = 0,											-- bit
								 @IsFireAuthority = 0,											-- bit
								 @IsWaterAuthority = 0,											-- bit
								 @RelationshipManagerUserGuid = @QuotingUserGuid,				-- uniqueidentifier
								 @CompanyRegistrationNumber = N'',								-- nvarchar(50)
								 @MainAccountContactGuid = '00000000-0000-0000-0000-000000000000',
								 @MainAccountAddressGuid = '00000000-0000-0000-0000-000000000000',
								 @Guid = @ClientAccountGuid,									-- uniqueidentifier
								 @BillingInstruction = NULL; --Since it is a new Account record, we can set it to null

	END;

	IF (
		   @ClientAddressGuid = '00000000-0000-0000-0000-000000000000'
	   AND	@ClientAddressNameNumber <> N''
	   )
	BEGIN
		SET @ClientAddressGuid = NEWID ();

		EXEC SCrm.AddressUpsert @AddressNumber = 0,							-- int
								@Name = N'',								-- nvarchar(100)
								@Number = @ClientAddressNameNumber,			-- nvarchar(100)
								@AddressLine1 = @ClientAddressLine1,		-- nvarchar(255)
								@AddressLine2 = @ClientAddressLine2,		-- nvarchar(255)
								@AddressLine3 = @ClientAddressLine3,		-- nvarchar(255)
								@Town = @ClientAddressTown,					-- nvarchar(255)
								@CountyGuid = @ClientAddressCountyGuid,		-- uniqueidentifier
								@Postcode = @ClientAddressPostCode,			-- nvarchar(50)
								@CountryGuid = @ClientAddressCountryGuid,	-- uniqueidentifier
								@Guid = @ClientAddressGuid OUTPUT;			-- uniqueidentifier

		DECLARE @AccountAddressGuid UNIQUEIDENTIFIER = NEWID ();

		EXEC SCrm.AccountAddressesUpsert @AccountGuid = @ClientAccountGuid, -- uniqueidentifier
										 @AddressGuid = @ClientAddressGuid, -- uniqueidentifier
										 @Guid = @AccountAddressGuid;		-- uniqueidentifier

		SET @ClientAddressGuid = @AccountAddressGuid;

		IF (EXISTS
		 (
			 SELECT 1
			 FROM	SCrm.Accounts AS a
			 WHERE	(a.MainAccountAddressId < 0)
				AND (a.Guid					= @ClientAccountGuid)
		 )
		   )
		BEGIN
			UPDATE	a
			SET		a.MainAccountAddressId = aa.ID
			FROM	SCrm.Accounts		  AS a
			JOIN	SCrm.AccountAddresses AS aa ON (aa.AccountID = a.ID)
			WHERE	(a.Guid = @ClientAccountGuid);
		END;
	END;

	IF (@IsClientFinanceAccount = 1)
	BEGIN
		SET @FinanceAccountGuid = @ClientAccountGuid;
		SET @FinanceAddressGuid = @ClientAddressGuid;
		SET @FinanceContactGuid = @ClientContactGuid;
	END;

	/* Convert new agent details */
	IF (@AgentAccountGuid = '00000000-0000-0000-0000-000000000000')
   AND	(@AgentName <> N'')
	BEGIN
		SET @AgentAccountGuid = NEWID ();

		EXEC SCrm.AccountsUpsert @Name = @AgentName,											-- nvarchar(250)
								 @Code = N'',													-- nvarchar(10)
								 @AccountStatusGuid = @AccountStatusGuid,						-- uniqueidentifier
								 @ParentAccountGuid = '00000000-0000-0000-0000-000000000000',	-- uniqueidentifier
								 @IsPurchaseLedger = 0,											-- bit
								 @IsSalesLedger = 1,											-- bit
								 @IsLocalAuthority = 0,											-- bit
								 @IsFireAuthority = 0,											-- bit
								 @IsWaterAuthority = 0,											-- bit
								 @RelationshipManagerUserGuid = @QuotingUserGuid,				-- uniqueidentifier
								 @CompanyRegistrationNumber = N'',								-- nvarchar(50)
								 @MainAccountAddressGuid = '00000000-0000-0000-0000-000000000000',
								 @MainAccountContactGuid = '00000000-0000-0000-0000-000000000000',
								 @Guid = @AgentAccountGuid,										-- uniqueidentifier
								 @BillingInstruction = NULL; --Same as above --> Since it is new, it can be set to null.

	END;

	IF (
		   @AgentAddressGuid = '00000000-0000-0000-0000-000000000000'
	   AND	@AgentAddressNameNumber <> N''
	   )
	BEGIN
		SET @AgentAddressGuid = NEWID ();

		EXEC SCrm.AddressUpsert @AddressNumber = 0,							-- int
								@Name = N'',								-- nvarchar(100)
								@Number = @AgentAddressNameNumber,			-- nvarchar(100)
								@AddressLine1 = @AgentAddressLine1,			-- nvarchar(255)
								@AddressLine2 = @AgentAddressLine2,			-- nvarchar(255)
								@AddressLine3 = @AgentAddressLine3,			-- nvarchar(255)
								@Town = @AgentAddressTown,					-- nvarchar(255)
								@CountyGuid = @AgentAddressCountyGuid,		-- uniqueidentifier
								@Postcode = @AgentAddressPostCode,			-- nvarchar(50)
								@CountryGuid = @AgentAddressCountryGuid,	-- uniqueidentifier
								@Guid = @AgentAddressGuid OUTPUT;			-- uniqueidentifier

		DECLARE @AgentAccountAddressGuid UNIQUEIDENTIFIER = NEWID ();

		EXEC SCrm.AccountAddressesUpsert @AccountGuid = @AgentAccountGuid,	-- uniqueidentifier
										 @AddressGuid = @AgentAddressGuid,	-- uniqueidentifier
										 @Guid = @AgentAccountAddressGuid;	-- uniqueidentifier

		SET @AgentAddressGuid = @AgentAccountAddressGuid;

		IF (EXISTS
		 (
			 SELECT 1
			 FROM	SCrm.Accounts AS a
			 WHERE	(a.MainAccountAddressId < 0)
				AND (a.Guid					= @AgentAccountGuid)
		 )
		   )
		BEGIN
			UPDATE	a
			SET		a.MainAccountAddressId = aa.ID
			FROM	SCrm.Accounts		  AS a
			JOIN	SCrm.AccountAddresses AS aa ON (aa.AccountID = a.ID)
			WHERE	(a.Guid = @AgentAccountGuid);
		END;
	END;

	/* Convert new finance details */
	IF (@FinanceAccountGuid = '00000000-0000-0000-0000-000000000000')
   AND	(@FinanceName <> N'')
   AND	(@IsClientFinanceAccount = 0)
	BEGIN
		SET @FinanceAccountGuid = NEWID ();

		EXEC SCrm.AccountsUpsert @Name = @FinanceName,											-- nvarchar(250)
								 @Code = N'',													-- nvarchar(10)
								 @AccountStatusGuid = @AccountStatusGuid,						-- uniqueidentifier
								 @ParentAccountGuid = '00000000-0000-0000-0000-000000000000',	-- uniqueidentifier
								 @IsPurchaseLedger = 0,											-- bit
								 @IsSalesLedger = 1,											-- bit
								 @IsLocalAuthority = 0,											-- bit
								 @IsFireAuthority = 0,											-- bit
								 @IsWaterAuthority = 0,											-- bit
								 @RelationshipManagerUserGuid = @QuotingUserGuid,				-- uniqueidentifier
								 @CompanyRegistrationNumber = N'',								-- nvarchar(50)
								 @MainAccountAddressGuid = '00000000-0000-0000-0000-000000000000',
								 @MainAccountContactGuid = '00000000-0000-0000-0000-000000000000',
								 @Guid = @FinanceAccountGuid,									-- uniqueidentifier
								 @BillingInstruction = NULL; --Same as above -> New record can be set to null
	END;

	IF (
		   @FinanceAddressGuid = '00000000-0000-0000-0000-000000000000'
	   AND	@FinanceAddressNameNumber <> N''
	   AND	(@IsClientFinanceAccount = 0)
	   )
	BEGIN
		SET @FinanceAddressGuid = NEWID ();

		EXEC SCrm.AddressUpsert @AddressNumber = 0,							-- int
								@Name = N'',								-- nvarchar(100)
								@Number = @FinanceAddressNameNumber,		-- nvarchar(100)
								@AddressLine1 = @FinanceAddressLine1,		-- nvarchar(255)
								@AddressLine2 = @FinanceAddressLine2,		-- nvarchar(255)
								@AddressLine3 = @FinanceAddressLine3,		-- nvarchar(255)
								@Town = @FinanceAddressTown,				-- nvarchar(255)
								@CountyGuid = @FinanceAddressCountyGuid,	-- uniqueidentifier
								@Postcode = @FinanceAddressPostCode,		-- nvarchar(50)
								@CountryGuid = @FinanceAddressCountryGuid,	-- uniqueidentifier
								@Guid = @FinanceAddressGuid OUTPUT;			-- uniqueidentifier

		DECLARE @FinanceAccountAddressGuid UNIQUEIDENTIFIER = NEWID ();
		
		
		EXEC SCrm.AddressUpsert @AccountGuid = @FinanceAccountGuid, -- uniqueidentifier
								@AddressGuid = @FinanceAddressGuid, -- uniqueidentifier
								@Guid = @FinanceAccountAddressGuid; -- uniqueidentifier

		

		SET @FinanceAddressGuid = @FinanceAccountAddressGuid;

		IF (EXISTS
		 (
			 SELECT 1
			 FROM	SCrm.Accounts AS a
			 WHERE	(a.MainAccountAddressId < 0)
				AND (a.Guid					= @FinanceAccountGuid)
		 )
		   )
		BEGIN
			UPDATE	a
			SET		a.MainAccountAddressId = aa.ID
			FROM	SCrm.Accounts		  AS a
			JOIN	SCrm.AccountAddresses AS aa ON (aa.AccountID = a.ID)
			WHERE	(a.Guid = @FinanceAccountGuid);
		END;
	END;

	/* Build a consolidated list of quotes to create  */
	DECLARE @QuotesToCreate TABLE
		(
			ID INT NOT NULL PRIMARY KEY,
			Guid UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID (),
			OrganisationalUnitGuid UNIQUEIDENTIFIER NOT NULL,
			EnquiryGuid UNIQUEIDENTIFIER NOT NULL,
			DescriptionOfWorks NVARCHAR(4000) NOT NULL,
			JobTypeName NVARCHAR(100) NOT NULL,
			JobTypeId	INT NOT NULL, 
			SendInfoToClient BIT NOT NULL,
			SendInfoToAgent BIT NOT NULL,
			ExternalReference NVARCHAR(50) NOT NULL,
			ValueOfWork DECIMAL(19, 2) NOT NULL,
			CurrentStageGuid UNIQUEIDENTIFIER NOT NULL,
			AppointmentStageGuid UNIQUEIDENTIFIER NOT NULL,
			IsSubjectToNDA BIT NOT NULL,
			EnquiryServiceGuid UNIQUEIDENTIFIER NOT NULL
		);

	INSERT	@QuotesToCreate
		 (ID,
		  OrganisationalUnitGuid,
		  EnquiryGuid,
		  DescriptionOfWorks,
		  JobTypeName,
		  JobTypeId,
		  SendInfoToClient,
		  SendInfoToAgent,
		  ExternalReference,
		  ValueOfWork,
		  CurrentStageGuid,
		  AppointmentStageGuid,
		  IsSubjectToNDA,
		  EnquiryServiceGuid)
	SELECT	es.ID,
			ou.Guid,
			@Guid,
			e.DescriptionOfWorks,
			jt.Name,
			jt.ID, 
			e.SendInfoToClient,
			e.SendInfoToAgent,
			e.ExternalReference,
			e.ValueOfWork,
			cs.Guid,
			aps.Guid,
			e.IsSubjectToNDA,
			es.Guid
	FROM	SSop.EnquiryServices	  AS es
	JOIN	SSop.Enquiries			  AS e ON (e.ID		= es.EnquiryId)
	JOIN	SJob.JobTypes			  AS jt ON (jt.ID	= es.JobTypeId)
	JOIN	SCore.OrganisationalUnits AS ou ON (ou.ID	= jt.OrganisationalUnitID)
	JOIN	SJob.RibaStages			  AS cs ON (cs.ID	= e.CurrentProjectRibaStageID)
	JOIN	SJob.RibaStages			  AS aps ON (aps.ID = es.StartRibaStageId)
	WHERE	(e.Guid = @Guid)
		AND (es.RowStatus NOT IN (0, 254))
		AND (NOT EXISTS
		(
			SELECT	1
			FROM	SSop.Quotes AS q
			WHERE	(q.EnquiryServiceID = es.ID)
				AND (q.RowStatus NOT IN (0, 254))
		)
			);

	IF NOT EXISTS
	 (
		 SELECT 1
		 FROM	@QuotesToCreate
	 )
	BEGIN
		;
		THROW 60000, N'There were no quotes to create', 1;
	END;

	/*
		  Loop through the list of Quotes executing QuotesUpsert
	  */
	DECLARE @CreatedDateTime		DATETIME2 = GETUTCDATE (),
			@ExpiryDate				DATETIME2 = DATEADD (	MONTH,
															6,
															GETUTCDATE ()
														),
			@OrganisationalUnitGuid UNIQUEIDENTIFIER,
			@DescriptionOfWorks		NVARCHAR(4000),
			@QuoteGuid				UNIQUEIDENTIFIER,
			@MaxID					INT,
			@CurrentId				INT,
			@ExternalReference		NVARCHAR(50),
			@CurrentStageGuid		UNIQUEIDENTIFIER,
			@AppointmentStageGuid	UNIQUEIDENTIFIER,
			@EnquiryServiceGuid		UNIQUEIDENTIFIER;


	SELECT	@MaxID	   = MAX (ID),
			@CurrentId = 0
	FROM	@QuotesToCreate;

	WHILE (@CurrentId < @MaxID)
	BEGIN
		SELECT		TOP (1) @CurrentId				= q.ID,
							@DescriptionOfWorks		= q.JobTypeName + N' -- ' + q.DescriptionOfWorks,
							@QuoteGuid				= q.Guid,
							@OrganisationalUnitGuid = q.OrganisationalUnitGuid,
							@ExternalReference		= q.ExternalReference,
							@CurrentStageGuid		= q.CurrentStageGuid,
							@AppointmentStageGuid	= q.AppointmentStageGuid,
							@EnquiryServiceGuid		= q.EnquiryServiceGuid,
							@JobTypeId = q.JobTypeId
		FROM		@QuotesToCreate AS q
		WHERE		(q.ID > @CurrentId)
		ORDER BY	q.ID;

		EXEC SSop.QuotesUpsert @OrganisationalUnitGuid = @OrganisationalUnitGuid,		-- uniqueidentifier
							   @QuotingUserGuid = @QuotingUserGuid,						-- uniqueidentifier
							   @ContractGuid = '00000000-0000-0000-0000-000000000000',	-- uniqueidentifier
							   @Date = @CreatedDateTime,								-- date
							   @Overview = @DescriptionOfWorks,							-- nvarchar(max)
							   @ExpiryDate = @ExpiryDate,								-- date
							   @DateSent = NULL,										-- date
							   @DateAccepted = NULL,									-- date
							   @DateRejected = NULL,									-- date
							   @RejectionReason = N'',									-- nvarchar(max)
							   @FeeCap = 0,												-- decimal(19, 2)
							   @IsFinal = 0,
							   @ExternalReference = @ExternalReference,
							   @QuotingConsultantGuid = @QuotingUserGuid,
							   @AppointmentFromRibaStageGuid = @AppointmentStageGuid,
							   @CurrentStageGuid = @CurrentStageGuid,
							   @DeadDate = NULL,
							   @EnquiryServiceGuid = @EnquiryServiceGuid,
							   @ProjectGuid = @ProjectGuid,
							   @Guid = @QuoteGuid,
							   @JobType = @EnquiryServiceGuid,	
							   @DescriptionOfWorks = @DescriptionOfWorks,
							   @DeclinedToQuoteReason = N'',
							   @ExclusionsAndLimitations = N'';
							  
	END;

	DECLARE @PropertyID		  INT,
			@ClientID		  INT,
			@AgentID		  INT,
			@FinanceID		  INT,
			@ClientAddressID  INT,
			@AgentAddressID	  INT,
			@FinanceAddressID INT;

	SELECT	@PropertyID = p.ID
	FROM	SJob.Assets AS p
	WHERE	(p.Guid = @PropertyGuid);

	SELECT	@ClientID = a.ID
	FROM	SCrm.Accounts AS a
	WHERE	(a.Guid = @ClientAccountGuid);

	SELECT	@ClientAddressID = a.ID
	FROM	SCrm.AccountAddresses AS a
	WHERE	(a.Guid = @ClientAddressGuid);

	SELECT	@AgentID = a.ID
	FROM	SCrm.Accounts AS a
	WHERE	(a.Guid = @AgentAccountGuid);

	SELECT	@AgentAddressID = a.ID
	FROM	SCrm.AccountAddresses AS a
	WHERE	(a.Guid = @AgentAddressGuid);

	SELECT	@FinanceID = a.ID
	FROM	SCrm.Accounts AS a
	WHERE	(a.Guid = @FinanceAccountGuid);

	SELECT	@FinanceAddressID = a.ID
	FROM	SCrm.AccountAddresses AS a
	WHERE	(a.Guid = @FinanceAddressGuid);

	/* Update the Enquiry with the created records */
	UPDATE	SSop.Enquiries
	SET		PropertyId = @PropertyID,
			ClientAccountId = @ClientID,
			AgentAccountId = @AgentID,
			FinanceAccountId = @FinanceID,
			ClientAddressId = @ClientAddressID,
			AgentAddressId = @AgentAddressID,
			FinanceAddressId = @FinanceAddressID,
			EnterNewClientDetails = 0,
			EnterNewAgentDetails = 0,
			EnterNewFinanceDetails = 0,
			EnterNewStructureDetails = 0
	WHERE	(Guid = @Guid);

END;
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_ContractBands_ContractId] on table [SSop].[ContractBands]
--
ALTER TABLE [SSop].[ContractBands]
  DROP CONSTRAINT [FK_ContractBands_ContractId]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_ContractBands_Guid] on table [SSop].[ContractBands]
--
ALTER TABLE [SSop].[ContractBands]
  DROP CONSTRAINT [FK_ContractBands_Guid]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_ContractBands_PriceListId] on table [SSop].[ContractBands]
--
ALTER TABLE [SSop].[ContractBands]
  DROP CONSTRAINT [FK_ContractBands_PriceListId]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_ContractBands_RowStatus] on table [SSop].[ContractBands]
--
ALTER TABLE [SSop].[ContractBands]
  DROP CONSTRAINT [FK_ContractBands_RowStatus]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Rename table [SSop].[ContractBands] to [SSop].[tmp_devart_ContractBands]
--
DECLARE @res int
EXEC @res = sp_rename N'[SSop].[ContractBands]', N'tmp_devart_ContractBands', 'OBJECT'
IF @res <> 0
  RAISERROR ('Error while Rename table [SSop].[ContractBands] to [SSop].[tmp_devart_ContractBands]', 11, 1 );
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Rename index [PK_ContractBands_ID] to [tmp_devart_PK_ContractBands_ID] on table [SSop].[ContractBands]
--
DECLARE @res int
EXEC @res = sp_rename N'[SSop].[PK_ContractBands_ID]', N'tmp_devart_PK_ContractBands_ID', 'OBJECT'
IF @res <> 0
  RAISERROR ('Error while Rename index [PK_ContractBands_ID] to [tmp_devart_PK_ContractBands_ID] on table [SSop].[ContractBands]', 11, 1 );
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Rename default [DC_ContractBands_ContractId] to [tmp_devart_DC_ContractBands_ContractId] on table [SSop].[ContractBands]
--
DECLARE @res int
EXEC @res = sp_rename N'[SSop].[DC_ContractBands_ContractId]', N'tmp_devart_DC_ContractBands_ContractId', 'OBJECT'
IF @res <> 0
  RAISERROR ('Error while Rename default [DC_ContractBands_ContractId] to [tmp_devart_DC_ContractBands_ContractId] on table [SSop].[ContractBands]', 11, 1 );
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Rename default [DC_ContractBands_Guid] to [tmp_devart_DC_ContractBands_Guid] on table [SSop].[ContractBands]
--
DECLARE @res int
EXEC @res = sp_rename N'[SSop].[DC_ContractBands_Guid]', N'tmp_devart_DC_ContractBands_Guid', 'OBJECT'
IF @res <> 0
  RAISERROR ('Error while Rename default [DC_ContractBands_Guid] to [tmp_devart_DC_ContractBands_Guid] on table [SSop].[ContractBands]', 11, 1 );
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Rename default [DC_ContractBands_RowStatus] to [tmp_devart_DC_ContractBands_RowStatus] on table [SSop].[ContractBands]
--
DECLARE @res int
EXEC @res = sp_rename N'[SSop].[DC_ContractBands_RowStatus]', N'tmp_devart_DC_ContractBands_RowStatus', 'OBJECT'
IF @res <> 0
  RAISERROR ('Error while Rename default [DC_ContractBands_RowStatus] to [tmp_devart_DC_ContractBands_RowStatus] on table [SSop].[ContractBands]', 11, 1 );
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create table [SSop].[ContractBands]
--
CREATE TABLE [SSop].[ContractBands] (
  [ID] [int] IDENTITY,
  [RowStatus] [tinyint] NOT NULL CONSTRAINT [DC_ContractBands_RowStatus] DEFAULT (1),
  [RowVersion] [timestamp],
  [Guid] [uniqueidentifier] NOT NULL CONSTRAINT [DC_ContractBands_Guid] DEFAULT (newid()) ROWGUIDCOL,
  [ContractId] [int] NOT NULL CONSTRAINT [DC_ContractBands_ContractId] DEFAULT (-1),
  [PriceListId] [int] NOT NULL CONSTRAINT [DF_ContractBands_PriveListId] DEFAULT (-1),
  [MinValueOfWork] [decimal](19, 2) NOT NULL CONSTRAINT [DF_ContractBands_MinValue] DEFAULT (0),
  [MaxValueOfWork] [decimal](19, 2) NOT NULL CONSTRAINT [DF_ContractBands_MaxValue] DEFAULT (0)
)
ON [PRIMARY]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Restore data to the table [SSop].[ContractBands]
--
SET IDENTITY_INSERT [SSop].[ContractBands] ON

INSERT [SSop].[ContractBands]([ID], [RowStatus], [Guid], [ContractId], [PriceListId], [MinValueOfWork], [MaxValueOfWork])
  SELECT [ID], [RowStatus], [Guid], [ContractId], [PriceListId], [MinValueOfWork], [MaxValueOfWork] FROM [SSop].[tmp_devart_ContractBands] WITH (NOLOCK)
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

if @@ERROR = 0
  DROP TABLE [SSop].[tmp_devart_ContractBands]

SET IDENTITY_INSERT [SSop].[ContractBands] OFF
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create primary key [PK_ContractBands_ID] on table [SSop].[ContractBands]
--
ALTER TABLE [SSop].[ContractBands]
  ADD CONSTRAINT [PK_ContractBands_ID] PRIMARY KEY CLUSTERED ([ID]) WITH (FILLFACTOR = 80)
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_ContractBands_RowStatus] on table [SSop].[ContractBands]
--
ALTER TABLE [SSop].[ContractBands]
  ADD CONSTRAINT [FK_ContractBands_RowStatus] FOREIGN KEY ([RowStatus]) REFERENCES [SCore].[RowStatus] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_ContractBands_PriceListId] on table [SSop].[ContractBands]
--
ALTER TABLE [SSop].[ContractBands]
  ADD CONSTRAINT [FK_ContractBands_PriceListId] FOREIGN KEY ([PriceListId]) REFERENCES [SSop].[PriceLists] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_ContractBands_Guid] on table [SSop].[ContractBands]
--
ALTER TABLE [SSop].[ContractBands] WITH NOCHECK
  ADD CONSTRAINT [FK_ContractBands_Guid] FOREIGN KEY ([Guid]) REFERENCES [SCore].[DataObjects] ([Guid])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_ContractBands_ContractId] on table [SSop].[ContractBands]
--
ALTER TABLE [SSop].[ContractBands]
  ADD CONSTRAINT [FK_ContractBands_ContractId] FOREIGN KEY ([ContractId]) REFERENCES [SSop].[Contracts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Disable foreign key [FK_ContractBands_Guid] on table [SSop].[ContractBands]
--
ALTER TABLE [SSop].[ContractBands]
  NOCHECK CONSTRAINT [FK_ContractBands_Guid]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_QuoteTemplates_ContractBandId] on table [SSop].[QuoteTemplates]
--
ALTER TABLE [SSop].[QuoteTemplates]
  ADD CONSTRAINT [FK_QuoteTemplates_ContractBandId] FOREIGN KEY ([ContractBandId]) REFERENCES [SSop].[ContractBands] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Jobs_Addresses] on table [SJob].[Jobs]
--
ALTER TABLE [SJob].[Jobs]
  ADD CONSTRAINT [FK_Jobs_Addresses] FOREIGN KEY ([ClientAddressID]) REFERENCES [SCrm].[AccountAddresses] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Jobs_Addresses1] on table [SJob].[Jobs]
--
ALTER TABLE [SJob].[Jobs]
  ADD CONSTRAINT [FK_Jobs_Addresses1] FOREIGN KEY ([AgentAddressID]) REFERENCES [SCrm].[AccountAddresses] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Jobs_Addresses2] on table [SJob].[Jobs]
--
ALTER TABLE [SJob].[Jobs]
  ADD CONSTRAINT [FK_Jobs_Addresses2] FOREIGN KEY ([FinanceAddressID]) REFERENCES [SCrm].[AccountAddresses] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Enquiries_AccountAddresses] on table [SSop].[Enquiries]
--
ALTER TABLE [SSop].[Enquiries]
  ADD CONSTRAINT [FK_Enquiries_AccountAddresses] FOREIGN KEY ([FinanceAddressId]) REFERENCES [SCrm].[AccountAddresses] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Enquiries_Addresses] on table [SSop].[Enquiries]
--
ALTER TABLE [SSop].[Enquiries]
  ADD CONSTRAINT [FK_Enquiries_Addresses] FOREIGN KEY ([ClientAddressId]) REFERENCES [SCrm].[AccountAddresses] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Enquiries_Addresses1] on table [SSop].[Enquiries]
--
ALTER TABLE [SSop].[Enquiries]
  ADD CONSTRAINT [FK_Enquiries_Addresses1] FOREIGN KEY ([AgentAddressId]) REFERENCES [SCrm].[AccountAddresses] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Jobs_Contacts] on table [SJob].[Jobs]
--
ALTER TABLE [SJob].[Jobs]
  ADD CONSTRAINT [FK_Jobs_Contacts] FOREIGN KEY ([AgentContactID]) REFERENCES [SCrm].[AccountContacts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Jobs_Contacts1] on table [SJob].[Jobs]
--
ALTER TABLE [SJob].[Jobs]
  ADD CONSTRAINT [FK_Jobs_Contacts1] FOREIGN KEY ([ClientContactID]) REFERENCES [SCrm].[AccountContacts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Jobs_Contacts3] on table [SJob].[Jobs]
--
ALTER TABLE [SJob].[Jobs]
  ADD CONSTRAINT [FK_Jobs_Contacts3] FOREIGN KEY ([FinanceContactID]) REFERENCES [SCrm].[AccountContacts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Enquiries_AccountContacts] on table [SSop].[Enquiries]
--
ALTER TABLE [SSop].[Enquiries]
  ADD CONSTRAINT [FK_Enquiries_AccountContacts] FOREIGN KEY ([AgentAccountContactId]) REFERENCES [SCrm].[AccountContacts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Enquiries_AccountContacts1] on table [SSop].[Enquiries]
--
ALTER TABLE [SSop].[Enquiries]
  ADD CONSTRAINT [FK_Enquiries_AccountContacts1] FOREIGN KEY ([ClientAccountContactId]) REFERENCES [SCrm].[AccountContacts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_Enquiries_AccountContacts2] on table [SSop].[Enquiries]
--
ALTER TABLE [SSop].[Enquiries]
  ADD CONSTRAINT [FK_Enquiries_AccountContacts2] FOREIGN KEY ([FinanceContactId]) REFERENCES [SCrm].[AccountContacts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_ProjectDirectory_Contacts] on table [SJob].[ProjectDirectory]
--
ALTER TABLE [SJob].[ProjectDirectory]
  ADD CONSTRAINT [FK_ProjectDirectory_Contacts] FOREIGN KEY ([ContactID]) REFERENCES [SCrm].[Contacts] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create or alter function [SCore].[tvf_GetScheduledActivities]
--
GO
/*
	[*] Returns upcoming scheduled activities for a user.
	[*] Used in the "Scheduler" to popuate the calendar.
*/
CREATE OR ALTER FUNCTION [SCore].[tvf_GetScheduledActivities] 
(
	@UserId INT,
	@StartDate DATETIME,
	@EndDate DATETIME
)
RETURNS TABLE
AS
RETURN
(
   SELECT 
	root_hobt.SurveyorID AS UserId,
	root_hobt.Date AS StartDate,
	root_hobt.EndDate,
	root_hobt.Title,
	j.Number as JobNumber,
	root_hobt.Notes AS Note
FROM 
	SJob.Activities root_hobt
LEFT JOIN SJob.Jobs AS j ON j.ID = root_hobt.JobID
WHERE 
	(
		root_hobt.SurveyorID = @UserId AND 
		root_hobt.ActivityStatusID = 2 AND 
		(root_hobt.Date >= @StartDate AND root_hobt.Date < @EndDate)
	) --Tentative (REWRITE AS EXISTS)
);
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Commit Transaction
--
IF @@TRANCOUNT>0 COMMIT TRANSACTION
GO

--
-- Create full-text index on table [SCrm].[Accounts]
--
CREATE FULLTEXT INDEX
  ON [SCrm].[Accounts]([Name] LANGUAGE 1033)
  KEY INDEX [PK_Accounts]
  ON [AccountName]
  WITH CHANGE_TRACKING AUTO, STOPLIST Honorifics
GO
IF @@ERROR <> 0 SET NOEXEC ON
GO

--
-- Set NOEXEC to off
--
SET NOEXEC OFF
GO