--
-- Script was generated by Devart dbForge Data Compare for SQL Server, Version 7.1.63.0
-- Product Home Page: https://www.devart.com/dbforge/sql/datacompare
-- Script date 04/08/2025 15:58:27
-- Source server version: 16.00.0000
-- Target server version: 16.00.1000
-- Target connection string: Data Source=soc-sqldevbre01.esgl.co.uk\General;Integrated Security=True;User ID=ESGL\Richard.Brindley
-- Run this script against CymBuild_Upgrade_Stage to synchronize it with Schema
-- Please backup your target database before running this script
--

SET LANGUAGE 'British English'
SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT, XACT_ABORT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS OFF
GO

--
-- Start Transaction
--
BEGIN TRANSACTION

--
-- Disabling DML triggers for [SCore].[EntityProperties]
--
GO
DISABLE TRIGGER ALL ON SCore.EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Disabling DML triggers for [SCore].[EntityQueries]
--
GO
DISABLE TRIGGER ALL ON SCore.EntityQueries
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Disabling DML triggers for [SCore].[EntityQueryParameters]
--
GO
DISABLE TRIGGER ALL ON SCore.EntityQueryParameters
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Disabling DML triggers for [SCore].[LanguageLabelTranslations]
--
GO
DISABLE TRIGGER ALL ON SCore.LanguageLabelTranslations
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityProperties]
--
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_DropDownListDefinitions
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_EntityDataTypes
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_EntityHoBTs
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_EntityPropertyGroupID
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_LanguageLabels
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityQueries]
--
ALTER TABLE SCore.EntityQueries
  DROP CONSTRAINT IF EXISTS FK_EntityQueries_DataObjects
ALTER TABLE SCore.EntityQueries
  DROP CONSTRAINT IF EXISTS FK_EntityQueries_EntityHoBTs
ALTER TABLE SCore.EntityQueries
  DROP CONSTRAINT IF EXISTS FK_EntityQueries_EntityTypes
ALTER TABLE SCore.EntityQueries
  DROP CONSTRAINT IF EXISTS FK_EntityQueries_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityQueryParameters]
--
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS FK_EntityQueryParameters_DataObjects
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS FK_EntityQueryParameters_EntityDataTypes
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS FK_EntityQueryParameters_EntityProperties
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS FK_EntityQueryParameters_EntityQueries
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS FK_EntityQueryParameters_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[LanguageLabelTranslations]
--
ALTER TABLE SCore.LanguageLabelTranslations
  DROP CONSTRAINT IF EXISTS FK_LanguageLabelTranslations_DataObjects
ALTER TABLE SCore.LanguageLabelTranslations
  DROP CONSTRAINT IF EXISTS FK_LanguageLabelTranslations_LanguageLabels
ALTER TABLE SCore.LanguageLabelTranslations
  DROP CONSTRAINT IF EXISTS FK_LanguageLabelTranslations_Languages
ALTER TABLE SCore.LanguageLabelTranslations
  DROP CONSTRAINT IF EXISTS FK_LanguageLabelTranslations_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridViewColumnDefinitions]
--
ALTER TABLE SUserInterface.GridViewColumnDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewColumnDefinition_GridViewDefinition
ALTER TABLE SUserInterface.GridViewColumnDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewColumnDefinitions_DataObjects
ALTER TABLE SUserInterface.GridViewColumnDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewColumnDefinitions_LanguageLabelId
ALTER TABLE SUserInterface.GridViewColumnDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewColumnDefinitions_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridViewDefinitions]
--
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinition_GridDefinition
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_DataObjects
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_DrawerIconId
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_EntityTypes
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_LanguageLabelId
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_MetricTypes
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityPropertyActions]
--
ALTER TABLE SCore.EntityPropertyActions
  DROP CONSTRAINT IF EXISTS FK_EntityPropertyActions_EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityPropertyDependants]
--
ALTER TABLE SCore.EntityPropertyDependants
  DROP CONSTRAINT IF EXISTS FK_EntityPropertyDependants_EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[MergeDocumentItemIncludes]
--
ALTER TABLE SCore.MergeDocumentItemIncludes
  DROP CONSTRAINT IF EXISTS FK_MergeDocumentItemIncludes_EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[RecordHistory]
--
ALTER TABLE SCore.RecordHistory
  DROP CONSTRAINT IF EXISTS FK_RecordHistory_EntityPropertyID
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[SynchronisationErrors]
--
ALTER TABLE SCore.SynchronisationErrors
  DROP CONSTRAINT IF EXISTS FK_SychronisationErrors_EntityPropertyID
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[ActionMenuItems]
--
ALTER TABLE SUserInterface.ActionMenuItems
  DROP CONSTRAINT IF EXISTS FK_ActionMenuItems_EntityQueries
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridViewActions]
--
ALTER TABLE SUserInterface.GridViewActions
  DROP CONSTRAINT IF EXISTS FK_GridViewActions_EntityQueries
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridViewWidgetQueries]
--
ALTER TABLE SUserInterface.GridViewWidgetQueries
  DROP CONSTRAINT IF EXISTS FK_GridViewWidgetQueries_EntityQueries
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Updating data of table [SCore].[EntityProperties]
--
UPDATE SCore.EntityProperties SET IsReadOnly = 1 WHERE ID = 100
UPDATE SCore.EntityProperties SET IsCompulsory = 1 WHERE ID = 2167
UPDATE SCore.EntityProperties SET IsCompulsory = 1 WHERE ID = 2168
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Updating data of table [SCore].[EntityQueries]
--
UPDATE SCore.EntityQueries SET Statement = N'SELECT * FROM [SJob].[tvf_Jobs_DataPills] ( @Guid, @AppFormReceived, @ClientAppointmentReceived, @ClientAccountGuid, @AgentAccountGuid, @FinanceAccountGuid, @JobCompleted, @JobCancelled, @JobDormant, @JobStarted, @OrganisationalUnitGuid, @IsNDA, @JobTypeGuid, @CannotBeInvoiced, @CannotBeInvoicedReason, @ContractGuid, @AgentContractGuid, @ProjectGuid) root_hobt' WHERE ID = 38
EXEC(N'UPDATE SCore.EntityQueries SET Statement = N''SELECT 
	[62A7CA41-57FE-4541-9B7B-64C2BECBD403].Guid AS AgentAccountContactId,
	[C6D3628B-9EF6-46E7-A04B-455D7256E180].Guid AS AgentAccountId,
	[518A2AAD-697B-4134-B39D-20C20B5FCD92].Guid AS AgentAddressId,
	root_hobt.AgentAddressLine1,
	root_hobt.AgentAddressLine2,
	root_hobt.AgentAddressLine3,
	root_hobt.AgentAddressNameNumber,
	root_hobt.AgentAddressPostCode,
	[609B9A6E-F1BE-4A80-BFA8-A66F28E3F29A].Guid AS AgentContactDetailType,
	root_hobt.AgentContactDetailTypeName,
	root_hobt.AgentContactDetailTypeValue,
	root_hobt.AgentContactDisplayName,
	[9B125B55-B220-4023-AA54-BABCDF6AFD1B].Guid AS AgentCountryId,
	[7EA7CAB9-F5BC-4B00-AE06-276E3B772910].Guid AS AgentCountyId,
	root_hobt.AgentName,
	root_hobt.AgentTown,
	root_hobt.ChaseDate1,
	root_hobt.ChaseDate2,
	[CCDDA156-B2D7-4F37-AA9E-1CB98F3C11FD].Guid AS ClientAccountContactId,
	[C1AFB8A2-4596-4C64-8267-7F49B9BE04D6].Guid AS ClientAccountId,
	[3611CED8-53C2-4FA8-9ACC-F508149BC716].Guid AS ClientAddressCountryId,
	[A0DB71C1-2E2B-4559-95E4-9CEBF2F01BA5].Guid AS ClientAddressCountyId,
	[8D6A7C6A-9D55-4C03-82F1-75B6BB5BB3CC].Guid AS ClientAddressId,
	root_hobt.ClientAddressLine1,
	root_hobt.ClientAddressLine2,
	root_hobt.ClientAddressLine3,
	root_hobt.ClientAddressNameNumber,
	root_hobt.ClientAddressPostCode,
	root_hobt.ClientAddressTown,
	[C70D2DDB-45EB-4292-B1E9-2F7F97171CA8].Guid AS ClientContactDetailType,
	root_hobt.ClientContactDetailTypeName,
	root_hobt.ClientContactDetailTypeValue,
	root_hobt.ClientContactDisplayName,
	root_hobt.ClientName,
	root_hobt.ConstructionStageMonths,
	[2B074135-3D54-49A9-ACDE-C82FDB5F9067].Guid AS CreatedByUserId,
	[D020A007-8E39-450B-8575-69D76529659A].Guid AS CurrentProjectRibaStageID,
	root_hobt.Date,
	root_hobt.DeadDate,
	root_hobt.DeclinedToQuoteDate,
	root_hobt.DeclinedToQuoteReason,
	root_hobt.DescriptionOfWorks,
	[DE5A2964-7F7D-4194-962C-11F3FA18DB55].Guid AS EnquirySourceId,
	root_hobt.EnterNewAgentDetails,
	root_hobt.EnterNewClientDetails,
	root_hobt.EnterNewFinanceDetails,
	root_hobt.EnterNewStructureDetails,
	root_hobt.ExpectedProcurementRoute,
	root_hobt.ExternalReference,
	[B7C58113-E763-4B52-82D5-21501514AF8C].Guid AS FinanceAccountId,
	root_hobt.FinanceAccountName,
	[BC7CF205-B05B-41AC-B0CC-E23AEDC459D8].Guid AS FinanceAddressId,
	root_hobt.FinanceAddressLine1,
	root_hobt.FinanceAddressLine2,
	root_hobt.FinanceAddressLine3,
	root_hobt.FinanceAddressNameNumber,
	[302CDB8A-058A-4BEB-9B64-2FC2EACF10D9].Guid AS FinanceContactDetailType,
	root_hobt.FinanceContactDetailTypeName,
	root_hobt.FinanceContactDetailTypeValue,
	root_hobt.FinanceContactDisplayName,
	[02B19759-9D35-447C-9AE2-3C7B9027FEB1].Guid AS FinanceContactId,
	[70FEA0EA-C279-484C-931D-2D23F42D01C3].Guid AS FinanceCountyId,
	root_hobt.FinancePostCode,
	root_hobt.FinanceTown,
	root_hobt.Guid,
	root_hobt.ID,
	root_hobt.IsClientFinanceAccount,
	root_hobt.IsReadyForQuoteReview,
	CASE WHEN [9066A2DA-692E-4EFD-A2F0-FF124E2F366E].IsSubjectToNDA = 1 THEN [9066A2DA-692E-4EFD-A2F0-FF124E2F366E].IsSubjectToNDA ELSE root_hobt.IsSubjectToNDA END AS IsSubjectToNDA,
	--root_hobt.IsSubjectToNDA,
	root_hobt.KeyDates,
	root_hobt.Notes,
	root_hobt.Number,
	[1C4B6562-A512-4FC9-85EE-F6A2193EBECE].Guid AS OrganisationalUnitID,
	root_hobt.PreConstructionStageMonths,
	[9066A2DA-692E-4EFD-A2F0-FF124E2F366E].Guid AS ProjectId,
	root_hobt.PropertyAddressLine1,
	root_hobt.PropertyAddressLine2,
	root_hobt.PropertyAddressLine3,
	[C1B43942-F1B0-42DD-8AB7-E1D2C02DFA1B].Guid AS PropertyCountryId,
	[EF3E7956-4ECB-49B0-B930-8DB68D545FFB].Guid AS PropertyCountyId,
	[FE002E4D-3B56-499F-93DA-5D43259CBC76].Guid AS PropertyId,
	root_hobt.PropertyNameNumber,
	root_hobt.PropertyPostCode,
	root_hobt.PropertyTown,
	root_hobt.ProposalLetter,
	root_hobt.QuotingDeadlineDate,
	root_hobt.RibaStage0Months,
	root_hobt.RibaStage1Months,
	root_hobt.RibaStage2Months,
	root_hobt.RibaStage3Months,
	root_hobt.RibaStage4Months,
	root_hobt.RibaStage5Months,
	root_hobt.RibaStage6Months,'
+ N'
	root_hobt.RibaStage7Months,
	root_hobt.RowStatus,
	root_hobt.RowVersion,
	root_hobt.SendInfoToAgent,
	root_hobt.SendInfoToClient,
	[9264744B-5F58-461B-953B-0C16D80B8FC7].Guid AS SignatoryIdentityId,
	root_hobt.ValueOfWork,
	ClientContract.Guid AS ContractID,
	AgentContract.Guid AS AgentContractID
FROM SSop.Enquiries AS root_hobt 
JOIN SCrm.Accounts AS [C6D3628B-9EF6-46E7-A04B-455D7256E180] ON ([C6D3628B-9EF6-46E7-A04B-455D7256E180].ID = root_hobt.AgentAccountId) 
 JOIN SCrm.AccountAddresses AS [518A2AAD-697B-4134-B39D-20C20B5FCD92] ON ([518A2AAD-697B-4134-B39D-20C20B5FCD92].ID = root_hobt.AgentAddressId) 
 JOIN SCrm.Countries AS [9B125B55-B220-4023-AA54-BABCDF6AFD1B] ON ([9B125B55-B220-4023-AA54-BABCDF6AFD1B].ID = root_hobt.AgentCountryId) 
 JOIN SCrm.Counties AS [7EA7CAB9-F5BC-4B00-AE06-276E3B772910] ON ([7EA7CAB9-F5BC-4B00-AE06-276E3B772910].ID = root_hobt.AgentCountyId) 
 JOIN SCrm.Accounts AS [C1AFB8A2-4596-4C64-8267-7F49B9BE04D6] ON ([C1AFB8A2-4596-4C64-8267-7F49B9BE04D6].ID = root_hobt.ClientAccountId) 
 JOIN SCrm.Countries AS [3611CED8-53C2-4FA8-9ACC-F508149BC716] ON ([3611CED8-53C2-4FA8-9ACC-F508149BC716].ID = root_hobt.ClientAddressCountryId) 
 JOIN SCrm.Counties AS [A0DB71C1-2E2B-4559-95E4-9CEBF2F01BA5] ON ([A0DB71C1-2E2B-4559-95E4-9CEBF2F01BA5].ID = root_hobt.ClientAddressCountyId) 
 JOIN SCrm.AccountAddresses AS [8D6A7C6A-9D55-4C03-82F1-75B6BB5BB3CC] ON ([8D6A7C6A-9D55-4C03-82F1-75B6BB5BB3CC].ID = root_hobt.ClientAddressId) 
 JOIN SCore.Identities AS [2B074135-3D54-49A9-ACDE-C82FDB5F9067] ON ([2B074135-3D54-49A9-ACDE-C82FDB5F9067].ID = root_hobt.CreatedByUserId) 
 JOIN SJob.RibaStages AS [D020A007-8E39-450B-8575-69D76529659A] ON ([D020A007-8E39-450B-8575-69D76529659A].ID = root_hobt.CurrentProjectRibaStageID) 
 JOIN SCore.OrganisationalUnits AS [1C4B6562-A512-4FC9-85EE-F6A2193EBECE] ON ([1C4B6562-A512-4FC9-85EE-F6A2193EBECE].ID = root_hobt.OrganisationalUnitID) 
 JOIN SCrm.Countries AS [C1B43942-F1B0-42DD-8AB7-E1D2C02DFA1B] ON ([C1B43942-F1B0-42DD-8AB7-E1D2C02DFA1B].ID = root_hobt.PropertyCountryId) 
 JOIN SCrm.Counties AS [EF3E7956-4ECB-49B0-B930-8DB68D545FFB] ON ([EF3E7956-4ECB-49B0-B930-8DB68D545FFB].ID = root_hobt.PropertyCountyId) 
 JOIN SJob.Assets AS [FE002E4D-3B56-499F-93DA-5D43259CBC76] ON ([FE002E4D-3B56-499F-93DA-5D43259CBC76].ID = root_hobt.PropertyId) 
 JOIN SSop.QuoteSources AS [DE5A2964-7F7D-4194-962C-11F3FA18DB55] ON ([DE5A2964-7F7D-4194-962C-11F3FA18DB55].ID = root_hobt.EnquirySourceId) 
 JOIN SCrm.AccountContacts AS [62A7CA41-57FE-4541-9B7B-64C2BECBD403] ON ([62A7CA41-57FE-4541-9B7B-64C2BECBD403].ID = root_hobt.AgentAccountContactId) 
 JOIN SCrm.AccountContacts AS [CCDDA156-B2D7-4F37-AA9E-1CB98F3C11FD] ON ([CCDDA156-B2D7-4F37-AA9E-1CB98F3C11FD].ID = root_hobt.ClientAccountContactId) 
 JOIN SSop.Projects AS [9066A2DA-692E-4EFD-A2F0-FF124E2F366E] ON ([9066A2DA-692E-4EFD-A2F0-FF124E2F366E].ID = root_hobt.ProjectId) 
 JOIN SCrm.Accounts AS [B7C58113-E763-4B52-82D5-21501514AF8C] ON ([B7C58113-E763-4B52-82D5-21501514AF8C].ID = root_hobt.FinanceAccountId) 
 JOIN SCrm.AccountAddresses AS [BC7CF205-B05B-41AC-B0CC-E23AEDC459D8] ON ([BC7CF205-B05B-41AC-B0CC-E23AEDC459D8].ID = root_hobt.FinanceAddressId) 
 JOIN SCrm.AccountContacts AS [02B19759-9D35-447C-9AE2-3C7B9027FEB1] ON ([02B19759-9D35-447C-9AE2-3C7B9027FEB1].ID = root_hobt.FinanceContactId) 
 JOIN SCrm.Counties AS [70FEA0EA-C279-484C-931D-2D23F42D01C3] ON ([70FEA0EA-C279-484C-931D-2D23F42D01C3].ID = root_hobt.FinanceCountyId) 
 JOIN SCore.Identities AS [9264744B-5F58-461B-953B-0C16D80B8FC7] ON ([9264744B-5F58-461B-953B-0C16D80B8FC7].ID = root_hobt.SignatoryIdentityId) 
 JOIN SCrm.ContactDetailTypes AS [C70D2DDB-45EB-4292-B1E9-2F7F97171CA8] ON ([C70D2DDB-45EB-4292-B1E9-2F7F97171CA8].ID = root_hobt.ClientContactDetailType) 
 JOIN SCrm.ContactDetailTypes AS [609B9A6E-F1BE-4A80-BFA8-A66F28E3F29A] ON ([609B9A6E-F1BE-4A80-BFA8-A66F28E3F29A].ID = root_hobt.AgentContactDetailType) 
 JOIN SCrm.ContactDetailTypes AS [302CDB8A-058A-4BEB-9B64-2FC2EACF10D9'
+ N'] ON ([302CDB8A-058A-4BEB-9B64-2FC2EACF10D9].ID = root_hobt.FinanceContactDetailType) 
 JOIN SSop.Contracts AS ClientContract ON (ClientContract.ID = root_hobt.ContractID)
 JOIN SSop.Contracts AS AgentContract ON  (AgentContract.ID = root_hobt.AgentContractID)
'' WHERE ID = 159')
EXEC(N'UPDATE SCore.EntityQueries SET Statement = N''EXEC [SSop].[EnquiriesUpsert]  
	@OrganisationalUnitGuid = @OrganisationalUnitGuid, 
	@Date = @Date, 
	@CreatedByUserGuid = @CreatedByUserGuid, 
	@PropertyGuid = @PropertyGuid, 
	@PropertyNameNumber = @PropertyNameNumber, 
	@PropertyAddressLine1 = @PropertyAddressLine1, 
	@PropertyAddressLine2 = @PropertyAddressLine2, 
	@PropertyAddressLine3 = @PropertyAddressLine3, 
	@PropertyCountyGuid = @PropertyCountyGuid, 
	@PropertyPostCode = @PropertyPostCode, 
	@PropertyCountryGuid = @PropertyCountryGuid, 
	@ClientAccountGuid = @ClientAccountGuid, 
	@ClientAddressGuid = @ClientAddressGuid, 
	@ClientAccountContactGuid = @ClientAccountContactGuid, 
	@ClientName = @ClientName, 
	@ClientAddressNameNumber = @ClientAddressNameNumber, 
	@ClientAddressLine1 = @ClientAddressLine1, 
	@ClientAddressLine2 = @ClientAddressLine2, 
	@ClientAddressLine3 = @ClientAddressLine3, 
	@ClientAddressCountyGuid = @ClientAddressCountyGuid, 
	@ClientAddressPostCode = @ClientAddressPostCode, 
	@ClientAddressCountryGuid = @ClientAddressCountryGuid, 
	@AgentAccountGuid = @AgentAccountGuid, 
	@AgentAddressGuid = @AgentAddressGuid, 
	@AgentAccountContactGuid = @AgentAccountContactGuid, 
	@AgentName = @AgentName, 
	@AgentAddressNameNumber = @AgentAddressNameNumber, 
	@AgentAddressLine1 = @AgentAddressLine1, 
	@AgentAddressLine2 = @AgentAddressLine2, 
	@AgentAddressLine3 = @AgentAddressLine3, 
	@AgentAddressCountyGuid = @AgentAddressCountyGuid, 
	@AgentAddressPostCode = @AgentAddressPostCode, 
	@AgentAddressCountryGuid = @AgentAddressCountryGuid, 
	@DescriptionOfWorks = @DescriptionOfWorks, 
	@ValueOfWork = @ValueOfWork, 
	@CurrentProjectRobaStageGuid = @CurrentProjectRobaStageGuid, 
	@RibaStage0Months = @RibaStage0Months, 
	@RibaStage1Months = @RibaStage1Months, 
	@RibaStage2Months = @RibaStage2Months, 
	@RibaStage3Months = @RibaStage3Months, 
	@RibaStage4Months = @RibaStage4Months, 
	@RibaStage5Months = @RibaStage5Months, 
	@RibaStage6Months = @RibaStage6Months, 
	@RibaStage7Months = @RibaStage7Months, 
	@PreConstructionStageMonths = @PreConstructionStageMonths, 
	@ConstructionStageMonths = @ConstructionStageMonths, 
	@SendInfoToClient = @SendInfoToClient, 
	@SendInfoToAgent = @SendInfoToAgent, 
	@KeyDates = @KeyDates, 
	@ExpectedProcurementRoute = @ExpectedProcurementRoute, 
	@Notes = @Notes, 
	@EnquirySourceGuid = @EnquirySourceGuid, 
	@IsReadyForQuoteReview = @IsReadyForQuoteReview, 
	@QuotingDeadlineDate = @QuotingDeadlineDate, 
	@DeclinedToQuoteDate = @DeclinedToQuoteDate, 
	@DeclinedToQuoteReason = @DeclinedToQuoteReason, 
	@ExternalReference = @ExternalReference, 
	@ProjectGuid = @ProjectGuid, 
	@IsSubjectToNDA = @IsSubjectToNDA, 
	@DeadDate = @DeadDate, 
	@ChaseDate1 = @ChaseDate1, 
	@ChaseDate2 = @ChaseDate2, 
	@FinanceAccountGuid = @FinanceAccountGuid, 
	@FinanceAddressGuid = @FinanceAddressGuid, 
	@FinanceContactGuid = @FinanceContactGuid, 
	@FinanceAccountName = @FinanceAccountName, 
	@FinanceAddressNameNumber = @FinanceAddressNameNumber, 
	@FinanceAddressLine1 = @FinanceAddressLine1, 
	@FinanceAddressLine2 = @FinanceAddressLine2, 
	@FinanceAddressLine3 = @FinanceAddressLine3, 
	@FinanceCountyGuid = @FinanceCountyGuid, 
	@FinancePostCode = @FinancePostCode, 
	@EnterNewClientDetails = @EnterNewClientDetails, 
	@EnterNewAgentDetails = @EnterNewAgentDetails, 
	@EnterNewFinanceDetails = @EnterNewFinanceDetails, 
	@EnterNewStructureDetails = @EnterNewStructureDetails, 
	@IsClientFinanceAccount = @IsClientFinanceAccount, 
	@SignatoryIdentityGuid = @SignatoryIdentityGuid, 
	@ProposalLetter = @ProposalLetter, 
	@Guid = @Guid,
        @ClientContactDisplayName = @ClientContactDisplayName,
        @ClientContactDetailTypeGuid = @ClientContactDetailTypeGuid,
        @ClientContactDetailTypeName = @ClientContactDetailTypeName,
        @ClientContactDetailTypeValue = @ClientContactDetailTypeValue,
        @AgentContactDisplayName = @AgentContactDisplayName,
        @AgentContactDetailTypeGuid= @AgentContactDetailTypeGuid'
+ N',
        @AgentContactDetailTypeName = @AgentContactDetailTypeName,
        @AgentContactDetailTypeValue = @AgentContactDetailTypeValue,
        @FinanceContactDisplayName = @FinanceContactDisplayName,
        @FinanceContactDetailTypeGuid = @FinanceContactDetailTypeGuid,
        @FinanceContactDetailTypeName = @FinanceContactDetailTypeName,
        @FinanceContactDetailTypeValue = @FinanceContactDetailTypeValue,
        @ContractGuid = @ContractGuid,
        @AgentContractGuid = @AgentContractGuid
        
'' WHERE ID = 160')

--
-- Inserting data into table [SCore].[EntityQueries]
--
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
SET IDENTITY_INSERT SCore.EntityQueries ON
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
INSERT SCore.EntityQueries(ID, RowStatus, Guid, Name, Statement, EntityTypeID, EntityHoBTID, IsDefaultCreate, IsDefaultRead, IsDefaultUpdate, IsDefaultDelete, IsScalarExecute, IsDefaultValidation, UsesProcessGuid, IsDefaultDataPills, IsProgressData, IsMergeDocumentQuery, SchemaName, ObjectName, IsManualStatement) VALUES (332, 1, '3138ca92-58f4-4f6f-aeb5-22e20499668a', N'Account Merge Batch Delete', N'EXEC [SCrm].[AccountMergeBatchDelete]  
	@Guid = @Guid', 93, 85, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, N'SCrm', N'AccountMergeBatchDelete', 0)
INSERT SCore.EntityQueries(ID, RowStatus, Guid, Name, Statement, EntityTypeID, EntityHoBTID, IsDefaultCreate, IsDefaultRead, IsDefaultUpdate, IsDefaultDelete, IsScalarExecute, IsDefaultValidation, UsesProcessGuid, IsDefaultDataPills, IsProgressData, IsMergeDocumentQuery, SchemaName, ObjectName, IsManualStatement) VALUES (333, 1, 'f5e0de7a-494b-4cb2-ad74-2347fab52f34', N'Job Type Activity Types Delete', N'EXEC [SJob].[JobTypeActivityTypesDelete] @Guid = @Guid', 81, 73, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, N'SJob', N'JobTypeActivityTypes', 1)
GO
SET IDENTITY_INSERT SCore.EntityQueries OFF
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Inserting data into table [SCore].[EntityQueryParameters]
--
SET IDENTITY_INSERT SCore.EntityQueryParameters ON
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
INSERT SCore.EntityQueryParameters(ID, RowStatus, Guid, Name, EntityQueryID, EntityDataTypeID, MappedEntityPropertyID, DefaultValue, IsInput, IsOutput, IsReturnColumn) VALUES (1399, 1, 'b02085c9-fc14-450d-8151-b41089c1b788', N'@Guid', 332, 6, 1187, N'', 1, 0, 0)
INSERT SCore.EntityQueryParameters(ID, RowStatus, Guid, Name, EntityQueryID, EntityDataTypeID, MappedEntityPropertyID, DefaultValue, IsInput, IsOutput, IsReturnColumn) VALUES (1401, 1, '1ee38c04-8036-484a-839f-ec26df4dc9d2', N'@Guid', 333, 6, 942, N'', 1, 0, 0)
INSERT SCore.EntityQueryParameters(ID, RowStatus, Guid, Name, EntityQueryID, EntityDataTypeID, MappedEntityPropertyID, DefaultValue, IsInput, IsOutput, IsReturnColumn) VALUES (1402, 1, '78719204-6cc0-488f-a115-56a290fcadba', N'@ProjectGuid', 38, 6, 1230, N'', 1, 0, 0)
GO
SET IDENTITY_INSERT SCore.EntityQueryParameters OFF
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Updating data of table [SCore].[LanguageLabelTranslations]
--
UPDATE SCore.LanguageLabelTranslations SET Text = N'Is Subject to NDA (From Enquiry)', TextPlural = N'Is Subject to NDA (From Enquiry)' WHERE ID = 611
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Updating data of table [SUserInterface].[GridViewColumnDefinitions]
--
UPDATE SUserInterface.GridViewColumnDefinitions SET Width = N'' WHERE ID = 18
UPDATE SUserInterface.GridViewColumnDefinitions SET Width = N'150px' WHERE ID = 432
UPDATE SUserInterface.GridViewColumnDefinitions SET IsHidden = 0 WHERE ID = 437
UPDATE SUserInterface.GridViewColumnDefinitions SET IsHidden = 1 WHERE ID = 440
UPDATE SUserInterface.GridViewColumnDefinitions SET Width = N'120px' WHERE ID = 459
UPDATE SUserInterface.GridViewColumnDefinitions SET IsHidden = 1 WHERE ID = 974
UPDATE SUserInterface.GridViewColumnDefinitions SET Width = N'100px' WHERE ID = 1020

--
-- Inserting data into table [SUserInterface].[GridViewColumnDefinitions]
--
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
SET IDENTITY_INSERT SUserInterface.GridViewColumnDefinitions ON
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
INSERT SUserInterface.GridViewColumnDefinitions(ID, RowStatus, Guid, Name, ColumnOrder, GridViewDefinitionId, IsPrimaryKey, IsHidden, IsFiltered, IsCombo, IsLongitude, IsLatitude, DisplayFormat, Width, LanguageLabelId, TopHeaderCategory, TopHeaderCategoryOrder) VALUES (1110, 1, 'f9f4953d-3401-4cf3-9498-4adc1e271a1f', N'Disciplines', 7, 101, 0, 0, 0, 0, 0, 0, N'', N'', 2557, N'', 0)
INSERT SUserInterface.GridViewColumnDefinitions(ID, RowStatus, Guid, Name, ColumnOrder, GridViewDefinitionId, IsPrimaryKey, IsHidden, IsFiltered, IsCombo, IsLongitude, IsLatitude, DisplayFormat, Width, LanguageLabelId, TopHeaderCategory, TopHeaderCategoryOrder) VALUES (1111, 1, '52841fc5-32fd-40fc-9e3c-909ae8a6034f', N'OrgUnit', 8, 101, 0, 0, 1, 0, 0, 0, N'', N'', 2808, N'', 0)
INSERT SUserInterface.GridViewColumnDefinitions(ID, RowStatus, Guid, Name, ColumnOrder, GridViewDefinitionId, IsPrimaryKey, IsHidden, IsFiltered, IsCombo, IsLongitude, IsLatitude, DisplayFormat, Width, LanguageLabelId, TopHeaderCategory, TopHeaderCategoryOrder) VALUES (1112, 1, '5a9c3a55-fe1d-452c-8119-80d404fbac4b', N'Date', 9, 101, 0, 0, 0, 0, 0, 0, N'', N'', 2824, N'', 0)
GO
SET IDENTITY_INSERT SUserInterface.GridViewColumnDefinitions OFF
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Reseed identity on SUserInterface.GridViewColumnDefinitions
--
DBCC CHECKIDENT('SUserInterface.GridViewColumnDefinitions', RESEED, 1)
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Updating data of table [SUserInterface].[GridViewDefinitions]
--
UPDATE SUserInterface.GridViewDefinitions SET DefaultSortColumnName = N'ID' WHERE ID = 54
UPDATE SUserInterface.GridViewDefinitions SET SqlQuery = N'SELECT	ID,
		RowStatus,
		RowVersion,
		Guid,
		Number,
		ExternalReference,
		DescriptionOfWorks,
		Account,
                ClientAgentAccount,
                Property,
                EnquiryStatus,
                Disciplines,
                Date,
                OrgUnit
FROM	SSop.tvf_EnquiriesForQuoteReview([[UserId]]) root_hobt' WHERE ID = 101
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Reseed identity on SUserInterface.GridViewDefinitions
--
DBCC CHECKIDENT('SUserInterface.GridViewDefinitions', RESEED, 1)
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityProperties]
--
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_DropDownListDefinitions FOREIGN KEY (DropDownListDefinitionID) REFERENCES SUserInterface.DropDownListDefinitions(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_EntityDataTypes FOREIGN KEY (EntityDataTypeID) REFERENCES SCore.EntityDataTypes(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_EntityHoBTs FOREIGN KEY (EntityHoBTID) REFERENCES SCore.EntityHobts(ID) ON DELETE CASCADE ON UPDATE NO ACTION
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_EntityPropertyGroupID FOREIGN KEY (EntityPropertyGroupID) REFERENCES SCore.EntityPropertyGroups(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_LanguageLabels FOREIGN KEY (LanguageLabelID) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityQueries]
--
ALTER TABLE SCore.EntityQueries WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueries_DataObjects FOREIGN KEY (Guid) REFERENCES SCore.DataObjects(Guid) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityQueries WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueries_EntityHoBTs FOREIGN KEY (EntityHoBTID) REFERENCES SCore.EntityHobts(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityQueries WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueries_EntityTypes FOREIGN KEY (EntityTypeID) REFERENCES SCore.EntityTypes(ID) ON DELETE CASCADE ON UPDATE NO ACTION
ALTER TABLE SCore.EntityQueries WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueries_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityQueryParameters]
--
ALTER TABLE SCore.EntityQueryParameters WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueryParameters_DataObjects FOREIGN KEY (Guid) REFERENCES SCore.DataObjects(Guid) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityQueryParameters WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueryParameters_EntityDataTypes FOREIGN KEY (EntityDataTypeID) REFERENCES SCore.EntityDataTypes(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityQueryParameters WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueryParameters_EntityProperties FOREIGN KEY (MappedEntityPropertyID) REFERENCES SCore.EntityProperties(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityQueryParameters WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueryParameters_EntityQueries FOREIGN KEY (EntityQueryID) REFERENCES SCore.EntityQueries(ID) ON DELETE CASCADE ON UPDATE NO ACTION
ALTER TABLE SCore.EntityQueryParameters WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueryParameters_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[LanguageLabelTranslations]
--
ALTER TABLE SCore.LanguageLabelTranslations WITH NOCHECK
  ADD CONSTRAINT FK_LanguageLabelTranslations_DataObjects FOREIGN KEY (Guid) REFERENCES SCore.DataObjects(Guid) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.LanguageLabelTranslations WITH NOCHECK
  ADD CONSTRAINT FK_LanguageLabelTranslations_LanguageLabels FOREIGN KEY (LanguageLabelID) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.LanguageLabelTranslations WITH NOCHECK
  ADD CONSTRAINT FK_LanguageLabelTranslations_Languages FOREIGN KEY (LanguageID) REFERENCES SCore.Languages(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.LanguageLabelTranslations WITH NOCHECK
  ADD CONSTRAINT FK_LanguageLabelTranslations_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridViewColumnDefinitions]
--
ALTER TABLE SUserInterface.GridViewColumnDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewColumnDefinition_GridViewDefinition FOREIGN KEY (GridViewDefinitionId) REFERENCES SUserInterface.GridViewDefinitions(ID) ON DELETE CASCADE ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewColumnDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewColumnDefinitions_DataObjects FOREIGN KEY (Guid) REFERENCES SCore.DataObjects(Guid) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewColumnDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewColumnDefinitions_LanguageLabelId FOREIGN KEY (LanguageLabelId) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewColumnDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewColumnDefinitions_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridViewDefinitions]
--
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinition_GridDefinition FOREIGN KEY (GridDefinitionId) REFERENCES SUserInterface.GridDefinitions(ID) ON DELETE CASCADE ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_DataObjects FOREIGN KEY (Guid) REFERENCES SCore.DataObjects(Guid) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_DrawerIconId FOREIGN KEY (DrawerIconId) REFERENCES SUserInterface.Icons(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_EntityTypes FOREIGN KEY (EntityTypeID) REFERENCES SCore.EntityTypes(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_LanguageLabelId FOREIGN KEY (LanguageLabelId) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_MetricTypes FOREIGN KEY (MetricTypeID) REFERENCES SUserInterface.MetricTypes(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityPropertyActions]
--
ALTER TABLE SCore.EntityPropertyActions WITH NOCHECK
  ADD CONSTRAINT FK_EntityPropertyActions_EntityProperties FOREIGN KEY (EntityPropertyID) REFERENCES SCore.EntityProperties(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityPropertyDependants]
--
ALTER TABLE SCore.EntityPropertyDependants WITH NOCHECK
  ADD CONSTRAINT FK_EntityPropertyDependants_EntityProperties FOREIGN KEY (ParentEntityPropertyID) REFERENCES SCore.EntityProperties(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[MergeDocumentItemIncludes]
--
ALTER TABLE SCore.MergeDocumentItemIncludes WITH NOCHECK
  ADD CONSTRAINT FK_MergeDocumentItemIncludes_EntityProperties FOREIGN KEY (SourceDocumentEntityPropertyId) REFERENCES SCore.EntityProperties(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[RecordHistory]
--
ALTER TABLE SCore.RecordHistory WITH NOCHECK
  ADD CONSTRAINT FK_RecordHistory_EntityPropertyID FOREIGN KEY (EntityPropertyID) REFERENCES SCore.EntityProperties(ID) ON DELETE CASCADE ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[SynchronisationErrors]
--
ALTER TABLE SCore.SynchronisationErrors WITH NOCHECK
  ADD CONSTRAINT FK_SychronisationErrors_EntityPropertyID FOREIGN KEY (EntityPropertyID) REFERENCES SCore.EntityProperties(ID) ON DELETE CASCADE ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[ActionMenuItems]
--
ALTER TABLE SUserInterface.ActionMenuItems WITH NOCHECK
  ADD CONSTRAINT FK_ActionMenuItems_EntityQueries FOREIGN KEY (EntityQueryId) REFERENCES SCore.EntityQueries(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridViewActions]
--
ALTER TABLE SUserInterface.GridViewActions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewActions_EntityQueries FOREIGN KEY (EntityQueryId) REFERENCES SCore.EntityQueries(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridViewWidgetQueries]
--
ALTER TABLE SUserInterface.GridViewWidgetQueries WITH NOCHECK
  ADD CONSTRAINT FK_GridViewWidgetQueries_EntityQueries FOREIGN KEY (EntityQueryId) REFERENCES SCore.EntityQueries(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Enabling DML triggers for [SCore].[EntityProperties]
--
GO
ENABLE TRIGGER ALL ON SCore.EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Enabling DML triggers for [SCore].[EntityQueries]
--
GO
ENABLE TRIGGER ALL ON SCore.EntityQueries
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Enabling DML triggers for [SCore].[EntityQueryParameters]
--
GO
ENABLE TRIGGER ALL ON SCore.EntityQueryParameters
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Enabling DML triggers for [SCore].[LanguageLabelTranslations]
--
GO
ENABLE TRIGGER ALL ON SCore.LanguageLabelTranslations
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Commit Transaction
--
IF @@TRANCOUNT>0 COMMIT TRANSACTION
SET NOEXEC OFF
GO