SET LANGUAGE 'British English'
SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT, XACT_ABORT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS OFF
GO

BEGIN TRAN 


EXEC sys.sp_set_session_context @key = 'S_disable_triggers',
								@value = 1;

UPDATE	a
SET		a.IsSalesLedger = 1,
		a.IsPurchaseLedger = 0
--SELECT	*
FROM	SCrm.Accounts AS a
WHERE	(a.IsPurchaseLedger = 1)


IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Commit Transaction
--
IF @@TRANCOUNT>0 COMMIT TRANSACTION
SET NOEXEC OFF
GO