-- 
-- Script was generated by Devart dbForge Schema Compare for SQL Server, Version 7.1.45.0
-- Product Home Page: https://www.devart.com/dbforge/sql/schemacompare
-- Script date 01/05/2025 10:01:16
-- Source server version: 16.00.1000
-- Source connection string: Data Source=soc-sqldevbre01.esgl.co.uk\General;Integrated Security=True;User ID=ESGL\Richard.Brindley
-- Target server version: 16.00.1000
-- Target connection string: Data Source=soc-sqldevbre01.esgl.co.uk\General;Integrated Security=True;User ID=ESGL\Richard.Brindley
-- Run this script against Concursus_Test to synchronize it with Concursus_Dev
-- Please backup your target database before running this script
-- 

SET CONCAT_NULL_YIELDS_NULL, ANSI_NULLS, ANSI_PADDING, QUOTED_IDENTIFIER, ANSI_WARNINGS, ARITHABORT, XACT_ABORT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS OFF
GO

--
-- Start Transaction
--
BEGIN TRANSACTION
GO

--
-- Drop foreign key [FK_EntityPropertyActions_EntityProperties] on table [SCore].[EntityPropertyActions]
--
ALTER TABLE [SCore].[EntityPropertyActions]
  DROP CONSTRAINT [FK_EntityPropertyActions_EntityProperties]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_EntityPropertyDependants_EntityProperties] on table [SCore].[EntityPropertyDependants]
--
ALTER TABLE [SCore].[EntityPropertyDependants]
  DROP CONSTRAINT [FK_EntityPropertyDependants_EntityProperties]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_EntityPropertyDependants_EntityProperties1] on table [SCore].[EntityPropertyDependants]
--
ALTER TABLE [SCore].[EntityPropertyDependants]
  DROP CONSTRAINT [FK_EntityPropertyDependants_EntityProperties1]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_EntityQueryParameters_EntityProperties] on table [SCore].[EntityQueryParameters]
--
ALTER TABLE [SCore].[EntityQueryParameters]
  DROP CONSTRAINT [FK_EntityQueryParameters_EntityProperties]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_RecordHistory_EntityPropertyID] on table [SCore].[RecordHistory]
--
ALTER TABLE [SCore].[RecordHistory]
  DROP CONSTRAINT [FK_RecordHistory_EntityPropertyID]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_SychronisationErrors_EntityPropertyID] on table [SCore].[SynchronisationErrors]
--
ALTER TABLE [SCore].[SynchronisationErrors]
  DROP CONSTRAINT [FK_SychronisationErrors_EntityPropertyID]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_MergeDocumentItemIncludes_EntityProperties] on table [SCore].[MergeDocumentItemIncludes]
--
ALTER TABLE [SCore].[MergeDocumentItemIncludes]
  DROP CONSTRAINT [FK_MergeDocumentItemIncludes_EntityProperties]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop foreign key [FK_MergeDocumentItemIncludes_EntityProperties1] on table [SCore].[MergeDocumentItemIncludes]
--
ALTER TABLE [SCore].[MergeDocumentItemIncludes]
  DROP CONSTRAINT [FK_MergeDocumentItemIncludes_EntityProperties1]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create column [ShowOnMobile] on table [SCore].[EntityPropertyGroups]
--
ALTER TABLE [SCore].[EntityPropertyGroups]
  ADD [ShowOnMobile] [bit] NOT NULL CONSTRAINT [DF_EntityPropertyGroups_ShowOnMobile] DEFAULT (0)
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create column [IsCollapsable] on table [SCore].[EntityPropertyGroups]
--
ALTER TABLE [SCore].[EntityPropertyGroups]
  ADD [IsCollapsable] [bit] NOT NULL CONSTRAINT [DF_EntityPropertyGroups_IsCollapsable] DEFAULT (0)
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create column [IsDefaultCollapsed] on table [SCore].[EntityPropertyGroups]
--
ALTER TABLE [SCore].[EntityPropertyGroups]
  ADD [IsDefaultCollapsed] [bit] NOT NULL CONSTRAINT [DF_EntityPropertyGroups_IsDefaultCollapsed] DEFAULT (0)
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create column [IsDefaultCollapsed_Mobile] on table [SCore].[EntityPropertyGroups]
--
ALTER TABLE [SCore].[EntityPropertyGroups]
  ADD [IsDefaultCollapsed_Mobile] [bit] NOT NULL CONSTRAINT [DF_EntityPropertyGroups_IsDefaultCollapsed_Moble] DEFAULT (0)
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Refresh view [SCore].[EntityPropertiesGroupsForValidationV]
--
EXEC sp_refreshview '[SCore].[EntityPropertiesGroupsForValidationV]'
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Drop primary key [PK_EntityProperties] on table [SCore].[EntityProperties]
--
ALTER TABLE [SCore].[EntityProperties]
  DROP CONSTRAINT [PK_EntityProperties]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create column [ShowOnMobile] on table [SCore].[EntityProperties]
--
ALTER TABLE [SCore].[EntityProperties]
  ADD [ShowOnMobile] [bit] NOT NULL CONSTRAINT [DF_EntityProperties_ShowOnMobile] DEFAULT (0)
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create column [IsAlwaysVisibleInGroup] on table [SCore].[EntityProperties]
--
ALTER TABLE [SCore].[EntityProperties]
  ADD [IsAlwaysVisibleInGroup] [bit] NOT NULL CONSTRAINT [DF_EntityProperties_IsAlwaysVisibleInGroup] DEFAULT (0)
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create column [IsAlwaysVisibleInGroup_Mobile] on table [SCore].[EntityProperties]
--
ALTER TABLE [SCore].[EntityProperties]
  ADD [IsAlwaysVisibleInGroup_Mobile] [bit] NOT NULL CONSTRAINT [DF_EntityProperties_IsAlwaysVisibleInGroup_Mobile] DEFAULT (0)
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create primary key [PK_EntityProperties] on table [SCore].[EntityProperties]
--
ALTER TABLE [SCore].[EntityProperties]
  ADD CONSTRAINT [PK_EntityProperties] PRIMARY KEY CLUSTERED ([ID]) WITH (FILLFACTOR = 80) ON [METADATA]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_EntityPropertyActions_EntityProperties] on table [SCore].[EntityPropertyActions]
--
ALTER TABLE [SCore].[EntityPropertyActions] WITH NOCHECK
  ADD CONSTRAINT [FK_EntityPropertyActions_EntityProperties] FOREIGN KEY ([EntityPropertyID]) REFERENCES [SCore].[EntityProperties] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_EntityPropertyDependants_EntityProperties] on table [SCore].[EntityPropertyDependants]
--
ALTER TABLE [SCore].[EntityPropertyDependants] WITH NOCHECK
  ADD CONSTRAINT [FK_EntityPropertyDependants_EntityProperties] FOREIGN KEY ([ParentEntityPropertyID]) REFERENCES [SCore].[EntityProperties] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_EntityPropertyDependants_EntityProperties1] on table [SCore].[EntityPropertyDependants]
--
ALTER TABLE [SCore].[EntityPropertyDependants] WITH NOCHECK
  ADD CONSTRAINT [FK_EntityPropertyDependants_EntityProperties1] FOREIGN KEY ([DependantPropertyID]) REFERENCES [SCore].[EntityProperties] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_EntityQueryParameters_EntityProperties] on table [SCore].[EntityQueryParameters]
--
ALTER TABLE [SCore].[EntityQueryParameters] WITH NOCHECK
  ADD CONSTRAINT [FK_EntityQueryParameters_EntityProperties] FOREIGN KEY ([MappedEntityPropertyID]) REFERENCES [SCore].[EntityProperties] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_RecordHistory_EntityPropertyID] on table [SCore].[RecordHistory]
--
ALTER TABLE [SCore].[RecordHistory] WITH NOCHECK
  ADD CONSTRAINT [FK_RecordHistory_EntityPropertyID] FOREIGN KEY ([EntityPropertyID]) REFERENCES [SCore].[EntityProperties] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_SychronisationErrors_EntityPropertyID] on table [SCore].[SynchronisationErrors]
--
ALTER TABLE [SCore].[SynchronisationErrors] WITH NOCHECK
  ADD CONSTRAINT [FK_SychronisationErrors_EntityPropertyID] FOREIGN KEY ([EntityPropertyID]) REFERENCES [SCore].[EntityProperties] ([ID]) ON DELETE CASCADE
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_MergeDocumentItemIncludes_EntityProperties] on table [SCore].[MergeDocumentItemIncludes]
--
ALTER TABLE [SCore].[MergeDocumentItemIncludes] WITH NOCHECK
  ADD CONSTRAINT [FK_MergeDocumentItemIncludes_EntityProperties] FOREIGN KEY ([SourceDocumentEntityPropertyId]) REFERENCES [SCore].[EntityProperties] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Create foreign key [FK_MergeDocumentItemIncludes_EntityProperties1] on table [SCore].[MergeDocumentItemIncludes]
--
ALTER TABLE [SCore].[MergeDocumentItemIncludes]
  ADD CONSTRAINT [FK_MergeDocumentItemIncludes_EntityProperties1] FOREIGN KEY ([SourceSharePointItemEntityPropertyId]) REFERENCES [SCore].[EntityProperties] ([ID])
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Refresh view [SCore].[AllEntityProperties]
--
EXEC sp_refreshview '[SCore].[AllEntityProperties]'
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Refresh view [SCore].[EntityPropertiesForValidationV]
--
EXEC sp_refreshview '[SCore].[EntityPropertiesForValidationV]'
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Refresh view [SCore].[EntityPropertiesV]
--
EXEC sp_refreshview '[SCore].[EntityPropertiesV]'
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Refresh view [SCore].[EntityPropertiesWithoutSchemaColumns]
--
EXEC sp_refreshview '[SCore].[EntityPropertiesWithoutSchemaColumns]'
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Refresh view [SCore].[EntityPropertyDependantsV]
--
EXEC sp_refreshview '[SCore].[EntityPropertyDependantsV]'
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
GO

--
-- Commit Transaction
--
IF @@TRANCOUNT>0 COMMIT TRANSACTION
GO

--
-- Set NOEXEC to off
--
SET NOEXEC OFF
GO