--
-- Script was generated by Devart dbForge Data Compare for SQL Server, Version 5.5.3.0
-- Product Home Page: http://www.devart.com/dbforge/sql/datacompare
-- Script date 29/04/2026 16:45:26
-- Source server version: 16.00.1000
-- Source connection string: Data Source=SOC-SQLDEVBRE01\GENERAL;Initial Catalog=CymBuild_Dev;Integrated Security=True;User ID=ESGL\stephen.brett
-- Target server version: 16.00.4175
-- Target connection string: Data Source=SOC-SQLBRE01\SQL2022;Integrated Security=True;User ID=ESGL\stephen.brett
-- Run this script against CymBuild_UAT to synchronize it with Cymbuild_QA
-- Please backup your target database before running this script
--



SET LANGUAGE 'British English'
SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT, XACT_ABORT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS OFF
GO


--
-- Start Transaction
--
PRINT(N'Start Transaction')
GO
BEGIN TRANSACTION

--
-- Disabling DML triggers for [SCore].[EntityProperties]
--
PRINT(N'Disabling DML triggers for [SCore].[EntityProperties]')
GO
DISABLE TRIGGER ALL ON SCore.EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Disabling DML triggers for [SCore].[EntityQueryParameters]
--
PRINT(N'Disabling DML triggers for [SCore].[EntityQueryParameters]')
GO
DISABLE TRIGGER ALL ON SCore.EntityQueryParameters
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Disabling DML triggers for [SCore].[LanguageLabels]
--
PRINT(N'Disabling DML triggers for [SCore].[LanguageLabels]')
GO
DISABLE TRIGGER ALL ON SCore.LanguageLabels
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Disabling DML triggers for [SCore].[LanguageLabelTranslations]
--
PRINT(N'Disabling DML triggers for [SCore].[LanguageLabelTranslations]')
GO
DISABLE TRIGGER ALL ON SCore.LanguageLabelTranslations
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityProperties]
--
PRINT(N'Dropping constraints from [SCore].[EntityProperties]')
GO
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_DropDownListDefinitions
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_EntityDataTypes
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_EntityHoBTs
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_EntityPropertyGroupID
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_LanguageLabels
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityQueryParameters]
--
PRINT(N'Dropping constraints from [SCore].[EntityQueryParameters]')
GO
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS FK_EntityQueryParameters_EntityDataTypes
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS FK_EntityQueryParameters_EntityProperties
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS FK_EntityQueryParameters_EntityQueries
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS FK_EntityQueryParameters_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[LanguageLabels]
--
PRINT(N'Dropping constraints from [SCore].[LanguageLabels]')
GO
ALTER TABLE SCore.LanguageLabels
  DROP CONSTRAINT IF EXISTS FK_LanguageLabels_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[LanguageLabelTranslations]
--
PRINT(N'Dropping constraints from [SCore].[LanguageLabelTranslations]')
GO
ALTER TABLE SCore.LanguageLabelTranslations
  DROP CONSTRAINT IF EXISTS FK_LanguageLabelTranslations_LanguageLabels
ALTER TABLE SCore.LanguageLabelTranslations
  DROP CONSTRAINT IF EXISTS FK_LanguageLabelTranslations_Languages
ALTER TABLE SCore.LanguageLabelTranslations
  DROP CONSTRAINT IF EXISTS FK_LanguageLabelTranslations_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityPropertyActions]
--
PRINT(N'Dropping constraints from [SCore].[EntityPropertyActions]')
GO
ALTER TABLE SCore.EntityPropertyActions
  DROP CONSTRAINT IF EXISTS FK_EntityPropertyActions_EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityPropertyDependants]
--
PRINT(N'Dropping constraints from [SCore].[EntityPropertyDependants]')
GO
ALTER TABLE SCore.EntityPropertyDependants
  DROP CONSTRAINT IF EXISTS FK_EntityPropertyDependants_EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[MergeDocumentItemIncludes]
--
PRINT(N'Dropping constraints from [SCore].[MergeDocumentItemIncludes]')
GO
ALTER TABLE SCore.MergeDocumentItemIncludes
  DROP CONSTRAINT IF EXISTS FK_MergeDocumentItemIncludes_EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[RecordHistory]
--
PRINT(N'Dropping constraints from [SCore].[RecordHistory]')
GO
ALTER TABLE SCore.RecordHistory
  DROP CONSTRAINT IF EXISTS FK_RecordHistory_EntityPropertyID
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[SynchronisationErrors]
--
PRINT(N'Dropping constraints from [SCore].[SynchronisationErrors]')
GO
ALTER TABLE SCore.SynchronisationErrors
  DROP CONSTRAINT IF EXISTS FK_SychronisationErrors_EntityPropertyID
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityPropertyGroups]
--
PRINT(N'Dropping constraints from [SCore].[EntityPropertyGroups]')
GO
ALTER TABLE SCore.EntityPropertyGroups
  DROP CONSTRAINT IF EXISTS FK_EntityPropertyGroups_LanguageLabels
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityTypes]
--
PRINT(N'Dropping constraints from [SCore].[EntityTypes]')
GO
ALTER TABLE SCore.EntityTypes
  DROP CONSTRAINT IF EXISTS FK_EntityTypes_LanguageLabels
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[ActionMenuItems]
--
PRINT(N'Dropping constraints from [SUserInterface].[ActionMenuItems]')
GO
ALTER TABLE SUserInterface.ActionMenuItems
  DROP CONSTRAINT IF EXISTS FK_ActionMenuItems_LanguageLabels
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridDefinitions]
--
PRINT(N'Dropping constraints from [SUserInterface].[GridDefinitions]')
GO
ALTER TABLE SUserInterface.GridDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridDefinitions_LanguageLabelId
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridViewActions]
--
PRINT(N'Dropping constraints from [SUserInterface].[GridViewActions]')
GO
ALTER TABLE SUserInterface.GridViewActions
  DROP CONSTRAINT IF EXISTS FK_GridViewActions_LanguageLabelId
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridViewColumnDefinitions]
--
PRINT(N'Dropping constraints from [SUserInterface].[GridViewColumnDefinitions]')
GO
ALTER TABLE SUserInterface.GridViewColumnDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewColumnDefinitions_LanguageLabelId
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridViewDefinitions]
--
PRINT(N'Dropping constraints from [SUserInterface].[GridViewDefinitions]')
GO
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_LanguageLabelId
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridViewWidgetQueries]
--
PRINT(N'Dropping constraints from [SUserInterface].[GridViewWidgetQueries]')
GO
ALTER TABLE SUserInterface.GridViewWidgetQueries
  DROP CONSTRAINT IF EXISTS FK_GridViewWidgetQueries_LanguageLabels
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[MainMenuItems]
--
PRINT(N'Dropping constraints from [SUserInterface].[MainMenuItems]')
GO
ALTER TABLE SUserInterface.MainMenuItems
  DROP CONSTRAINT IF EXISTS FK_MainMenuItems_LanguageLabelId
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping indexes and constraints from [SCore].[EntityProperties]
--
PRINT(N'Dropping indexes and constraints from [SCore].[EntityProperties]')
GO
DROP INDEX IF EXISTS IX_UQ_EntityProperties_Guid ON SCore.EntityProperties
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
DROP INDEX IF EXISTS IX_UQ_EntityProperties_Hobt_Name ON SCore.EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping indexes and constraints from [SCore].[EntityQueryParameters]
--
PRINT(N'Dropping indexes and constraints from [SCore].[EntityQueryParameters]')
GO
DROP INDEX IF EXISTS IX_EntityQueryParameters_Settings ON SCore.EntityQueryParameters
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping indexes and constraints from [SCore].[LanguageLabels]
--
PRINT(N'Dropping indexes and constraints from [SCore].[LanguageLabels]')
GO
DROP INDEX IF EXISTS IX_SCore_LanguageLabels_1003669193 ON SCore.LanguageLabels
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
DROP INDEX IF EXISTS IX_SCore_LanguageLabels_1008315981 ON SCore.LanguageLabels
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
DROP INDEX IF EXISTS IX_SCore_LanguageLabels_1885346130 ON SCore.LanguageLabels
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping indexes and constraints from [SCore].[LanguageLabelTranslations]
--
PRINT(N'Dropping indexes and constraints from [SCore].[LanguageLabelTranslations]')
GO
DROP INDEX IF EXISTS IX_SCore_LanguageLabelTranslations_1112326884 ON SCore.LanguageLabelTranslations
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
DROP INDEX IF EXISTS IX_SCore_LanguageLabelTranslations_1368578410 ON SCore.LanguageLabelTranslations
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
DROP INDEX IF EXISTS IX_SCore_LanguageLabelTranslations_1684617698 ON SCore.LanguageLabelTranslations
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
DROP INDEX IF EXISTS IX_SCore_LanguageLabelTranslations_2005253351 ON SCore.LanguageLabelTranslations
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityProperties]
--
PRINT(N'Dropping constraints from [SCore].[EntityProperties]')
GO
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DEFAULT_EntityProperties_IsObjectLabel
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DEFAULT_EntityProperties_IsParentRelationship
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_AllowBulkChange
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_DoNotTrackChanges
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_DropDownListDefinitionID
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_EntityDateTypeID
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_EntityHoBTID
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_EntityPropertyGroupID
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_FixDefaultValue
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_GroupSortOrder
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_Guid
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_IsAlwaysVisibleInGroup
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_IsAlwaysVisibleInGroup_Mobile
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_IsCompulsory
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_IsHidden
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_IsImmutable
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_IsIncludedInformation
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_IsLatitude
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_IsLongitude
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_IsReadOnly
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_IsUppercase
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_IsVirtual
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_LanguageLabelID
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_MaxLength
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_Name
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_Precision
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_RowStatus
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_Scale
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_ShowOnMobile
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_SortOrder
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS DF_EntityProperties_SqlDefaultValueScript
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityQueryParameters]
--
PRINT(N'Dropping constraints from [SCore].[EntityQueryParameters]')
GO
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS DF_EntityQueryParameters_DefaultValue
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS DF_EntityQueryParameters_EntityDateTypeID
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS DF_EntityQueryParameters_EntityPropertyID
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS DF_EntityQueryParameters_EntityQueryID
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS DF_EntityQueryParameters_Guid
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS DF_EntityQueryParameters_IsInput
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS DF_EntityQueryParameters_IsOutput
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS DF_EntityQueryParameters_IsReturnColumn
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS DF_EntityQueryParameters_Name
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS DF_EntityQueryParameters_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[LanguageLabels]
--
PRINT(N'Dropping constraints from [SCore].[LanguageLabels]')
GO
ALTER TABLE SCore.LanguageLabels
  DROP CONSTRAINT IF EXISTS DF_LanguageLabels_Guid
ALTER TABLE SCore.LanguageLabels
  DROP CONSTRAINT IF EXISTS DF_LanguageLabels_Name
ALTER TABLE SCore.LanguageLabels
  DROP CONSTRAINT IF EXISTS DF_LanguageLabels_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[LanguageLabelTranslations]
--
PRINT(N'Dropping constraints from [SCore].[LanguageLabelTranslations]')
GO
ALTER TABLE SCore.LanguageLabelTranslations
  DROP CONSTRAINT IF EXISTS DF_LanguageLabelTranslations_Guid
ALTER TABLE SCore.LanguageLabelTranslations
  DROP CONSTRAINT IF EXISTS DF_LanguageLabelTranslations_HelpText
ALTER TABLE SCore.LanguageLabelTranslations
  DROP CONSTRAINT IF EXISTS DF_LanguageLabelTranslations_LanguageID
ALTER TABLE SCore.LanguageLabelTranslations
  DROP CONSTRAINT IF EXISTS DF_LanguageLabelTranslations_LanguageLabelID
ALTER TABLE SCore.LanguageLabelTranslations
  DROP CONSTRAINT IF EXISTS DF_LanguageLabelTranslations_RowStatus
ALTER TABLE SCore.LanguageLabelTranslations
  DROP CONSTRAINT IF EXISTS DF_LanguageLabelTranslations_Text
ALTER TABLE SCore.LanguageLabelTranslations
  DROP CONSTRAINT IF EXISTS DF_LanguageLabelTranslations_TextPlural
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping not null constraints from [SCore].[EntityProperties]
--
PRINT(N'Dropping not null constraints from [SCore].[EntityProperties]')
GO
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN RowStatus tinyint
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN RowVersion timestamp
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN Guid DROP ROWGUIDCOL
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN Guid uniqueidentifier
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN Name nvarchar(250)
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN LanguageLabelID int
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN EntityHoBTID int
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN EntityDataTypeID int
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsReadOnly bit
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsImmutable bit
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsUppercase bit
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsHidden bit
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsCompulsory bit
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN MaxLength int
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN Precision int
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN Scale int
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN DoNotTrackChanges bit
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN EntityPropertyGroupID int
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN SortOrder smallint
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN GroupSortOrder smallint
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsObjectLabel bit
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN DropDownListDefinitionID int
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsParentRelationship bit
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsLongitude bit
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsLatitude bit
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsIncludedInformation bit
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN FixedDefaultValue nvarchar(50)
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN SqlDefaultValueStatement nvarchar(4000)
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN AllowBulkChange bit
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsVirtual bit
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN ShowOnMobile bit
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsAlwaysVisibleInGroup bit
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsAlwaysVisibleInGroup_Mobile bit
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping not null constraints from [SCore].[EntityQueryParameters]
--
PRINT(N'Dropping not null constraints from [SCore].[EntityQueryParameters]')
GO
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN RowStatus tinyint
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN RowVersion timestamp
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN Guid DROP ROWGUIDCOL
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN Guid uniqueidentifier
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN Name nvarchar(250)
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN EntityQueryID int
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN EntityDataTypeID int
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN MappedEntityPropertyID int
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN DefaultValue nvarchar(100)
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN IsInput bit
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN IsOutput bit
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN IsReturnColumn bit
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping not null constraints from [SCore].[LanguageLabels]
--
PRINT(N'Dropping not null constraints from [SCore].[LanguageLabels]')
GO
ALTER TABLE SCore.LanguageLabels
  ALTER
    COLUMN RowStatus tinyint
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.LanguageLabels
  ALTER
    COLUMN RowVersion timestamp
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.LanguageLabels
  ALTER
    COLUMN Guid DROP ROWGUIDCOL
ALTER TABLE SCore.LanguageLabels
  ALTER
    COLUMN Guid uniqueidentifier
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.LanguageLabels
  ALTER
    COLUMN Name nvarchar(250)
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping not null constraints from [SCore].[LanguageLabelTranslations]
--
PRINT(N'Dropping not null constraints from [SCore].[LanguageLabelTranslations]')
GO
ALTER TABLE SCore.LanguageLabelTranslations
  ALTER
    COLUMN RowStatus tinyint
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.LanguageLabelTranslations
  ALTER
    COLUMN RowVersion timestamp
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.LanguageLabelTranslations
  ALTER
    COLUMN Guid DROP ROWGUIDCOL
ALTER TABLE SCore.LanguageLabelTranslations
  ALTER
    COLUMN Guid uniqueidentifier
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.LanguageLabelTranslations
  ALTER
    COLUMN Text nvarchar(250)
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.LanguageLabelTranslations
  ALTER
    COLUMN TextPlural nvarchar(250)
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.LanguageLabelTranslations
  ALTER
    COLUMN LanguageLabelID int
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.LanguageLabelTranslations
  ALTER
    COLUMN LanguageID int
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.LanguageLabelTranslations
  ALTER
    COLUMN HelpText nvarchar(max)
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Inserting data into table SCore.EntityProperties
--
PRINT(N'Inserting data into table SCore.EntityProperties')
GO
SET IDENTITY_INSERT SCore.EntityProperties ON
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
IF NOT EXISTS (SELECT ID, RowStatus, Guid, Name, LanguageLabelID, EntityHoBTID, EntityDataTypeID, IsReadOnly, IsImmutable, IsUppercase, IsHidden, IsCompulsory, MaxLength, Precision, Scale, DoNotTrackChanges, EntityPropertyGroupID, SortOrder, GroupSortOrder, IsObjectLabel, DropDownListDefinitionID, IsParentRelationship, IsLongitude, IsLatitude, IsIncludedInformation, FixedDefaultValue, SqlDefaultValueStatement, AllowBulkChange, IsVirtual, ShowOnMobile, IsAlwaysVisibleInGroup, IsAlwaysVisibleInGroup_Mobile FROM SCore.EntityProperties WITH (NOLOCK) WHERE ID = 2803)
INSERT SCore.EntityProperties(ID, RowStatus, Guid, Name, LanguageLabelID, EntityHoBTID, EntityDataTypeID, IsReadOnly, IsImmutable, IsUppercase, IsHidden, IsCompulsory, MaxLength, Precision, Scale, DoNotTrackChanges, EntityPropertyGroupID, SortOrder, GroupSortOrder, IsObjectLabel, DropDownListDefinitionID, IsParentRelationship, IsLongitude, IsLatitude, IsIncludedInformation, FixedDefaultValue, SqlDefaultValueStatement, AllowBulkChange, IsVirtual, ShowOnMobile, IsAlwaysVisibleInGroup, IsAlwaysVisibleInGroup_Mobile) VALUES (2803, 1, '47583ed8-d82b-4575-9447-8374fddc9068', N'ScheduleReenabled', 4194, 155, 4, 0, 0, 0, 1, 0, 0, 0, 0, 0, -1, 0, 0, 0, -1, 0, 0, 0, 0, N'', N'', 0, 0, 0, 0, 0)
GO
SET IDENTITY_INSERT SCore.EntityProperties OFF
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Inserting data into table SCore.EntityQueryParameters
--
PRINT(N'Inserting data into table SCore.EntityQueryParameters')
GO
SET IDENTITY_INSERT SCore.EntityQueryParameters ON
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
IF NOT EXISTS (SELECT ID, RowStatus, Guid, Name, EntityQueryID, EntityDataTypeID, MappedEntityPropertyID, DefaultValue, IsInput, IsOutput, IsReturnColumn FROM SCore.EntityQueryParameters WITH (NOLOCK) WHERE ID = 1607)
INSERT SCore.EntityQueryParameters(ID, RowStatus, Guid, Name, EntityQueryID, EntityDataTypeID, MappedEntityPropertyID, DefaultValue, IsInput, IsOutput, IsReturnColumn) VALUES (1607, 1, 'c30b1590-085f-4da7-bd90-8b07fe845654', N'@ScheduleReenabled', 362, 4, 2803, N'', 1, 0, 0)
GO
SET IDENTITY_INSERT SCore.EntityQueryParameters OFF
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Inserting data into table SCore.LanguageLabels
--
PRINT(N'Inserting data into table SCore.LanguageLabels')
GO
SET IDENTITY_INSERT SCore.LanguageLabels ON
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
IF NOT EXISTS (SELECT ID, RowStatus, Guid, Name FROM SCore.LanguageLabels WITH (NOLOCK) WHERE ID = 4194)
INSERT SCore.LanguageLabels(ID, RowStatus, Guid, Name) VALUES (4194, 1, '50a04e3a-72a3-4680-97c4-bc9b4dd1c5a0', N'[SFin].[InvoiceSchedules].[ScheduleReenabled]')
GO
SET IDENTITY_INSERT SCore.LanguageLabels OFF
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Reseed identity on SCore.LanguageLabels
--
PRINT(N'Reseed identity on SCore.LanguageLabels')
GO
DBCC CHECKIDENT('SCore.LanguageLabels', RESEED, 4227)
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Inserting data into table SCore.LanguageLabelTranslations
--
PRINT(N'Inserting data into table SCore.LanguageLabelTranslations')
GO
SET IDENTITY_INSERT SCore.LanguageLabelTranslations ON
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
IF NOT EXISTS (SELECT ID, RowStatus, Guid, Text, TextPlural, LanguageLabelID, LanguageID, HelpText FROM SCore.LanguageLabelTranslations WITH (NOLOCK) WHERE ID = 4179)
INSERT SCore.LanguageLabelTranslations(ID, RowStatus, Guid, Text, TextPlural, LanguageLabelID, LanguageID, HelpText) VALUES (4179, 1, 'cacf8386-fbb0-4f1a-a093-2774604d3153', N'Schedule Reenabled', N'Schedule Reenabled', 4194, 1, N'')
GO
SET IDENTITY_INSERT SCore.LanguageLabelTranslations OFF
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Reseed identity on SCore.LanguageLabelTranslations
--
PRINT(N'Reseed identity on SCore.LanguageLabelTranslations')
GO
DBCC CHECKIDENT('SCore.LanguageLabelTranslations', RESEED, 4212)
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityProperties]
--
PRINT(N'Creating constraints for [SCore].[EntityProperties]')
GO
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DEFAULT_EntityProperties_IsObjectLabel DEFAULT (0) FOR IsObjectLabel
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DEFAULT_EntityProperties_IsParentRelationship DEFAULT (0) FOR IsParentRelationship
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_AllowBulkChange DEFAULT (0) FOR AllowBulkChange
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_DoNotTrackChanges DEFAULT (0) FOR DoNotTrackChanges
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_DropDownListDefinitionID DEFAULT (-1) FOR DropDownListDefinitionID
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_EntityDateTypeID DEFAULT (-1) FOR EntityDataTypeID
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_EntityHoBTID DEFAULT (-1) FOR EntityHoBTID
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_EntityPropertyGroupID DEFAULT (-1) FOR EntityPropertyGroupID
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_FixDefaultValue DEFAULT ('') FOR FixedDefaultValue
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_GroupSortOrder DEFAULT (0) FOR GroupSortOrder
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_Guid DEFAULT (newid()) FOR Guid
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_IsAlwaysVisibleInGroup DEFAULT (0) FOR IsAlwaysVisibleInGroup
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_IsAlwaysVisibleInGroup_Mobile DEFAULT (0) FOR IsAlwaysVisibleInGroup_Mobile
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_IsCompulsory DEFAULT (0) FOR IsCompulsory
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_IsHidden DEFAULT (0) FOR IsHidden
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_IsImmutable DEFAULT (0) FOR IsImmutable
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_IsIncludedInformation DEFAULT (0) FOR IsIncludedInformation
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_IsLatitude DEFAULT (0) FOR IsLatitude
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_IsLongitude DEFAULT (0) FOR IsLongitude
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_IsReadOnly DEFAULT (0) FOR IsReadOnly
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_IsUppercase DEFAULT (0) FOR IsUppercase
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_IsVirtual DEFAULT (0) FOR IsVirtual
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_LanguageLabelID DEFAULT (-1) FOR LanguageLabelID
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_MaxLength DEFAULT (0) FOR MaxLength
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_Name DEFAULT ('') FOR Name
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_Precision DEFAULT (0) FOR Precision
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_RowStatus DEFAULT (0) FOR RowStatus
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_Scale DEFAULT (0) FOR Scale
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_ShowOnMobile DEFAULT (0) FOR ShowOnMobile
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_SortOrder DEFAULT (0) FOR SortOrder
ALTER TABLE SCore.EntityProperties
  ADD CONSTRAINT DF_EntityProperties_SqlDefaultValueScript DEFAULT ('') FOR SqlDefaultValueStatement
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityQueryParameters]
--
PRINT(N'Creating constraints for [SCore].[EntityQueryParameters]')
GO
ALTER TABLE SCore.EntityQueryParameters
  ADD CONSTRAINT DF_EntityQueryParameters_DefaultValue DEFAULT ('') FOR DefaultValue
ALTER TABLE SCore.EntityQueryParameters
  ADD CONSTRAINT DF_EntityQueryParameters_EntityDateTypeID DEFAULT (-1) FOR EntityDataTypeID
ALTER TABLE SCore.EntityQueryParameters
  ADD CONSTRAINT DF_EntityQueryParameters_EntityPropertyID DEFAULT (-1) FOR MappedEntityPropertyID
ALTER TABLE SCore.EntityQueryParameters
  ADD CONSTRAINT DF_EntityQueryParameters_EntityQueryID DEFAULT (-1) FOR EntityQueryID
ALTER TABLE SCore.EntityQueryParameters
  ADD CONSTRAINT DF_EntityQueryParameters_Guid DEFAULT (newid()) FOR Guid
ALTER TABLE SCore.EntityQueryParameters
  ADD CONSTRAINT DF_EntityQueryParameters_IsInput DEFAULT (0) FOR IsInput
ALTER TABLE SCore.EntityQueryParameters
  ADD CONSTRAINT DF_EntityQueryParameters_IsOutput DEFAULT (0) FOR IsOutput
ALTER TABLE SCore.EntityQueryParameters
  ADD CONSTRAINT DF_EntityQueryParameters_IsReturnColumn DEFAULT (0) FOR IsReturnColumn
ALTER TABLE SCore.EntityQueryParameters
  ADD CONSTRAINT DF_EntityQueryParameters_Name DEFAULT ('') FOR Name
ALTER TABLE SCore.EntityQueryParameters
  ADD CONSTRAINT DF_EntityQueryParameters_RowStatus DEFAULT (0) FOR RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[LanguageLabels]
--
PRINT(N'Creating constraints for [SCore].[LanguageLabels]')
GO
ALTER TABLE SCore.LanguageLabels
  ADD CONSTRAINT DF_LanguageLabels_Guid DEFAULT (newid()) FOR Guid
ALTER TABLE SCore.LanguageLabels
  ADD CONSTRAINT DF_LanguageLabels_Name DEFAULT ('') FOR Name
ALTER TABLE SCore.LanguageLabels
  ADD CONSTRAINT DF_LanguageLabels_RowStatus DEFAULT (0) FOR RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[LanguageLabelTranslations]
--
PRINT(N'Creating constraints for [SCore].[LanguageLabelTranslations]')
GO
ALTER TABLE SCore.LanguageLabelTranslations
  ADD CONSTRAINT DF_LanguageLabelTranslations_Guid DEFAULT (newid()) FOR Guid
ALTER TABLE SCore.LanguageLabelTranslations
  ADD CONSTRAINT DF_LanguageLabelTranslations_HelpText DEFAULT ('') FOR HelpText
ALTER TABLE SCore.LanguageLabelTranslations
  ADD CONSTRAINT DF_LanguageLabelTranslations_LanguageID DEFAULT (-1) FOR LanguageID
ALTER TABLE SCore.LanguageLabelTranslations
  ADD CONSTRAINT DF_LanguageLabelTranslations_LanguageLabelID DEFAULT (-1) FOR LanguageLabelID
ALTER TABLE SCore.LanguageLabelTranslations
  ADD CONSTRAINT DF_LanguageLabelTranslations_RowStatus DEFAULT (0) FOR RowStatus
ALTER TABLE SCore.LanguageLabelTranslations
  ADD CONSTRAINT DF_LanguageLabelTranslations_Text DEFAULT ('') FOR Text
ALTER TABLE SCore.LanguageLabelTranslations
  ADD CONSTRAINT DF_LanguageLabelTranslations_TextPlural DEFAULT ('') FOR TextPlural
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating not null constraints for [SCore].[EntityProperties]
--
PRINT(N'Creating not null constraints for [SCore].[EntityProperties]')
GO
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN RowStatus tinyint NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN RowVersion timestamp NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN Guid uniqueidentifier NOT NULL
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN Guid ADD ROWGUIDCOL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN Name nvarchar(250) NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN LanguageLabelID int NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN EntityHoBTID int NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN EntityDataTypeID int NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsReadOnly bit NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsImmutable bit NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsUppercase bit NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsHidden bit NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsCompulsory bit NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN MaxLength int NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN Precision int NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN Scale int NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN DoNotTrackChanges bit NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN EntityPropertyGroupID int NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN SortOrder smallint NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN GroupSortOrder smallint NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsObjectLabel bit NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN DropDownListDefinitionID int NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsParentRelationship bit NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsLongitude bit NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsLatitude bit NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsIncludedInformation bit NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN FixedDefaultValue nvarchar(50) NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN SqlDefaultValueStatement nvarchar(4000) NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN AllowBulkChange bit NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsVirtual bit NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN ShowOnMobile bit NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsAlwaysVisibleInGroup bit NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityProperties
  ALTER
    COLUMN IsAlwaysVisibleInGroup_Mobile bit NOT NULL
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating not null constraints for [SCore].[EntityQueryParameters]
--
PRINT(N'Creating not null constraints for [SCore].[EntityQueryParameters]')
GO
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN RowStatus tinyint NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN RowVersion timestamp NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN Guid uniqueidentifier NOT NULL
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN Guid ADD ROWGUIDCOL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN Name nvarchar(250) NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN EntityQueryID int NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN EntityDataTypeID int NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN MappedEntityPropertyID int NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN DefaultValue nvarchar(100) NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN IsInput bit NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN IsOutput bit NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.EntityQueryParameters
  ALTER
    COLUMN IsReturnColumn bit NOT NULL
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating not null constraints for [SCore].[LanguageLabels]
--
PRINT(N'Creating not null constraints for [SCore].[LanguageLabels]')
GO
ALTER TABLE SCore.LanguageLabels
  ALTER
    COLUMN RowStatus tinyint NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.LanguageLabels
  ALTER
    COLUMN RowVersion timestamp NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.LanguageLabels
  ALTER
    COLUMN Guid uniqueidentifier NOT NULL
ALTER TABLE SCore.LanguageLabels
  ALTER
    COLUMN Guid ADD ROWGUIDCOL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.LanguageLabels
  ALTER
    COLUMN Name nvarchar(250) NOT NULL
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating not null constraints for [SCore].[LanguageLabelTranslations]
--
PRINT(N'Creating not null constraints for [SCore].[LanguageLabelTranslations]')
GO
ALTER TABLE SCore.LanguageLabelTranslations
  ALTER
    COLUMN RowStatus tinyint NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.LanguageLabelTranslations
  ALTER
    COLUMN RowVersion timestamp NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.LanguageLabelTranslations
  ALTER
    COLUMN Guid uniqueidentifier NOT NULL
ALTER TABLE SCore.LanguageLabelTranslations
  ALTER
    COLUMN Guid ADD ROWGUIDCOL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.LanguageLabelTranslations
  ALTER
    COLUMN Text nvarchar(250) NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.LanguageLabelTranslations
  ALTER
    COLUMN TextPlural nvarchar(250) NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.LanguageLabelTranslations
  ALTER
    COLUMN LanguageLabelID int NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.LanguageLabelTranslations
  ALTER
    COLUMN LanguageID int NOT NULL
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
ALTER TABLE SCore.LanguageLabelTranslations
  ALTER
    COLUMN HelpText nvarchar(max) NOT NULL
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating indexes and constraints for [SCore].[EntityProperties]
--
PRINT(N'Creating indexes and constraints for [SCore].[EntityProperties]')
GO
CREATE UNIQUE INDEX IX_UQ_EntityProperties_Hobt_Name
  ON SCore.EntityProperties (EntityHoBTID, Name, RowStatus)
  INCLUDE (Guid)
  WHERE ([RowStatus]<>(0) AND [RowStatus]<>(254))
  WITH (FILLFACTOR = 100)
  ON [PRIMARY]
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
CREATE UNIQUE INDEX IX_UQ_EntityProperties_Guid
  ON SCore.EntityProperties (Guid)
  WITH (FILLFACTOR = 100)
  ON [PRIMARY]
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating indexes and constraints for [SCore].[EntityQueryParameters]
--
PRINT(N'Creating indexes and constraints for [SCore].[EntityQueryParameters]')
GO
CREATE INDEX IX_EntityQueryParameters_Settings
  ON SCore.EntityQueryParameters (EntityQueryID, RowStatus)
  INCLUDE (RowVersion, Guid, Name, EntityDataTypeID, MappedEntityPropertyID)
  WHERE ([RowStatus]<>(0) AND [RowStatus]<>(254))
  WITH (FILLFACTOR = 100)
  ON METADATA
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating indexes and constraints for [SCore].[LanguageLabels]
--
PRINT(N'Creating indexes and constraints for [SCore].[LanguageLabels]')
GO
CREATE INDEX IX_SCore_LanguageLabels_1885346130
  ON SCore.LanguageLabels (RowStatus)
  WITH (FILLFACTOR = 90)
  ON METADATA
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
CREATE INDEX IX_SCore_LanguageLabels_1008315981
  ON SCore.LanguageLabels (Guid)
  WITH (FILLFACTOR = 90)
  ON METADATA
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
CREATE INDEX IX_SCore_LanguageLabels_1003669193
  ON SCore.LanguageLabels (RowStatus)
  INCLUDE (Guid, Name)
  WITH (FILLFACTOR = 90)
  ON METADATA
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating indexes and constraints for [SCore].[LanguageLabelTranslations]
--
PRINT(N'Creating indexes and constraints for [SCore].[LanguageLabelTranslations]')
GO
CREATE INDEX IX_SCore_LanguageLabelTranslations_2005253351
  ON SCore.LanguageLabelTranslations (LanguageLabelID, LanguageID)
  INCLUDE (RowStatus)
  WITH (FILLFACTOR = 90)
  ON METADATA
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
CREATE INDEX IX_SCore_LanguageLabelTranslations_1684617698
  ON SCore.LanguageLabelTranslations (LanguageLabelID, LanguageID)
  INCLUDE (RowStatus, Text)
  WITH (FILLFACTOR = 90)
  ON METADATA
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
CREATE INDEX IX_SCore_LanguageLabelTranslations_1368578410
  ON SCore.LanguageLabelTranslations (LanguageLabelID, LanguageID)
  INCLUDE (RowStatus, TextPlural)
  WITH (FILLFACTOR = 90)
  ON METADATA
GO
IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
CREATE INDEX IX_SCore_LanguageLabelTranslations_1112326884
  ON SCore.LanguageLabelTranslations (LanguageLabelID, RowStatus)
  WITH (FILLFACTOR = 90)
  ON METADATA
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityProperties]
--
PRINT(N'Creating constraints for [SCore].[EntityProperties]')
GO
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_DropDownListDefinitions FOREIGN KEY (DropDownListDefinitionID) REFERENCES SUserInterface.DropDownListDefinitions(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_EntityDataTypes FOREIGN KEY (EntityDataTypeID) REFERENCES SCore.EntityDataTypes(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_EntityHoBTs FOREIGN KEY (EntityHoBTID) REFERENCES SCore.EntityHobts(ID) ON DELETE CASCADE ON UPDATE NO ACTION
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_EntityPropertyGroupID FOREIGN KEY (EntityPropertyGroupID) REFERENCES SCore.EntityPropertyGroups(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_LanguageLabels FOREIGN KEY (LanguageLabelID) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityQueryParameters]
--
PRINT(N'Creating constraints for [SCore].[EntityQueryParameters]')
GO
ALTER TABLE SCore.EntityQueryParameters WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueryParameters_EntityDataTypes FOREIGN KEY (EntityDataTypeID) REFERENCES SCore.EntityDataTypes(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityQueryParameters WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueryParameters_EntityProperties FOREIGN KEY (MappedEntityPropertyID) REFERENCES SCore.EntityProperties(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityQueryParameters WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueryParameters_EntityQueries FOREIGN KEY (EntityQueryID) REFERENCES SCore.EntityQueries(ID) ON DELETE CASCADE ON UPDATE NO ACTION
ALTER TABLE SCore.EntityQueryParameters WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueryParameters_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[LanguageLabels]
--
PRINT(N'Creating constraints for [SCore].[LanguageLabels]')
GO
ALTER TABLE SCore.LanguageLabels WITH NOCHECK
  ADD CONSTRAINT FK_LanguageLabels_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[LanguageLabelTranslations]
--
PRINT(N'Creating constraints for [SCore].[LanguageLabelTranslations]')
GO
ALTER TABLE SCore.LanguageLabelTranslations WITH NOCHECK
  ADD CONSTRAINT FK_LanguageLabelTranslations_LanguageLabels FOREIGN KEY (LanguageLabelID) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.LanguageLabelTranslations WITH NOCHECK
  ADD CONSTRAINT FK_LanguageLabelTranslations_Languages FOREIGN KEY (LanguageID) REFERENCES SCore.Languages(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.LanguageLabelTranslations WITH NOCHECK
  ADD CONSTRAINT FK_LanguageLabelTranslations_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityPropertyActions]
--
PRINT(N'Creating constraints for [SCore].[EntityPropertyActions]')
GO
ALTER TABLE SCore.EntityPropertyActions WITH NOCHECK
  ADD CONSTRAINT FK_EntityPropertyActions_EntityProperties FOREIGN KEY (EntityPropertyID) REFERENCES SCore.EntityProperties(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityPropertyDependants]
--
PRINT(N'Creating constraints for [SCore].[EntityPropertyDependants]')
GO
ALTER TABLE SCore.EntityPropertyDependants WITH NOCHECK
  ADD CONSTRAINT FK_EntityPropertyDependants_EntityProperties FOREIGN KEY (ParentEntityPropertyID) REFERENCES SCore.EntityProperties(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[MergeDocumentItemIncludes]
--
PRINT(N'Creating constraints for [SCore].[MergeDocumentItemIncludes]')
GO
ALTER TABLE SCore.MergeDocumentItemIncludes WITH NOCHECK
  ADD CONSTRAINT FK_MergeDocumentItemIncludes_EntityProperties FOREIGN KEY (SourceDocumentEntityPropertyId) REFERENCES SCore.EntityProperties(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[RecordHistory]
--
PRINT(N'Creating constraints for [SCore].[RecordHistory]')
GO
ALTER TABLE SCore.RecordHistory WITH NOCHECK
  ADD CONSTRAINT FK_RecordHistory_EntityPropertyID FOREIGN KEY (EntityPropertyID) REFERENCES SCore.EntityProperties(ID) ON DELETE CASCADE ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[SynchronisationErrors]
--
PRINT(N'Creating constraints for [SCore].[SynchronisationErrors]')
GO
ALTER TABLE SCore.SynchronisationErrors WITH NOCHECK
  ADD CONSTRAINT FK_SychronisationErrors_EntityPropertyID FOREIGN KEY (EntityPropertyID) REFERENCES SCore.EntityProperties(ID) ON DELETE CASCADE ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityPropertyGroups]
--
PRINT(N'Creating constraints for [SCore].[EntityPropertyGroups]')
GO
ALTER TABLE SCore.EntityPropertyGroups WITH NOCHECK
  ADD CONSTRAINT FK_EntityPropertyGroups_LanguageLabels FOREIGN KEY (LanguageLabelID) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityTypes]
--
PRINT(N'Creating constraints for [SCore].[EntityTypes]')
GO
ALTER TABLE SCore.EntityTypes WITH NOCHECK
  ADD CONSTRAINT FK_EntityTypes_LanguageLabels FOREIGN KEY (LanguageLabelID) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[ActionMenuItems]
--
PRINT(N'Creating constraints for [SUserInterface].[ActionMenuItems]')
GO
ALTER TABLE SUserInterface.ActionMenuItems WITH NOCHECK
  ADD CONSTRAINT FK_ActionMenuItems_LanguageLabels FOREIGN KEY (LanguageLabelId) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridDefinitions]
--
PRINT(N'Creating constraints for [SUserInterface].[GridDefinitions]')
GO
ALTER TABLE SUserInterface.GridDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridDefinitions_LanguageLabelId FOREIGN KEY (LanguageLabelId) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridViewActions]
--
PRINT(N'Creating constraints for [SUserInterface].[GridViewActions]')
GO
ALTER TABLE SUserInterface.GridViewActions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewActions_LanguageLabelId FOREIGN KEY (LanguageLabelId) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridViewColumnDefinitions]
--
PRINT(N'Creating constraints for [SUserInterface].[GridViewColumnDefinitions]')
GO
ALTER TABLE SUserInterface.GridViewColumnDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewColumnDefinitions_LanguageLabelId FOREIGN KEY (LanguageLabelId) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridViewDefinitions]
--
PRINT(N'Creating constraints for [SUserInterface].[GridViewDefinitions]')
GO
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_LanguageLabelId FOREIGN KEY (LanguageLabelId) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridViewWidgetQueries]
--
PRINT(N'Creating constraints for [SUserInterface].[GridViewWidgetQueries]')
GO
ALTER TABLE SUserInterface.GridViewWidgetQueries WITH NOCHECK
  ADD CONSTRAINT FK_GridViewWidgetQueries_LanguageLabels FOREIGN KEY (LanguageLabelID) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[MainMenuItems]
--
PRINT(N'Creating constraints for [SUserInterface].[MainMenuItems]')
GO
ALTER TABLE SUserInterface.MainMenuItems WITH NOCHECK
  ADD CONSTRAINT FK_MainMenuItems_LanguageLabelId FOREIGN KEY (LanguageLabelId) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Enabling DML triggers for [SCore].[EntityProperties]
--
PRINT(N'Enabling DML triggers for [SCore].[EntityProperties]')
GO
ENABLE TRIGGER ALL ON SCore.EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Enabling DML triggers for [SCore].[EntityQueryParameters]
--
PRINT(N'Enabling DML triggers for [SCore].[EntityQueryParameters]')
GO
ENABLE TRIGGER ALL ON SCore.EntityQueryParameters
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Enabling DML triggers for [SCore].[LanguageLabels]
--
PRINT(N'Enabling DML triggers for [SCore].[LanguageLabels]')
GO
ENABLE TRIGGER ALL ON SCore.LanguageLabels
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Enabling DML triggers for [SCore].[LanguageLabelTranslations]
--
PRINT(N'Enabling DML triggers for [SCore].[LanguageLabelTranslations]')
GO
ENABLE TRIGGER ALL ON SCore.LanguageLabelTranslations
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END


--
-- Commit Transaction
--
PRINT(N'Commit Transaction')
GO
IF @@TRANCOUNT>0 COMMIT TRANSACTION
SET NOEXEC OFF
GO