--
-- Script was generated by Devart dbForge Data Compare for SQL Server, Version 5.5.3.0
-- Product Home Page: http://www.devart.com/dbforge/sql/datacompare
-- Script date 05/03/2026 14:20:29
-- Source server version: 16.00.1000
-- Source connection string: Data Source=SOC-SQLDEVBRE01\GENERAL;Initial Catalog=CymBuild_Dev;Integrated Security=True;User ID=ESGL\stephen.brett
-- Target server version: 16.00.1000
-- Target connection string: Data Source=SOC-SQLDEVBRE01\GENERAL;Initial Catalog=CymBuild_Dev;Integrated Security=True;User ID=ESGL\stephen.brett
-- Run this script against Cymbuild_QA to synchronize it with CymBuild_Dev
-- Please backup your target database before running this script
--



SET LANGUAGE 'British English'
SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT, XACT_ABORT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS OFF
GO


--
-- Start Transaction
--
PRINT(N'Start Transaction')
GO
BEGIN TRANSACTION

--
-- Disabling DML triggers for [SCore].[EntityHobts]
--
PRINT(N'Disabling DML triggers for [SCore].[EntityHobts]')
GO
DISABLE TRIGGER ALL ON SCore.EntityHobts
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Disabling DML triggers for [SCore].[EntityProperties]
--
PRINT(N'Disabling DML triggers for [SCore].[EntityProperties]')
GO
DISABLE TRIGGER ALL ON SCore.EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Disabling DML triggers for [SCore].[EntityQueries]
--
PRINT(N'Disabling DML triggers for [SCore].[EntityQueries]')
GO
DISABLE TRIGGER ALL ON SCore.EntityQueries
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Disabling DML triggers for [SCore].[EntityQueryParameters]
--
PRINT(N'Disabling DML triggers for [SCore].[EntityQueryParameters]')
GO
DISABLE TRIGGER ALL ON SCore.EntityQueryParameters
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Disabling DML triggers for [SCore].[LanguageLabels]
--
PRINT(N'Disabling DML triggers for [SCore].[LanguageLabels]')
GO
DISABLE TRIGGER ALL ON SCore.LanguageLabels
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Disabling DML triggers for [SCore].[LanguageLabelTranslations]
--
PRINT(N'Disabling DML triggers for [SCore].[LanguageLabelTranslations]')
GO
DISABLE TRIGGER ALL ON SCore.LanguageLabelTranslations
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Disabling DML triggers for [SUserInterface].[DropDownListDefinitions]
--
PRINT(N'Disabling DML triggers for [SUserInterface].[DropDownListDefinitions]')
GO
DISABLE TRIGGER ALL ON SUserInterface.DropDownListDefinitions
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityHobts]
--
PRINT(N'Dropping constraints from [SCore].[EntityHobts]')
GO
ALTER TABLE SCore.EntityHobts
  DROP CONSTRAINT IF EXISTS FK_EntityHoBTs_EntityTypes
ALTER TABLE SCore.EntityHobts
  DROP CONSTRAINT IF EXISTS FK_EntityHobts_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityProperties]
--
PRINT(N'Dropping constraints from [SCore].[EntityProperties]')
GO
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_DropDownListDefinitions
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_EntityDataTypes
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_EntityHoBTs
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_EntityPropertyGroupID
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_LanguageLabels
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityQueries]
--
PRINT(N'Dropping constraints from [SCore].[EntityQueries]')
GO
ALTER TABLE SCore.EntityQueries
  DROP CONSTRAINT IF EXISTS FK_EntityQueries_EntityHoBTs
ALTER TABLE SCore.EntityQueries
  DROP CONSTRAINT IF EXISTS FK_EntityQueries_EntityTypes
ALTER TABLE SCore.EntityQueries
  DROP CONSTRAINT IF EXISTS FK_EntityQueries_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityQueryParameters]
--
PRINT(N'Dropping constraints from [SCore].[EntityQueryParameters]')
GO
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS FK_EntityQueryParameters_EntityDataTypes
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS FK_EntityQueryParameters_EntityProperties
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS FK_EntityQueryParameters_EntityQueries
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS FK_EntityQueryParameters_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[LanguageLabels]
--
PRINT(N'Dropping constraints from [SCore].[LanguageLabels]')
GO
ALTER TABLE SCore.LanguageLabels
  DROP CONSTRAINT IF EXISTS FK_LanguageLabels_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[LanguageLabelTranslations]
--
PRINT(N'Dropping constraints from [SCore].[LanguageLabelTranslations]')
GO
ALTER TABLE SCore.LanguageLabelTranslations
  DROP CONSTRAINT IF EXISTS FK_LanguageLabelTranslations_LanguageLabels
ALTER TABLE SCore.LanguageLabelTranslations
  DROP CONSTRAINT IF EXISTS FK_LanguageLabelTranslations_Languages
ALTER TABLE SCore.LanguageLabelTranslations
  DROP CONSTRAINT IF EXISTS FK_LanguageLabelTranslations_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[DropDownListDefinitions]
--
PRINT(N'Dropping constraints from [SUserInterface].[DropDownListDefinitions]')
GO
ALTER TABLE SUserInterface.DropDownListDefinitions
  DROP CONSTRAINT IF EXISTS FK_DropDownListDefinitions_EntityTypes
ALTER TABLE SUserInterface.DropDownListDefinitions
  DROP CONSTRAINT IF EXISTS FK_DropDownListDefinitions_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridViewColumnDefinitions]
--
PRINT(N'Dropping constraints from [SUserInterface].[GridViewColumnDefinitions]')
GO
ALTER TABLE SUserInterface.GridViewColumnDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewColumnDefinition_GridViewDefinition
ALTER TABLE SUserInterface.GridViewColumnDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewColumnDefinitions_LanguageLabelId
ALTER TABLE SUserInterface.GridViewColumnDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewColumnDefinitions_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridViewDefinitions]
--
PRINT(N'Dropping constraints from [SUserInterface].[GridViewDefinitions]')
GO
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinition_GridDefinition
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_DrawerIconId
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_EntityTypes
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_LanguageLabelId
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_MetricTypes
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[Workflow]
--
PRINT(N'Dropping constraints from [SCore].[Workflow]')
GO
ALTER TABLE SCore.Workflow
  DROP CONSTRAINT IF EXISTS FK_Workflow_EntityHoBTs
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityPropertyActions]
--
PRINT(N'Dropping constraints from [SCore].[EntityPropertyActions]')
GO
ALTER TABLE SCore.EntityPropertyActions
  DROP CONSTRAINT IF EXISTS FK_EntityPropertyActions_EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityPropertyDependants]
--
PRINT(N'Dropping constraints from [SCore].[EntityPropertyDependants]')
GO
ALTER TABLE SCore.EntityPropertyDependants
  DROP CONSTRAINT IF EXISTS FK_EntityPropertyDependants_EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[MergeDocumentItemIncludes]
--
PRINT(N'Dropping constraints from [SCore].[MergeDocumentItemIncludes]')
GO
ALTER TABLE SCore.MergeDocumentItemIncludes
  DROP CONSTRAINT IF EXISTS FK_MergeDocumentItemIncludes_EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[RecordHistory]
--
PRINT(N'Dropping constraints from [SCore].[RecordHistory]')
GO
ALTER TABLE SCore.RecordHistory
  DROP CONSTRAINT IF EXISTS FK_RecordHistory_EntityPropertyID
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[SynchronisationErrors]
--
PRINT(N'Dropping constraints from [SCore].[SynchronisationErrors]')
GO
ALTER TABLE SCore.SynchronisationErrors
  DROP CONSTRAINT IF EXISTS FK_SychronisationErrors_EntityPropertyID
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[ActionMenuItems]
--
PRINT(N'Dropping constraints from [SUserInterface].[ActionMenuItems]')
GO
ALTER TABLE SUserInterface.ActionMenuItems
  DROP CONSTRAINT IF EXISTS FK_ActionMenuItems_EntityQueries
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridViewActions]
--
PRINT(N'Dropping constraints from [SUserInterface].[GridViewActions]')
GO
ALTER TABLE SUserInterface.GridViewActions
  DROP CONSTRAINT IF EXISTS FK_GridViewActions_EntityQueries
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridViewWidgetQueries]
--
PRINT(N'Dropping constraints from [SUserInterface].[GridViewWidgetQueries]')
GO
ALTER TABLE SUserInterface.GridViewWidgetQueries
  DROP CONSTRAINT IF EXISTS FK_GridViewWidgetQueries_EntityQueries
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityPropertyGroups]
--
PRINT(N'Dropping constraints from [SCore].[EntityPropertyGroups]')
GO
ALTER TABLE SCore.EntityPropertyGroups
  DROP CONSTRAINT IF EXISTS FK_EntityPropertyGroups_LanguageLabels
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityTypes]
--
PRINT(N'Dropping constraints from [SCore].[EntityTypes]')
GO
ALTER TABLE SCore.EntityTypes
  DROP CONSTRAINT IF EXISTS FK_EntityTypes_LanguageLabels
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridDefinitions]
--
PRINT(N'Dropping constraints from [SUserInterface].[GridDefinitions]')
GO
ALTER TABLE SUserInterface.GridDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridDefinitions_LanguageLabelId
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[MainMenuItems]
--
PRINT(N'Dropping constraints from [SUserInterface].[MainMenuItems]')
GO
ALTER TABLE SUserInterface.MainMenuItems
  DROP CONSTRAINT IF EXISTS FK_MainMenuItems_LanguageLabelId
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Deleting data from table SCore.EntityHobts
--
PRINT(N'Deleting data from table SCore.EntityHobts')
GO
DELETE SCore.EntityHobts WHERE ID = 172
DELETE SCore.EntityHobts WHERE ID = 173

--
-- Inserting data into table SCore.EntityHobts
--
PRINT(N'Inserting data into table SCore.EntityHobts')
GO
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
SET IDENTITY_INSERT SCore.EntityHobts ON
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
INSERT SCore.EntityHobts(ID, RowStatus, Guid, SchemaName, ObjectName, EntityTypeID, ObjectType, IsMainHoBT, IsReadOnlyOffline) VALUES (168, 1, 'd938d2c3-e975-4830-9d87-76c936f30c90', N'SFin', N'InvoiceAutomationRuns', 212, '', 0, 0)
INSERT SCore.EntityHobts(ID, RowStatus, Guid, SchemaName, ObjectName, EntityTypeID, ObjectType, IsMainHoBT, IsReadOnlyOffline) VALUES (169, 1, 'fbf9ae35-0145-4d75-8f70-56a71f6daf1e', N'SFin', N'InvoiceAutomationRunDetails', 213, '', 0, 0)
GO
SET IDENTITY_INSERT SCore.EntityHobts OFF
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Reseed identity on SCore.EntityHobts
--
PRINT(N'Reseed identity on SCore.EntityHobts')
GO
DBCC CHECKIDENT('SCore.EntityHobts', RESEED, 169)
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Updating data of table SCore.EntityProperties
--
PRINT(N'Updating data of table SCore.EntityProperties')
GO
UPDATE SCore.EntityProperties SET IsImmutable = 0 WHERE ID = 489
UPDATE SCore.EntityProperties SET SortOrder = 4 WHERE ID = 1672

--
-- Inserting data into table SCore.EntityProperties
--
PRINT(N'Inserting data into table SCore.EntityProperties')
GO
SET IDENTITY_INSERT SCore.EntityProperties ON
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
INSERT SCore.EntityProperties(ID, RowStatus, Guid, Name, LanguageLabelID, EntityHoBTID, EntityDataTypeID, IsReadOnly, IsImmutable, IsUppercase, IsHidden, IsCompulsory, MaxLength, Precision, Scale, DoNotTrackChanges, EntityPropertyGroupID, SortOrder, GroupSortOrder, IsObjectLabel, DropDownListDefinitionID, IsParentRelationship, IsLongitude, IsLatitude, IsIncludedInformation, FixedDefaultValue, SqlDefaultValueStatement, AllowBulkChange, IsVirtual, ShowOnMobile, IsAlwaysVisibleInGroup, IsAlwaysVisibleInGroup_Mobile) VALUES (2589, 1, '83972bf7-cb9a-4d9d-bc18-15baa4d5ea95', N'RIBAStageId', 3783, 116, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 45, 0, 0, 0, 0, N'', N'', 0, 0, 0, 0, 0)
INSERT SCore.EntityProperties(ID, RowStatus, Guid, Name, LanguageLabelID, EntityHoBTID, EntityDataTypeID, IsReadOnly, IsImmutable, IsUppercase, IsHidden, IsCompulsory, MaxLength, Precision, Scale, DoNotTrackChanges, EntityPropertyGroupID, SortOrder, GroupSortOrder, IsObjectLabel, DropDownListDefinitionID, IsParentRelationship, IsLongitude, IsLatitude, IsIncludedInformation, FixedDefaultValue, SqlDefaultValueStatement, AllowBulkChange, IsVirtual, ShowOnMobile, IsAlwaysVisibleInGroup, IsAlwaysVisibleInGroup_Mobile) VALUES (2597, 1, 'cd8ed008-65d3-45a0-846b-810da10826a2', N'InvoiceProcessingMode', 3791, 9, 8, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, -1, 0, 0, 0, 0, N'', N'1', 0, 0, 0, 0, 0)
INSERT SCore.EntityProperties(ID, RowStatus, Guid, Name, LanguageLabelID, EntityHoBTID, EntityDataTypeID, IsReadOnly, IsImmutable, IsUppercase, IsHidden, IsCompulsory, MaxLength, Precision, Scale, DoNotTrackChanges, EntityPropertyGroupID, SortOrder, GroupSortOrder, IsObjectLabel, DropDownListDefinitionID, IsParentRelationship, IsLongitude, IsLatitude, IsIncludedInformation, FixedDefaultValue, SqlDefaultValueStatement, AllowBulkChange, IsVirtual, ShowOnMobile, IsAlwaysVisibleInGroup, IsAlwaysVisibleInGroup_Mobile) VALUES (2598, 1, '258645d7-7d1e-4cc8-8e73-440db6aecbd5', N'ManualInvoicingEnabled', 3792, 9, 4, 0, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 0, -1, 0, 0, 0, 0, N'', N'', 0, 0, 0, 0, 0)
INSERT SCore.EntityProperties(ID, RowStatus, Guid, Name, LanguageLabelID, EntityHoBTID, EntityDataTypeID, IsReadOnly, IsImmutable, IsUppercase, IsHidden, IsCompulsory, MaxLength, Precision, Scale, DoNotTrackChanges, EntityPropertyGroupID, SortOrder, GroupSortOrder, IsObjectLabel, DropDownListDefinitionID, IsParentRelationship, IsLongitude, IsLatitude, IsIncludedInformation, FixedDefaultValue, SqlDefaultValueStatement, AllowBulkChange, IsVirtual, ShowOnMobile, IsAlwaysVisibleInGroup, IsAlwaysVisibleInGroup_Mobile) VALUES (2599, 1, '7c737459-c141-4f03-bafb-c05d386d70e3', N'RIBAStageId', 3793, 34, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 41, 0, 0, 0, 45, 0, 0, 0, 0, N'', N'', 0, 0, 0, 0, 0)
GO
SET IDENTITY_INSERT SCore.EntityProperties OFF
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Reseed identity on SCore.EntityProperties
--
PRINT(N'Reseed identity on SCore.EntityProperties')
GO
DBCC CHECKIDENT('SCore.EntityProperties', RESEED, 2599)
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Updating data of table SCore.EntityQueries
--
PRINT(N'Updating data of table SCore.EntityQueries')
GO
UPDATE SCore.EntityQueries SET Statement = N'SELECT
        root_hobt.ID,
        root_hobt.RowStatus,
        root_hobt.RowVersion,
        root_hobt.Guid,
        root_hobt.AgreedFee,
        root_hobt.RibaStage1Fee,
        root_hobt.RibaStage2Fee,
        root_hobt.RibaStage3Fee,
        root_hobt.RibaStage4Fee,
        root_hobt.RibaStage5Fee,
        root_hobt.RibaStage6Fee,
        root_hobt.RibaStage7Fee,
        root_hobt.PreConstructionStageFee,
        root_hobt.ConstructionStageFee,
        root_hobt.ArchiveBoxReference,
        root_hobt.ArchiveReferenceLink,
        root_hobt.CreatedOn,
        root_hobt.ExternalReference,
        root_hobt.IsSubjectToNDA,
        root_hobt.JobCancelled,
        root_hobt.JobCompleted,
        root_hobt.JobDescription,
        root_hobt.JobStarted,
		root_hobt.DeadDate,
        root_hobt.Number,
        root_hobt.VersionID,
        root_hobt.IsCompleteForReview,
        root_hobt.ReviewedDateTimeUTC,
        root_hobt.LegacyID,
        root_hobt.AppFormReceived,
        root_hobt.FeeCap,
        root_hobt.JobDormant,
        root_hobt.CurrentRibaStageId,
        root_hobt.JobTypeID,
        root_hobt.SurveyorID,
        root_hobt.CreatedByUserID,
        root_hobt.ClientAccountID,
        root_hobt.ClientAddressID,
        root_hobt.ClientContactID,
        root_hobt.AgentAccountID,
        root_hobt.AgentAddressID,
        root_hobt.AgentContactID,
        root_hobt.FinanceAccountID,
        root_hobt.FinanceAddressID,
        root_hobt.FinanceContactID,
        root_hobt.OrganisationalUnitID,
        root_hobt.QuoteItemID,
        root_hobt.UprnID,
        root_hobt.ValueOfWorkID,
        root_hobt.ReviewedByUserID,
        root_hobt.ContractID,
        root_hobt.PurchaseOrderNumber,
        root_hobt.ProjectId,
        root_hobt.ValueOfWork,
        root_hobt.ClientAppointmentReceived,
	root_hobt.AppointedFromStageId,
        root_hobt.BillingInstruction,
        root_hobt.CannotBeInvoiced,
	root_hobt.CannotBeInvoicedReason,
        root_hobt.AgentContractID,
        root_hobt.CompletedForReviewDate,
        root_hobt.SectorId,
        root_hobt.MarketId,
        root_hobt.ManualInvoicingEnabled,
        root_hobt.InvoiceProcessingMode
FROM
        SJob.Jobs_Read AS root_hobt' WHERE ID = 30
UPDATE SCore.EntityQueries SET Statement = N'SELECT	root_hobt.ID,
		root_hobt.RowStatus,
		root_hobt.RowVersion,
		root_hobt.Guid,
		tt.Guid	 AS TransactionTypeID,
		a.Guid	 AS AccountID,
		j.Guid	 AS JobID,
		root_hobt.Number,
		root_hobt.SageTransactionReference,
		root_hobt.Date,
		root_hobt.PurchaseOrderNumber,
		root_hobt.LegacyId,
		root_hobt.CreatedDateTimeUTC,
		root_hobt.Batched,
		ou.Guid AS OrganisationalUnitID,
		cu.Guid AS CreatedByUserID,
		i.Guid AS SurveyorUserID,
		ct.Guid AS CreditTermsId
FROM	SFin.Transactions	  AS root_hobt
JOIN	SFin.TransactionTypes AS tt ON (tt.ID = root_hobt.TransactionTypeID)
JOIN	SCrm.Accounts		  AS a ON (a.ID	  = root_hobt.AccountID)
JOIN	SJob.Jobs			  AS j ON (j.ID	  = root_hobt.JobID)
JOIN	SCore.OrganisationalUnits AS ou ON (ou.ID = root_hobt.OrganisationalUnitID)
JOIN	SCore.Identities cu ON (cu.ID = root_hobt.CreatedByUserID)
JOIN	SCore.Identities i ON (i.ID = root_hobt.SurveyorUserID)
JOIN	SFin.CreditTerms ct ON (ct.ID = root_hobt.CreditTermsId)' WHERE ID = 96
UPDATE SCore.EntityQueries SET Statement = N'EXEC SFin.TransactionsUpsert @AccountGuid = @AccountGuid,
							 @JobGuid = @JobGuid,
							 @TransactionTypeGuid = @TransactionTypeGuid,
							 @Date = @Date,
							 @PurchaseOrderNumber = @PurchaseOrderNumber,
							 @SageTransactionReference = @SageTransactionReference,
							 @OrganisationalUnitGuid = @OrganisationalUnitGuid,
							 @CreatedByUserGuid = @CreatedByUserGuid,
							 @SurveyorGuid = @SurveyorGuid,
							 @CreditTermsGuid = @CreditTermsGuid,
							 @Guid = @Guid,
                                                         @Batched = @Batched' WHERE ID = 98
UPDATE SCore.EntityQueries SET Statement = N'SELECT
		root_hobt.ID,
		root_hobt.RowStatus,
		root_hobt.RowVersion,
		root_hobt.Guid,
		t.Guid AS TransactionID,
		m.Guid AS MilestoneID,
		a.Guid AS ActivityID,
		riba.Guid AS RIBAStageId,
		jps.Guid AS JobPaymentStageId,
		root_hobt.Net,
		root_hobt.Vat,
		root_hobt.Gross,
		root_hobt.VatRate,
		root_hobt.Description,
		root_hobt.LegacyId
		
FROM
		SFin.TransactionDetails root_hobt
JOIN
		SFin.Transactions t ON (t.ID = root_hobt.TransactionID)
JOIN
		SJob.Milestones m ON (m.ID = root_hobt.MilestoneID)
JOIN
		SJob.Activities a ON (a.ID = root_hobt.ActivityID)
JOIN	
		SJob.JobPaymentStages jps ON jps.ID = root_hobt.JobPaymentStageId
JOIN
		SJob.RibaStages riba ON (riba.ID = root_hobt.RIBAStageId)' WHERE ID = 188
UPDATE SCore.EntityQueries SET Statement = N'SELECT * FROM [SFin].[TransactionsValidate] ( @Guid, @AccountGuid, @TransactionTypeGuid, @Batched) root_hobt' WHERE ID = 201
UPDATE SCore.EntityQueries SET Statement = N'SELECT 
	root_hobt.AutomationRunGuid,
	root_hobt.BlockedReason,
	root_hobt.CreatedDateTimeUTC,
	root_hobt.ExpectedDate,
	root_hobt.Guid,
	root_hobt.ID,
	root_hobt.InvoiceBatchGuid,
	[58ABEA42-8199-4DC5-87A8-C71687406B76].Guid AS InvoicePaymentStatusID,
	root_hobt.InvoicingType,
	root_hobt.IsAutomated,
	root_hobt.IsZeroValuePlaceholder,
	[DDDABD42-C753-48FA-800F-A73C88FCADCD].Guid AS JobId,
	root_hobt.LegacyId,
	root_hobt.LegacySystemID,
	root_hobt.ManualStatus,
	root_hobt.Notes,
	root_hobt.ReconciliationReason,
	root_hobt.ReconciliationRequired,
	[8C1F4236-36A8-44ED-AF70-C43F56840943].Guid AS RequesterUserId,
	root_hobt.RowStatus,
	root_hobt.RowVersion,
	root_hobt.SourceGuid,
	root_hobt.SourceIntId,
	root_hobt.SourceType,
	[158D0B3F-378F-45C6-B8A6-1480EA1880B3].Guid As FinanceAccountGuid
FROM SFin.InvoiceRequests AS root_hobt 
JOIN SCore.Identities AS [8C1F4236-36A8-44ED-AF70-C43F56840943] ON ([8C1F4236-36A8-44ED-AF70-C43F56840943].ID = root_hobt.RequesterUserId) 
 JOIN SJob.Jobs AS [DDDABD42-C753-48FA-800F-A73C88FCADCD] ON ([DDDABD42-C753-48FA-800F-A73C88FCADCD].ID = root_hobt.JobId) 
 JOIN SCrm.Accounts AS [158D0B3F-378F-45C6-B8A6-1480EA1880B3] ON ([158D0B3F-378F-45C6-B8A6-1480EA1880B3].ID = [DDDABD42-C753-48FA-800F-A73C88FCADCD].FinanceAccountID) 
 JOIN SFin.InvoicePaymentStatus AS [58ABEA42-8199-4DC5-87A8-C71687406B76] ON ([58ABEA42-8199-4DC5-87A8-C71687406B76].ID = root_hobt.InvoicePaymentStatusID)

' WHERE ID = 258
UPDATE SCore.EntityQueries SET Statement = N'EXEC [SFin].[InvoiceRequestUpsert]  
	@JobGuid = @JobGuid, 
	@RequesterUserGuid = @RequesterUserGuid, 
	@Notes = @Notes, 
	@Guid = @Guid, 
	@InvoicingType = @InvoicingType, 
	@ExpectedDate = @ExpectedDate, 
	@ManualStatus = @ManualStatus, 
	@PaymentStatusGuid = @PaymentStatusGuid' WHERE ID = 259
UPDATE SCore.EntityQueries SET Statement = N'SELECT 
 [DF573724-6B25-4B0E-BCDA-061280F64A77].Guid AS ActivityId,
 root_hobt.Guid,
 root_hobt.ID,
 [395D9343-C3C2-4DD1-A20C-A254BA403724].Guid AS InvoiceRequestId,
 [96FB0CCD-A7BF-45F8-A3A6-23D70E4620F4].Guid AS MilestoneId,
 root_hobt.Net,
 root_hobt.RowStatus,
 root_hobt.RowVersion,
 root_hobt.ShortDescription,
 RibaStages.Guid AS RIBAStageId
FROM SFin.InvoiceRequestItems AS root_hobt 
JOIN SFin.InvoiceRequests AS [395D9343-C3C2-4DD1-A20C-A254BA403724] ON ([395D9343-C3C2-4DD1-A20C-A254BA403724].ID = root_hobt.InvoiceRequestId) 
 JOIN SJob.Milestones AS [96FB0CCD-A7BF-45F8-A3A6-23D70E4620F4] ON ([96FB0CCD-A7BF-45F8-A3A6-23D70E4620F4].ID = root_hobt.MilestoneId) 
 JOIN SJob.Activities AS [DF573724-6B25-4B0E-BCDA-061280F64A77] ON ([DF573724-6B25-4B0E-BCDA-061280F64A77].ID = root_hobt.ActivityId) 
 JOIN SJob.RibaStages AS RibaStages ON (root_hobt.RIBAStageId = RibaStages.ID)' WHERE ID = 260
UPDATE SCore.EntityQueries SET Statement = N'EXEC [SFin].[InvoiceRequestItemsUpsert]  
	@InvoiceRequestGuid = @InvoiceRequestGuid, 
	@MilestoneGuid = @MilestoneGuid, 
	@ActivityGuid = @ActivityGuid, 
	@Net = @Net, 
	@Guid = @Guid, 
	@ShortDescription = @ShortDescription, 
	@RIBAStageGuid = @RIBAStageGuid' WHERE ID = 261

--
-- Inserting data into table SCore.EntityQueryParameters
--
PRINT(N'Inserting data into table SCore.EntityQueryParameters')
GO
SET IDENTITY_INSERT SCore.EntityQueryParameters ON
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
INSERT SCore.EntityQueryParameters(ID, RowStatus, Guid, Name, EntityQueryID, EntityDataTypeID, MappedEntityPropertyID, DefaultValue, IsInput, IsOutput, IsReturnColumn) VALUES (1591, 1, '77fb4c1e-69d2-4ad1-a33d-5a098f4d59bf', N'@RIBAStageGuid', 261, 6, 2589, N'', 1, 0, 0)
INSERT SCore.EntityQueryParameters(ID, RowStatus, Guid, Name, EntityQueryID, EntityDataTypeID, MappedEntityPropertyID, DefaultValue, IsInput, IsOutput, IsReturnColumn) VALUES (1592, 1, '400210af-3fff-459e-a945-208140902b2a', N'@Batched', 201, 4, 2588, N'', 1, 0, 0)
GO
SET IDENTITY_INSERT SCore.EntityQueryParameters OFF
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Reseed identity on SCore.EntityQueryParameters
--
PRINT(N'Reseed identity on SCore.EntityQueryParameters')
GO
DBCC CHECKIDENT('SCore.EntityQueryParameters', RESEED, 1592)
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Inserting data into table SCore.LanguageLabels
--
PRINT(N'Inserting data into table SCore.LanguageLabels')
GO
SET IDENTITY_INSERT SCore.LanguageLabels ON
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
INSERT SCore.LanguageLabels(ID, RowStatus, Guid, Name) VALUES (3783, 1, 'a46f958e-eaf5-41a2-98d9-cf47b4b87a8c', N'[SFin].[InvoiceRequestItems].[RIBAStageId]')
INSERT SCore.LanguageLabels(ID, RowStatus, Guid, Name) VALUES (3791, 1, 'd83ae491-dd18-44cb-b31c-4ea8e4fd9e71', N'SJob.Jobs.InvoiceProcessingMode')
INSERT SCore.LanguageLabels(ID, RowStatus, Guid, Name) VALUES (3792, 1, '7b930e3b-ea13-403b-a08f-c60daf65072a', N'SJob.Jobs.ManualInvoicingEnabled')
INSERT SCore.LanguageLabels(ID, RowStatus, Guid, Name) VALUES (3793, 1, 'd5f0f373-e058-459b-a7aa-dae716b604cc', N'[SFin].[TransactionDetails].[RIBAStageId]')
GO
SET IDENTITY_INSERT SCore.LanguageLabels OFF
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Reseed identity on SCore.LanguageLabels
--
PRINT(N'Reseed identity on SCore.LanguageLabels')
GO
DBCC CHECKIDENT('SCore.LanguageLabels', RESEED, 3793)
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Updating data of table SCore.LanguageLabelTranslations
--
PRINT(N'Updating data of table SCore.LanguageLabelTranslations')
GO
UPDATE SCore.LanguageLabelTranslations SET Text = N'Approve Invoice(s)', TextPlural = N'Approve Invoice(s)' WHERE ID = 3892

--
-- Inserting data into table SCore.LanguageLabelTranslations
--
PRINT(N'Inserting data into table SCore.LanguageLabelTranslations')
GO
SET IDENTITY_INSERT SCore.LanguageLabelTranslations ON
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
INSERT SCore.LanguageLabelTranslations(ID, RowStatus, Guid, Text, TextPlural, LanguageLabelID, LanguageID, HelpText) VALUES (3894, 1, '4ef4492b-e189-416a-be79-3397d346a009', N'RIBA Stage', N'RIBA Stage', 3783, 1, N'')
INSERT SCore.LanguageLabelTranslations(ID, RowStatus, Guid, Text, TextPlural, LanguageLabelID, LanguageID, HelpText) VALUES (3902, 1, '09325f6d-e2aa-4c38-87a2-76e99df37f18', N'InvoiceProcessingMode', N'InvoiceProcessingMode', 3791, 1, N'')
INSERT SCore.LanguageLabelTranslations(ID, RowStatus, Guid, Text, TextPlural, LanguageLabelID, LanguageID, HelpText) VALUES (3903, 1, '06f2ac46-0a6f-4270-b505-1548c9575a8b', N'ManualInvoicingMode', N'ManualInvoicingMode', 3792, 1, N'')
INSERT SCore.LanguageLabelTranslations(ID, RowStatus, Guid, Text, TextPlural, LanguageLabelID, LanguageID, HelpText) VALUES (3904, 1, '43a0a884-6cd8-4819-895f-94d9b339cd83', N'RIBA Stage', N'RIBA Stage', 3793, 1, N'')
GO
SET IDENTITY_INSERT SCore.LanguageLabelTranslations OFF
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Reseed identity on SCore.LanguageLabelTranslations
--
PRINT(N'Reseed identity on SCore.LanguageLabelTranslations')
GO
DBCC CHECKIDENT('SCore.LanguageLabelTranslations', RESEED, 3904)
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Updating data of table SUserInterface.DropDownListDefinitions
--
PRINT(N'Updating data of table SUserInterface.DropDownListDefinitions')
GO
UPDATE SUserInterface.DropDownListDefinitions SET SqlQuery = N'SELECT 
    root_hobt.Guid,
    root_hobt.FullName AS Name
FROM SCore.Identities AS root_hobt
WHERE root_hobt.OriganisationalUnitId = (
    SELECT OriganisationalUnitId
    FROM SCore.Identities
    WHERE ID = [[UserId]]
)
AND root_hobt.IsActive = 1' WHERE ID = 112

--
-- Inserting data into table SUserInterface.GridViewColumnDefinitions
--
PRINT(N'Inserting data into table SUserInterface.GridViewColumnDefinitions')
GO
SET IDENTITY_INSERT SUserInterface.GridViewColumnDefinitions ON
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
INSERT SUserInterface.GridViewColumnDefinitions(ID, RowStatus, Guid, Name, ColumnOrder, GridViewDefinitionId, IsPrimaryKey, IsHidden, IsFiltered, IsCombo, IsLongitude, IsLatitude, DisplayFormat, Width, LanguageLabelId, TopHeaderCategory, TopHeaderCategoryOrder) VALUES (1620, 1, '45205fb0-fa36-4266-8802-3ec53c163b39', N'ID', 999, 237, 1, 1, 1, 0, 0, 0, N'', N'', 1627, N'', 0)
INSERT SUserInterface.GridViewColumnDefinitions(ID, RowStatus, Guid, Name, ColumnOrder, GridViewDefinitionId, IsPrimaryKey, IsHidden, IsFiltered, IsCombo, IsLongitude, IsLatitude, DisplayFormat, Width, LanguageLabelId, TopHeaderCategory, TopHeaderCategoryOrder) VALUES (1621, 1, '26c23aa8-ca89-463a-bf6f-61aa8e177e18', N'Guid', 0, 237, 0, 1, 0, 0, 0, 0, N'', N'', 1689, N'', 0)
INSERT SUserInterface.GridViewColumnDefinitions(ID, RowStatus, Guid, Name, ColumnOrder, GridViewDefinitionId, IsPrimaryKey, IsHidden, IsFiltered, IsCombo, IsLongitude, IsLatitude, DisplayFormat, Width, LanguageLabelId, TopHeaderCategory, TopHeaderCategoryOrder) VALUES (1623, 1, '0bd53b5e-ad14-4cc8-b611-8f54caa89f75', N'Number', 1, 237, 0, 0, 1, 0, 0, 0, N'', N'', 1070, N'', 0)
INSERT SUserInterface.GridViewColumnDefinitions(ID, RowStatus, Guid, Name, ColumnOrder, GridViewDefinitionId, IsPrimaryKey, IsHidden, IsFiltered, IsCombo, IsLongitude, IsLatitude, DisplayFormat, Width, LanguageLabelId, TopHeaderCategory, TopHeaderCategoryOrder) VALUES (1624, 1, 'd08badee-ba0b-494d-b5c7-c81a254c4ec7', N'Description', 2, 237, 0, 0, 1, 0, 0, 0, N'', N'', 3105, N'', 0)
INSERT SUserInterface.GridViewColumnDefinitions(ID, RowStatus, Guid, Name, ColumnOrder, GridViewDefinitionId, IsPrimaryKey, IsHidden, IsFiltered, IsCombo, IsLongitude, IsLatitude, DisplayFormat, Width, LanguageLabelId, TopHeaderCategory, TopHeaderCategoryOrder) VALUES (1625, 1, 'fac2bc3a-f9c7-4ae9-89a2-c8091bfeb66a', N'ClientAgent', 3, 237, 0, 0, 1, 0, 0, 0, N'', N'', 3106, N'', 0)
INSERT SUserInterface.GridViewColumnDefinitions(ID, RowStatus, Guid, Name, ColumnOrder, GridViewDefinitionId, IsPrimaryKey, IsHidden, IsFiltered, IsCombo, IsLongitude, IsLatitude, DisplayFormat, Width, LanguageLabelId, TopHeaderCategory, TopHeaderCategoryOrder) VALUES (1626, 1, 'bb80b37e-f31c-4f34-8975-ba7d72ed59ab', N'ExternalReference', 4, 237, 0, 0, 1, 0, 0, 0, N'', N'', 1327, N'', 0)
INSERT SUserInterface.GridViewColumnDefinitions(ID, RowStatus, Guid, Name, ColumnOrder, GridViewDefinitionId, IsPrimaryKey, IsHidden, IsFiltered, IsCombo, IsLongitude, IsLatitude, DisplayFormat, Width, LanguageLabelId, TopHeaderCategory, TopHeaderCategoryOrder) VALUES (1627, 1, '2bb201f7-f2bb-48e1-a358-7a406dbacec8', N'JobTypeName', 5, 237, 0, 0, 0, 0, 0, 0, N'', N'', 3109, N'', 0)
INSERT SUserInterface.GridViewColumnDefinitions(ID, RowStatus, Guid, Name, ColumnOrder, GridViewDefinitionId, IsPrimaryKey, IsHidden, IsFiltered, IsCombo, IsLongitude, IsLatitude, DisplayFormat, Width, LanguageLabelId, TopHeaderCategory, TopHeaderCategoryOrder) VALUES (1628, 1, 'd1e9f39a-d7ac-4982-89df-00e37c86368d', N'CreatedOn', 6, 237, 0, 0, 0, 0, 0, 0, N'', N'', 3110, N'', 0)
INSERT SUserInterface.GridViewColumnDefinitions(ID, RowStatus, Guid, Name, ColumnOrder, GridViewDefinitionId, IsPrimaryKey, IsHidden, IsFiltered, IsCombo, IsLongitude, IsLatitude, DisplayFormat, Width, LanguageLabelId, TopHeaderCategory, TopHeaderCategoryOrder) VALUES (1629, 1, 'f691d8d6-727a-4c09-a79b-cdf38165ddd8', N'RowStatus', 0, 237, 0, 1, 0, 0, 0, 0, N'', N'', 1064, N'', 0)
GO
SET IDENTITY_INSERT SUserInterface.GridViewColumnDefinitions OFF
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Reseed identity on SUserInterface.GridViewColumnDefinitions
--
PRINT(N'Reseed identity on SUserInterface.GridViewColumnDefinitions')
GO
DBCC CHECKIDENT('SUserInterface.GridViewColumnDefinitions', RESEED, 1629)
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Updating data of table SUserInterface.GridViewDefinitions
--
PRINT(N'Updating data of table SUserInterface.GridViewDefinitions')
GO
UPDATE SUserInterface.GridViewDefinitions SET DefaultSortColumnName = N'ID' WHERE ID = 190
UPDATE SUserInterface.GridViewDefinitions SET SqlQuery = N'SELECT
 *
FROM
      [SFin].[tvf_AutomatedInvoicing]([[UserId]]) root_hobt' WHERE ID = 215

--
-- Inserting data into table SUserInterface.GridViewDefinitions
--
PRINT(N'Inserting data into table SUserInterface.GridViewDefinitions')
GO
SET IDENTITY_INSERT SUserInterface.GridViewDefinitions ON
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
INSERT SUserInterface.GridViewDefinitions(ID, RowStatus, Guid, Code, GridDefinitionId, DetailPageUri, SqlQuery, DefaultSortColumnName, SecurableCode, DisplayOrder, DisplayGroupName, MetricSqlQuery, ShowMetric, IsDetailWindowed, EntityTypeID, MetricTypeID, MetricMin, MetricMax, MetricMinorUnit, MetricMajorUnit, MetricStartAngle, MetricEndAngle, MetricReversed, MetricRange1Min, MetricRange1Max, MetricRange1ColourHex, MetricRange2Min, MetricRange2Max, MetricRange2ColourHex, IsDefaultSortDescending, AllowNew, AllowExcelExport, AllowPdfExport, AllowCsvExport, LanguageLabelId, DrawerIconId, GridViewTypeId, AllowBulkChange, ShowOnMobile, TreeListFirstOrderBy, TreeListSecondOrderBy, TreeListThirdOrderBy, TreeListOrderBy, TreeListGroupBy, ShowOnDashboard, FilteredListCreatedOnColumn, FilteredListRedStatusIndicatorTxt, FilteredListOrangeStatusIndicatorTxt, FilteredListGreenStatusIndicatorTxt, FilteredListGroupBy) VALUES (237, 1, '50f6e3b3-9f2b-47fb-aafa-4612407e7de8', N'APPROVEDENQUIRIES', 67, N'EnquiryDetail', N'SELECT  * 
FROM [SSop].[tvf_ApprovedEnquiries] ([[UserId]]) root_hobt', N'ID', N'', 0, N'', N'', 0, 0, 83, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0, N'', 0, 0, N'', 1, 0, 0, 0, 0, 3782, 5, 1, 0, 0, N'', N'', N'', N'', N'', 0, N'', N'', N'', N'', N'')
GO
SET IDENTITY_INSERT SUserInterface.GridViewDefinitions OFF
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Reseed identity on SUserInterface.GridViewDefinitions
--
PRINT(N'Reseed identity on SUserInterface.GridViewDefinitions')
GO
DBCC CHECKIDENT('SUserInterface.GridViewDefinitions', RESEED, 237)
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityHobts]
--
PRINT(N'Creating constraints for [SCore].[EntityHobts]')
GO
ALTER TABLE SCore.EntityHobts WITH NOCHECK
  ADD CONSTRAINT FK_EntityHoBTs_EntityTypes FOREIGN KEY (EntityTypeID) REFERENCES SCore.EntityTypes(ID) ON DELETE CASCADE ON UPDATE NO ACTION
ALTER TABLE SCore.EntityHobts WITH NOCHECK
  ADD CONSTRAINT FK_EntityHobts_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityProperties]
--
PRINT(N'Creating constraints for [SCore].[EntityProperties]')
GO
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_DropDownListDefinitions FOREIGN KEY (DropDownListDefinitionID) REFERENCES SUserInterface.DropDownListDefinitions(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_EntityDataTypes FOREIGN KEY (EntityDataTypeID) REFERENCES SCore.EntityDataTypes(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_EntityHoBTs FOREIGN KEY (EntityHoBTID) REFERENCES SCore.EntityHobts(ID) ON DELETE CASCADE ON UPDATE NO ACTION
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_EntityPropertyGroupID FOREIGN KEY (EntityPropertyGroupID) REFERENCES SCore.EntityPropertyGroups(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_LanguageLabels FOREIGN KEY (LanguageLabelID) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityQueries]
--
PRINT(N'Creating constraints for [SCore].[EntityQueries]')
GO
ALTER TABLE SCore.EntityQueries WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueries_EntityHoBTs FOREIGN KEY (EntityHoBTID) REFERENCES SCore.EntityHobts(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityQueries WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueries_EntityTypes FOREIGN KEY (EntityTypeID) REFERENCES SCore.EntityTypes(ID) ON DELETE CASCADE ON UPDATE NO ACTION
ALTER TABLE SCore.EntityQueries WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueries_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityQueryParameters]
--
PRINT(N'Creating constraints for [SCore].[EntityQueryParameters]')
GO
ALTER TABLE SCore.EntityQueryParameters WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueryParameters_EntityDataTypes FOREIGN KEY (EntityDataTypeID) REFERENCES SCore.EntityDataTypes(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityQueryParameters WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueryParameters_EntityProperties FOREIGN KEY (MappedEntityPropertyID) REFERENCES SCore.EntityProperties(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityQueryParameters WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueryParameters_EntityQueries FOREIGN KEY (EntityQueryID) REFERENCES SCore.EntityQueries(ID) ON DELETE CASCADE ON UPDATE NO ACTION
ALTER TABLE SCore.EntityQueryParameters WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueryParameters_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[LanguageLabels]
--
PRINT(N'Creating constraints for [SCore].[LanguageLabels]')
GO
ALTER TABLE SCore.LanguageLabels WITH NOCHECK
  ADD CONSTRAINT FK_LanguageLabels_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[LanguageLabelTranslations]
--
PRINT(N'Creating constraints for [SCore].[LanguageLabelTranslations]')
GO
ALTER TABLE SCore.LanguageLabelTranslations WITH NOCHECK
  ADD CONSTRAINT FK_LanguageLabelTranslations_LanguageLabels FOREIGN KEY (LanguageLabelID) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.LanguageLabelTranslations WITH NOCHECK
  ADD CONSTRAINT FK_LanguageLabelTranslations_Languages FOREIGN KEY (LanguageID) REFERENCES SCore.Languages(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.LanguageLabelTranslations WITH NOCHECK
  ADD CONSTRAINT FK_LanguageLabelTranslations_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[DropDownListDefinitions]
--
PRINT(N'Creating constraints for [SUserInterface].[DropDownListDefinitions]')
GO
ALTER TABLE SUserInterface.DropDownListDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_DropDownListDefinitions_EntityTypes FOREIGN KEY (EntityTypeId) REFERENCES SCore.EntityTypes(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.DropDownListDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_DropDownListDefinitions_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridViewColumnDefinitions]
--
PRINT(N'Creating constraints for [SUserInterface].[GridViewColumnDefinitions]')
GO
ALTER TABLE SUserInterface.GridViewColumnDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewColumnDefinition_GridViewDefinition FOREIGN KEY (GridViewDefinitionId) REFERENCES SUserInterface.GridViewDefinitions(ID) ON DELETE CASCADE ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewColumnDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewColumnDefinitions_LanguageLabelId FOREIGN KEY (LanguageLabelId) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewColumnDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewColumnDefinitions_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridViewDefinitions]
--
PRINT(N'Creating constraints for [SUserInterface].[GridViewDefinitions]')
GO
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinition_GridDefinition FOREIGN KEY (GridDefinitionId) REFERENCES SUserInterface.GridDefinitions(ID) ON DELETE CASCADE ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_DrawerIconId FOREIGN KEY (DrawerIconId) REFERENCES SUserInterface.Icons(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_EntityTypes FOREIGN KEY (EntityTypeID) REFERENCES SCore.EntityTypes(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_LanguageLabelId FOREIGN KEY (LanguageLabelId) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_MetricTypes FOREIGN KEY (MetricTypeID) REFERENCES SUserInterface.MetricTypes(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[Workflow]
--
PRINT(N'Creating constraints for [SCore].[Workflow]')
GO
ALTER TABLE SCore.Workflow WITH NOCHECK
  ADD CONSTRAINT FK_Workflow_EntityHoBTs FOREIGN KEY (EntityHoBTID) REFERENCES SCore.EntityHobts(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityPropertyActions]
--
PRINT(N'Creating constraints for [SCore].[EntityPropertyActions]')
GO
ALTER TABLE SCore.EntityPropertyActions WITH NOCHECK
  ADD CONSTRAINT FK_EntityPropertyActions_EntityProperties FOREIGN KEY (EntityPropertyID) REFERENCES SCore.EntityProperties(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityPropertyDependants]
--
PRINT(N'Creating constraints for [SCore].[EntityPropertyDependants]')
GO
ALTER TABLE SCore.EntityPropertyDependants WITH NOCHECK
  ADD CONSTRAINT FK_EntityPropertyDependants_EntityProperties FOREIGN KEY (ParentEntityPropertyID) REFERENCES SCore.EntityProperties(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[MergeDocumentItemIncludes]
--
PRINT(N'Creating constraints for [SCore].[MergeDocumentItemIncludes]')
GO
ALTER TABLE SCore.MergeDocumentItemIncludes WITH NOCHECK
  ADD CONSTRAINT FK_MergeDocumentItemIncludes_EntityProperties FOREIGN KEY (SourceDocumentEntityPropertyId) REFERENCES SCore.EntityProperties(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[RecordHistory]
--
PRINT(N'Creating constraints for [SCore].[RecordHistory]')
GO
ALTER TABLE SCore.RecordHistory WITH NOCHECK
  ADD CONSTRAINT FK_RecordHistory_EntityPropertyID FOREIGN KEY (EntityPropertyID) REFERENCES SCore.EntityProperties(ID) ON DELETE CASCADE ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[SynchronisationErrors]
--
PRINT(N'Creating constraints for [SCore].[SynchronisationErrors]')
GO
ALTER TABLE SCore.SynchronisationErrors WITH NOCHECK
  ADD CONSTRAINT FK_SychronisationErrors_EntityPropertyID FOREIGN KEY (EntityPropertyID) REFERENCES SCore.EntityProperties(ID) ON DELETE CASCADE ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[ActionMenuItems]
--
PRINT(N'Creating constraints for [SUserInterface].[ActionMenuItems]')
GO
ALTER TABLE SUserInterface.ActionMenuItems WITH NOCHECK
  ADD CONSTRAINT FK_ActionMenuItems_EntityQueries FOREIGN KEY (EntityQueryId) REFERENCES SCore.EntityQueries(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridViewActions]
--
PRINT(N'Creating constraints for [SUserInterface].[GridViewActions]')
GO
ALTER TABLE SUserInterface.GridViewActions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewActions_EntityQueries FOREIGN KEY (EntityQueryId) REFERENCES SCore.EntityQueries(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridViewWidgetQueries]
--
PRINT(N'Creating constraints for [SUserInterface].[GridViewWidgetQueries]')
GO
ALTER TABLE SUserInterface.GridViewWidgetQueries WITH NOCHECK
  ADD CONSTRAINT FK_GridViewWidgetQueries_EntityQueries FOREIGN KEY (EntityQueryId) REFERENCES SCore.EntityQueries(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityPropertyGroups]
--
PRINT(N'Creating constraints for [SCore].[EntityPropertyGroups]')
GO
ALTER TABLE SCore.EntityPropertyGroups WITH NOCHECK
  ADD CONSTRAINT FK_EntityPropertyGroups_LanguageLabels FOREIGN KEY (LanguageLabelID) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityTypes]
--
PRINT(N'Creating constraints for [SCore].[EntityTypes]')
GO
ALTER TABLE SCore.EntityTypes WITH NOCHECK
  ADD CONSTRAINT FK_EntityTypes_LanguageLabels FOREIGN KEY (LanguageLabelID) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridDefinitions]
--
PRINT(N'Creating constraints for [SUserInterface].[GridDefinitions]')
GO
ALTER TABLE SUserInterface.GridDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridDefinitions_LanguageLabelId FOREIGN KEY (LanguageLabelId) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[MainMenuItems]
--
PRINT(N'Creating constraints for [SUserInterface].[MainMenuItems]')
GO
ALTER TABLE SUserInterface.MainMenuItems WITH NOCHECK
  ADD CONSTRAINT FK_MainMenuItems_LanguageLabelId FOREIGN KEY (LanguageLabelId) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Enabling DML triggers for [SCore].[EntityHobts]
--
PRINT(N'Enabling DML triggers for [SCore].[EntityHobts]')
GO
ENABLE TRIGGER ALL ON SCore.EntityHobts
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Enabling DML triggers for [SCore].[EntityProperties]
--
PRINT(N'Enabling DML triggers for [SCore].[EntityProperties]')
GO
ENABLE TRIGGER ALL ON SCore.EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Enabling DML triggers for [SCore].[EntityQueries]
--
PRINT(N'Enabling DML triggers for [SCore].[EntityQueries]')
GO
ENABLE TRIGGER ALL ON SCore.EntityQueries
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Enabling DML triggers for [SCore].[EntityQueryParameters]
--
PRINT(N'Enabling DML triggers for [SCore].[EntityQueryParameters]')
GO
ENABLE TRIGGER ALL ON SCore.EntityQueryParameters
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Enabling DML triggers for [SCore].[LanguageLabels]
--
PRINT(N'Enabling DML triggers for [SCore].[LanguageLabels]')
GO
ENABLE TRIGGER ALL ON SCore.LanguageLabels
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Enabling DML triggers for [SCore].[LanguageLabelTranslations]
--
PRINT(N'Enabling DML triggers for [SCore].[LanguageLabelTranslations]')
GO
ENABLE TRIGGER ALL ON SCore.LanguageLabelTranslations
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Enabling DML triggers for [SUserInterface].[DropDownListDefinitions]
--
PRINT(N'Enabling DML triggers for [SUserInterface].[DropDownListDefinitions]')
GO
ENABLE TRIGGER ALL ON SUserInterface.DropDownListDefinitions
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END


--
-- Commit Transaction
--
PRINT(N'Commit Transaction')
GO
IF @@TRANCOUNT>0 COMMIT TRANSACTION
SET NOEXEC OFF
GO