--
-- Script was generated by Devart dbForge Data Compare for SQL Server, Version 2025.2.37.0
-- Product Home Page: https://www.devart.com/dbforge/sql/datacompare
-- Script date 10/12/2025 15:58:21
-- Source server version: 16.00.1000
-- Source connection string: Data Source=soc-sqldevbre01.esgl.co.uk\General;Integrated Security=True;User ID=ESGL\Richard.Brindley
-- Target server version: 16.00.0000
-- Run this script against Schema to synchronize it with Concursus_Dev
-- Please backup your target database before running this script
--

SET LANGUAGE 'English'
SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT, XACT_ABORT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS OFF
GO


--
-- Start Transaction
--
BEGIN TRANSACTION

--
-- Dropping constraints from [SCore].[LanguageLabelTranslations]
--
ALTER TABLE SCore.LanguageLabelTranslations
  DROP CONSTRAINT IF EXISTS FK_LanguageLabelTranslations_LanguageLabels
ALTER TABLE SCore.LanguageLabelTranslations
  DROP CONSTRAINT IF EXISTS FK_LanguageLabelTranslations_Languages
ALTER TABLE SCore.LanguageLabelTranslations
  DROP CONSTRAINT IF EXISTS FK_LanguageLabelTranslations_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[LanguageLabels]
--
ALTER TABLE SCore.LanguageLabels
  DROP CONSTRAINT IF EXISTS FK_LanguageLabels_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridViewDefinitions]
--
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinition_GridDefinition
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_DrawerIconId
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_EntityTypes
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_LanguageLabelId
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_MetricTypes
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridDefinitions]
--
ALTER TABLE SUserInterface.GridDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridDefinitions_LanguageLabelId
ALTER TABLE SUserInterface.GridDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridDefinitions_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityProperties]
--
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_LanguageLabels
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityPropertyGroups]
--
ALTER TABLE SCore.EntityPropertyGroups
  DROP CONSTRAINT IF EXISTS FK_EntityPropertyGroups_LanguageLabels
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityTypes]
--
ALTER TABLE SCore.EntityTypes
  DROP CONSTRAINT IF EXISTS FK_EntityTypes_LanguageLabels
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[ActionMenuItems]
--
ALTER TABLE SUserInterface.ActionMenuItems
  DROP CONSTRAINT IF EXISTS FK_ActionMenuItems_LanguageLabels
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridViewActions]
--
ALTER TABLE SUserInterface.GridViewActions
  DROP CONSTRAINT IF EXISTS FK_GridViewActions_LanguageLabelId
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridViewColumnDefinitions]
--
ALTER TABLE SUserInterface.GridViewColumnDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewColumnDefinitions_LanguageLabelId
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridViewWidgetQueries]
--
ALTER TABLE SUserInterface.GridViewWidgetQueries
  DROP CONSTRAINT IF EXISTS FK_GridViewWidgetQueries_LanguageLabels
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[MainMenuItems]
--
ALTER TABLE SUserInterface.MainMenuItems
  DROP CONSTRAINT IF EXISTS FK_MainMenuItems_LanguageLabelId
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Inserting data into table [SCore].[LanguageLabelTranslations]
--
SET IDENTITY_INSERT SCore.LanguageLabelTranslations ON
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
INSERT SCore.LanguageLabelTranslations(ID, RowStatus, Guid, Text, TextPlural, LanguageLabelID, LanguageID, HelpText) VALUES (3354, 1, '81e7fa12-f6d1-4742-b745-971465b963e7', N'Invoicing', N'Invoicing', 3326, 1, N'')
GO
SET IDENTITY_INSERT SCore.LanguageLabelTranslations OFF
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Reseed identity on SCore.LanguageLabelTranslations
--
DBCC CHECKIDENT('SCore.LanguageLabelTranslations', RESEED, 3354)
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Inserting data into table [SCore].[LanguageLabels]
--
SET IDENTITY_INSERT SCore.LanguageLabels ON
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END
INSERT SCore.LanguageLabels(ID, RowStatus, Guid, Name) VALUES (3326, 1, '4e000da7-5eeb-4037-8239-9ef9a96a2923', N'Invoicing')
GO
SET IDENTITY_INSERT SCore.LanguageLabels OFF
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Reseed identity on SCore.LanguageLabels
--
DBCC CHECKIDENT('SCore.LanguageLabels', RESEED, 3326)
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Updating data of table [SUserInterface].[GridViewDefinitions]
--
UPDATE SUserInterface.GridViewDefinitions SET SqlQuery = N'SELECT	ID,
		RowStatus,
		RowVersion,
		Guid,
		Number,
		ExternalReference,
		DescriptionOfWorks,
		Account,
                ClientAgentAccount,
                Property,
                EnquiryStatus,
                Disciplines,
                Date,
                OrgUnit,
                Deadline
FROM	SSop.tvf_EnquiriesForQuoteReview([[UserId]]) root_hobt' WHERE ID = 101
UPDATE SUserInterface.GridViewDefinitions SET SqlQuery = N'SELECT
     root_hobt.ID,
     root_hobt.RowStatus,
     root_hobt.Guid,
     root_hobt.Notes,
     root_hobt.CreatedDateTimeUTC,
     root_hobt.RequesterUserId,
     root_hobt.JobId,
     root_hobt.SurveyorName,
     root_hobt.Number,
     root_hobt.FinanceAccountID,
     -- [CBLD-522]
     root_hobt.ActivityId,               
    -- [CBLD-525]
     root_hobt.ClientName,
     root_hobt.Net,
     root_hobt.EndDate,
     root_hobt.JobBillingInstruction,
     root_hobt.CRMBillingInstruction,
     root_hobt.IsBillable,
     root_hobt.OrgUnit
FROM
      [SFin].[tvf_InvoiceRequests]([[UserId]]) root_hobt' WHERE ID = 168
UPDATE SUserInterface.GridViewDefinitions SET MetricSqlQuery = N'SELECT	CONVERT(DECIMAL(9,2), COUNT(1)) AS MetricValue1, 
		N''#ff0000'' Value1ColourHex, 
		CONVERT(DECIMAL(9,2), 0) AS MetricValue2, 
		N''#0000FF'' Value2ColourHex 
FROM	SSop.tvf_ClosedEnquiries([[UserId]])' WHERE ID = 205
UPDATE SUserInterface.GridViewDefinitions SET MetricSqlQuery = N'SELECT CONVERT(DECIMAL(9,2), COUNT(1)) AS MetricValue1, N''#ff0000'' Value1ColourHex, CONVERT(DECIMAL(9,2), 0) AS MetricValue2, N''#0000ff'' Value2ColourHex FROM  SSop.tvf_QuotesChaseTwo([[UserId]])
' WHERE ID = 206
UPDATE SUserInterface.GridViewDefinitions SET SqlQuery = N'SELECT 
	root_hobt.ID,
	root_hobt.Guid,
	root_hobt.Name,
	root_hobt.Description,
	root_hobt.Enabled,
	root_hobt.EntityTypeID,
	root_hobt.OrganisationalUnitId,
	root_hobt.RowStatus,
	root_hobt.RowVersion
FROM [SCore].[tvf_GetWorkflows]([[UserId]]) AS root_hobt' WHERE ID = 209
UPDATE SUserInterface.GridViewDefinitions SET SqlQuery = N'SELECT * 
FROM [SCore].[WorkflowStatus] root_hobt
WHERE 
	(root_hobt.RowStatus NOT IN (0,254)) AND
	( NOT EXISTS --Exclude system generated statuses.
			(
				SELECT 1 
				FROM [SCore].[WorkflowStatus]
				WHERE 
					ShowInEnquiries = 0 AND
					ShowInQuotes = 0 AND
					ShowInJobs = 0 AND
					root_hobt.ID = ID
			)
	)
' WHERE ID = 210
UPDATE SUserInterface.GridViewDefinitions SET SqlQuery = N'SELECT 
	root_hobt.ID,
	root_hobt.RowStatus,
	root_hobt.RowVersion,
	root_hobt.Guid,
	root_hobt.WorkflowID,
	WftF.Name AS FromStatusID,
	WftT.Name AS ToStatusID,
	root_hobt.IsFinal,
	root_hobt.Enabled,
	root_hobt.SortOrder,
	root_hobt.Description
FROM 
	SCore.WorkflowTransition root_hobt
JOIN 
	SCore.Workflow AS Wf ON (root_hobt.WorkflowID = Wf.ID)
JOIN
	SCore.WorkflowStatus AS WfTF ON (WftF.ID = root_hobt.FromStatusID)
JOIN
	SCore.WorkflowStatus AS WfTT ON (WftT.ID = root_hobt.ToStatusID)
WHERE
       Wf.Guid =[[ParentGuid]]' WHERE ID = 211
UPDATE SUserInterface.GridViewDefinitions SET SqlQuery = N'SELECT 
	root_hobt.ID,
	root_hobt.Guid,
	root_hobt.RowStatus,
	root_hobt.RowVersion,
	NewStatus.Name AS StatusID,
	PreviousStatus.Name AS OldStatusID,
	root_hobt.Comment,
	root_hobt.DateTimeUTC,
	CreatedBy.FullName AS CreatedByUserId,
	Surveyor.FullName AS SurveyorUserId,
	root_hobt.DataObjectGuid
FROM [SCore].[DataObjectTransition] AS root_hobt
JOIN SCore.Identities AS CreatedBy ON (CreatedBy.ID = root_hobt.CreatedByUserId)
JOIN SCore.Identities AS Surveyor ON (Surveyor.ID = root_hobt.SurveyorUserId)
LEFT JOIN SCore.WorkflowStatus AS PreviousStatus ON (PreviousStatus.ID = root_hobt.OldStatusID)
LEFT JOIN SCore.WorkflowStatus AS NewStatus ON (NewStatus.ID = root_hobt.StatusID)
WHERE root_hobt.DataObjectGuid = ''[[ParentGuid]]''' WHERE ID = 212
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Reseed identity on SUserInterface.GridViewDefinitions
--
DBCC CHECKIDENT('SUserInterface.GridViewDefinitions', RESEED, 213)
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Updating data of table [SUserInterface].[GridDefinitions]
--
UPDATE SUserInterface.GridDefinitions SET Code = N'Invoicing', LanguageLabelId = 3326 WHERE ID = 103
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Reseed identity on SUserInterface.GridDefinitions
--
DBCC CHECKIDENT('SUserInterface.GridDefinitions', RESEED, 112)
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[LanguageLabelTranslations]
--
ALTER TABLE SCore.LanguageLabelTranslations WITH NOCHECK
  ADD CONSTRAINT FK_LanguageLabelTranslations_LanguageLabels FOREIGN KEY (LanguageLabelID) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.LanguageLabelTranslations WITH NOCHECK
  ADD CONSTRAINT FK_LanguageLabelTranslations_Languages FOREIGN KEY (LanguageID) REFERENCES SCore.Languages(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.LanguageLabelTranslations WITH NOCHECK
  ADD CONSTRAINT FK_LanguageLabelTranslations_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[LanguageLabels]
--
ALTER TABLE SCore.LanguageLabels WITH NOCHECK
  ADD CONSTRAINT FK_LanguageLabels_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridViewDefinitions]
--
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinition_GridDefinition FOREIGN KEY (GridDefinitionId) REFERENCES SUserInterface.GridDefinitions(ID) ON DELETE CASCADE ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_DrawerIconId FOREIGN KEY (DrawerIconId) REFERENCES SUserInterface.Icons(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_EntityTypes FOREIGN KEY (EntityTypeID) REFERENCES SCore.EntityTypes(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_LanguageLabelId FOREIGN KEY (LanguageLabelId) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_MetricTypes FOREIGN KEY (MetricTypeID) REFERENCES SUserInterface.MetricTypes(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridDefinitions]
--
ALTER TABLE SUserInterface.GridDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridDefinitions_LanguageLabelId FOREIGN KEY (LanguageLabelId) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridDefinitions_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityProperties]
--
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_LanguageLabels FOREIGN KEY (LanguageLabelID) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityPropertyGroups]
--
ALTER TABLE SCore.EntityPropertyGroups WITH NOCHECK
  ADD CONSTRAINT FK_EntityPropertyGroups_LanguageLabels FOREIGN KEY (LanguageLabelID) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityTypes]
--
ALTER TABLE SCore.EntityTypes WITH NOCHECK
  ADD CONSTRAINT FK_EntityTypes_LanguageLabels FOREIGN KEY (LanguageLabelID) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[ActionMenuItems]
--
ALTER TABLE SUserInterface.ActionMenuItems WITH NOCHECK
  ADD CONSTRAINT FK_ActionMenuItems_LanguageLabels FOREIGN KEY (LanguageLabelId) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridViewActions]
--
ALTER TABLE SUserInterface.GridViewActions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewActions_LanguageLabelId FOREIGN KEY (LanguageLabelId) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridViewColumnDefinitions]
--
ALTER TABLE SUserInterface.GridViewColumnDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewColumnDefinitions_LanguageLabelId FOREIGN KEY (LanguageLabelId) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridViewWidgetQueries]
--
ALTER TABLE SUserInterface.GridViewWidgetQueries WITH NOCHECK
  ADD CONSTRAINT FK_GridViewWidgetQueries_LanguageLabels FOREIGN KEY (LanguageLabelID) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[MainMenuItems]
--
ALTER TABLE SUserInterface.MainMenuItems WITH NOCHECK
  ADD CONSTRAINT FK_MainMenuItems_LanguageLabelId FOREIGN KEY (LanguageLabelId) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Commit Transaction
--
IF @@TRANCOUNT>0 COMMIT TRANSACTION
SET NOEXEC OFF
GO