--
-- Script was generated by Devart dbForge Data Compare for SQL Server, Version 5.5.3.0
-- Product Home Page: http://www.devart.com/dbforge/sql/datacompare
-- Script date 03/06/2026 21:27:29
-- Source server version: 16.00.1000
-- Source connection string: Data Source=SOC-SQLDEVBRE01\GENERAL;Initial Catalog=CymBuild_Dev;Integrated Security=True;User ID=ESGL\stephen.brett
-- Target server version: 16.00.1000
-- Target connection string: Data Source=SOC-SQLDEVBRE01\GENERAL;Initial Catalog=CymBuild_Dev;Integrated Security=True;User ID=ESGL\stephen.brett
-- Run this script against Cymbuild_QA to synchronize it with CymBuild_Dev
-- Please backup your target database before running this script
--



SET LANGUAGE 'British English'
SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT, XACT_ABORT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS OFF
GO


--
-- Start Transaction
--
PRINT(N'Start Transaction')
GO
BEGIN TRANSACTION

--
-- Disabling DML triggers for [SCore].[EntityQueries]
--
PRINT(N'Disabling DML triggers for [SCore].[EntityQueries]')
GO
DISABLE TRIGGER ALL ON SCore.EntityQueries
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Disabling DML triggers for [SCore].[WorkflowStatus]
--
PRINT(N'Disabling DML triggers for [SCore].[WorkflowStatus]')
GO
DISABLE TRIGGER ALL ON SCore.WorkflowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Disabling DML triggers for [SCore].[DataClassifications]
--
PRINT(N'Disabling DML triggers for [SCore].[DataClassifications]')
GO
DISABLE TRIGGER ALL ON SCore.DataClassifications
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Disabling DML triggers for [SCore].[SecurityClassifications]
--
PRINT(N'Disabling DML triggers for [SCore].[SecurityClassifications]')
GO
DISABLE TRIGGER ALL ON SCore.SecurityClassifications
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityQueries]
--
PRINT(N'Dropping constraints from [SCore].[EntityQueries]')
GO
ALTER TABLE SCore.EntityQueries
  DROP CONSTRAINT IF EXISTS FK_EntityQueries_DataObjects
ALTER TABLE SCore.EntityQueries
  DROP CONSTRAINT IF EXISTS FK_EntityQueries_EntityHoBTs
ALTER TABLE SCore.EntityQueries
  DROP CONSTRAINT IF EXISTS FK_EntityQueries_EntityTypes
ALTER TABLE SCore.EntityQueries
  DROP CONSTRAINT IF EXISTS FK_EntityQueries_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridViewDefinitions]
--
PRINT(N'Dropping constraints from [SUserInterface].[GridViewDefinitions]')
GO
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinition_GridDefinition
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_DrawerIconId
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_EntityTypes
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_LanguageLabelId
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_MetricTypes
ALTER TABLE SUserInterface.GridViewDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewDefinitions_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SAi].[AssistantKnowledgeItems]
--
PRINT(N'Dropping constraints from [SAi].[AssistantKnowledgeItems]')
GO
ALTER TABLE SAi.AssistantKnowledgeItems
  DROP CONSTRAINT IF EXISTS FK_AssistantKnowledgeItems_Categories
ALTER TABLE SAi.AssistantKnowledgeItems
  DROP CONSTRAINT IF EXISTS FK_AssistantKnowledgeItems_DataObjects
ALTER TABLE SAi.AssistantKnowledgeItems
  DROP CONSTRAINT IF EXISTS FK_AssistantKnowledgeItems_Identities_CreatedBy
ALTER TABLE SAi.AssistantKnowledgeItems
  DROP CONSTRAINT IF EXISTS FK_AssistantKnowledgeItems_Identities_UpdatedBy
ALTER TABLE SAi.AssistantKnowledgeItems
  DROP CONSTRAINT IF EXISTS FK_AssistantKnowledgeItems_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityQueryParameters]
--
PRINT(N'Dropping constraints from [SCore].[EntityQueryParameters]')
GO
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS FK_EntityQueryParameters_EntityQueries
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[ActionMenuItems]
--
PRINT(N'Dropping constraints from [SUserInterface].[ActionMenuItems]')
GO
ALTER TABLE SUserInterface.ActionMenuItems
  DROP CONSTRAINT IF EXISTS FK_ActionMenuItems_EntityQueries
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridViewActions]
--
PRINT(N'Dropping constraints from [SUserInterface].[GridViewActions]')
GO
ALTER TABLE SUserInterface.GridViewActions
  DROP CONSTRAINT IF EXISTS FK_GridViewActions_EntityQueries
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridViewWidgetQueries]
--
PRINT(N'Dropping constraints from [SUserInterface].[GridViewWidgetQueries]')
GO
ALTER TABLE SUserInterface.GridViewWidgetQueries
  DROP CONSTRAINT IF EXISTS FK_GridViewWidgetQueries_EntityQueries
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[DataObjectTransition]
--
PRINT(N'Dropping constraints from [SCore].[DataObjectTransition]')
GO
ALTER TABLE SCore.DataObjectTransition
  DROP CONSTRAINT IF EXISTS FK_DataObjectTransition_OldStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[WorkflowTransition]
--
PRINT(N'Dropping constraints from [SCore].[WorkflowTransition]')
GO
ALTER TABLE SCore.WorkflowTransition
  DROP CONSTRAINT IF EXISTS FK_WorkflowTransition_FromStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SUserInterface].[GridViewColumnDefinitions]
--
PRINT(N'Dropping constraints from [SUserInterface].[GridViewColumnDefinitions]')
GO
ALTER TABLE SUserInterface.GridViewColumnDefinitions
  DROP CONSTRAINT IF EXISTS FK_GridViewColumnDefinition_GridViewDefinition
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SAi].[AssistantContentGaps]
--
PRINT(N'Dropping constraints from [SAi].[AssistantContentGaps]')
GO
ALTER TABLE SAi.AssistantContentGaps
  DROP CONSTRAINT IF EXISTS FK_AssistantContentGaps_KnowledgeItems
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SAi].[AssistantKnowledgeItemTags]
--
PRINT(N'Dropping constraints from [SAi].[AssistantKnowledgeItemTags]')
GO
ALTER TABLE SAi.AssistantKnowledgeItemTags
  DROP CONSTRAINT IF EXISTS FK_AssistantKnowledgeItemTags_Items
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SAi].[AssistantKnowledgeItemVersions]
--
PRINT(N'Dropping constraints from [SAi].[AssistantKnowledgeItemVersions]')
GO
ALTER TABLE SAi.AssistantKnowledgeItemVersions
  DROP CONSTRAINT IF EXISTS FK_AssistantKnowledgeItemVersions_Items
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SAi].[AssistantUploads]
--
PRINT(N'Dropping constraints from [SAi].[AssistantUploads]')
GO
ALTER TABLE SAi.AssistantUploads
  DROP CONSTRAINT IF EXISTS FK_AssistantUploads_KnowledgeItems
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SJob].[Jobs]
--
PRINT(N'Dropping constraints from [SJob].[Jobs]')
GO
ALTER TABLE SJob.Jobs
  DROP CONSTRAINT IF EXISTS FK_Jobs_DataClassifications
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SSop].[Projects]
--
PRINT(N'Dropping constraints from [SSop].[Projects]')
GO
ALTER TABLE SSop.Projects
  DROP CONSTRAINT IF EXISTS FK_Projects_DataClassifications
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SSop].[Quotes]
--
PRINT(N'Dropping constraints from [SSop].[Quotes]')
GO
ALTER TABLE SSop.Quotes
  DROP CONSTRAINT IF EXISTS FK_Quotes_DataClassifications
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Updating data of table SCore.EntityQueries
--
PRINT(N'Updating data of table SCore.EntityQueries')
GO
UPDATE SCore.EntityQueries SET Statement = N'SELECT 
	[E8455B33-57E5-4BBA-8A39-31F7D6822171].Guid AS ActivityID,
	root_hobt.Description,
	root_hobt.Gross,
	root_hobt.Guid,
	root_hobt.ID,
	root_hobt.InvoiceRequestItemId,
	[C2E1B699-22BE-49B4-8A1D-E4F045195D13].Guid AS JobPaymentStageId,
	root_hobt.LegacyId,
	root_hobt.LegacySystemID,
	[A722809B-CB57-49C2-8C14-B819E996D222].Guid AS MilestoneID,
	root_hobt.Net,
	root_hobt.Qty,
	[7C737459-C141-4F03-BAFB-C05D386D70E3].Guid AS RIBAStageId,
	root_hobt.RowStatus,
	root_hobt.RowVersion,
	[BFB87EA7-11F2-49CA-89FB-D1089EA149FD].Guid AS TransactionID,
	root_hobt.Vat,
	[290003C0-1E15-42B0-8CB4-EFD14FD8D71D].Guid AS VatCodeID,
	root_hobt.VatRate
FROM SFin.TransactionDetails AS root_hobt 
JOIN SJob.Activities AS [E8455B33-57E5-4BBA-8A39-31F7D6822171] ON ([E8455B33-57E5-4BBA-8A39-31F7D6822171].ID = root_hobt.ActivityID) 
 JOIN SJob.Milestones AS [A722809B-CB57-49C2-8C14-B819E996D222] ON ([A722809B-CB57-49C2-8C14-B819E996D222].ID = root_hobt.MilestoneID) 
 JOIN SFin.Transactions AS [BFB87EA7-11F2-49CA-89FB-D1089EA149FD] ON ([BFB87EA7-11F2-49CA-89FB-D1089EA149FD].ID = root_hobt.TransactionID) 
 JOIN SJob.JobPaymentStages AS [C2E1B699-22BE-49B4-8A1D-E4F045195D13] ON ([C2E1B699-22BE-49B4-8A1D-E4F045195D13].ID = root_hobt.JobPaymentStageId) 
 JOIN SJob.RibaStages AS [7C737459-C141-4F03-BAFB-C05D386D70E3] ON ([7C737459-C141-4F03-BAFB-C05D386D70E3].ID = root_hobt.RIBAStageId) 
 JOIN SFin.VatCodes AS [290003C0-1E15-42B0-8CB4-EFD14FD8D71D] ON ([290003C0-1E15-42B0-8CB4-EFD14FD8D71D].ID = root_hobt.VatCodeID) 
' WHERE ID = 188
UPDATE SCore.EntityQueries SET Statement = N'SELECT 
	root_hobt.ConstructionStageChange,
	root_hobt.ConstructionStageMeetingChange,
	root_hobt.ConstructionStageVisitChange,
	[CF412054-4E61-424D-BFD1-D55C52DAF97E].Guid AS CreatedByUserID,
	root_hobt.CreatedDateTime,
	root_hobt.FeeCapChange,
	root_hobt.Guid,
	root_hobt.ID,
	[DB24C54E-C649-4FAF-B134-99087AF7B6C6].Guid AS JobID,
	root_hobt.PreConstructionStageChange,
	root_hobt.PreConstructionStageMeetingChange,
	root_hobt.PreConstructionStageVisitChange,
	root_hobt.Reason,
	root_hobt.RibaStage0Change,
	root_hobt.RibaStage0MeetingChange,
	root_hobt.RibaStage0VisitChange,
	root_hobt.RibaStage1Change,
	root_hobt.RibaStage1MeetingChange,
	root_hobt.RibaStage1VisitChange,
	root_hobt.RibaStage2Change,
	root_hobt.RibaStage2MeetingChange,
	root_hobt.RibaStage2VisitChange,
	root_hobt.RibaStage3Change,
	root_hobt.RibaStage3MeetingChange,
	root_hobt.RibaStage3VisitChange,
	root_hobt.RibaStage4Change,
	root_hobt.RibaStage4MeetingChange,
	root_hobt.RibaStage4VisitChange,
	root_hobt.RibaStage5Change,
	root_hobt.RibaStage5MeetingChange,
	root_hobt.RibaStage5VisitChange,
	root_hobt.RibaStage6Change,
	root_hobt.RibaStage6MeetingChange,
	root_hobt.RibaStage6VisitChange,
	root_hobt.RibaStage7Change,
	root_hobt.RibaStage7MeetingChange,
	root_hobt.RibaStage7VisitChange,
	root_hobt.RowStatus,
	root_hobt.RowVersion
FROM SJob.FeeAmendment AS root_hobt 
JOIN SCore.Identities AS [CF412054-4E61-424D-BFD1-D55C52DAF97E] ON ([CF412054-4E61-424D-BFD1-D55C52DAF97E].ID = root_hobt.CreatedByUserID) 
 JOIN SJob.Jobs AS [DB24C54E-C649-4FAF-B134-99087AF7B6C6] ON ([DB24C54E-C649-4FAF-B134-99087AF7B6C6].ID = root_hobt.JobID) 
' WHERE ID = 192
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Updating data of table SCore.WorkflowStatus
--
PRINT(N'Updating data of table SCore.WorkflowStatus')
GO
UPDATE SCore.WorkflowStatus SET IsAuthStatus = 0 WHERE ID = 67

--
-- Updating data of table SUserInterface.GridViewDefinitions
--
PRINT(N'Updating data of table SUserInterface.GridViewDefinitions')
GO
UPDATE SUserInterface.GridViewDefinitions SET SqlQuery = N'SELECT	root_hobt.Guid,
		root_hobt.RowStatus,
		root_hobt.Stage,
		root_hobt.StageLabel,
		root_hobt.Agreed,
		root_hobt.Invoiced,
                root_hobt.Paid,
		root_hobt.Remaining,
		root_hobt.QuotedMeetings,
		root_hobt.CompletedMeetings,
		root_hobt.QuotedSiteVisits,
		root_hobt.CompletedSiteVisits,
                root_hobt.IsTotalHighlightRow
FROM	SJob.tvf_JobFeeDrawdown (	[[UserId]],
									''[[ParentGuid]]''
								) AS root_hobt' WHERE ID = 88

--
-- Updating data of table SAi.AssistantKnowledgeItems
--
PRINT(N'Updating data of table SAi.AssistantKnowledgeItems')
GO
EXEC(N'UPDATE SAi.AssistantKnowledgeItems SET Summary = N''CymBuild  DocumentationV4.0     CymBuild  DocumentationV4.0

CymBuild  Documentation

V4.0

CymBuild  Documentation

V4.0

Contents

Introduction3

Purpose3

Overview4

Navigation Bar4

Quick Access Links5

IT Support Section5

Modal View5

Grid Views5

Grid View Types6

Grids/Rows7

Filters8

Getting Started10

Multiplatform10

System Requirements10

Installation10

Converting CymBuild into an installed application (Optional)10

Basic Operations of The Software12

Components12

Input Components14

Basic Operations20

Parent-Child Relationship20

Home Page (Wiget Board)22

Widget Types23

Functionality25

Customer Relationship Management (CRM)28

Structure29

Enquiry29

Quote31

Job33

Finance35

Settings36

Report I...

--- Extracted Text ---
CymBuild  DocumentationV4.0     CymBuild  DocumentationV4.0

CymBuild  Documentation

V4.0

CymBuild  Documentation

V4.0

Contents

Introduction3

Purpose3

Overview4

Navigation Bar4

Quick Access Links5

IT Support Section5

Modal View5

Grid Views5

Grid View Types6

Grids/Rows7

Filters8

Getting Started10

Multiplatform10

System Requirements10

Installation10

Converting CymBuild into an installed application (Optional)10

Basic Operations of The Software12

Components12

Input Components14

Basic Operations20

Parent-Child Relationship20

Home Page (Wiget Board)22

Widget Types23

Functionality25

Customer Relationship Management (CRM)28

Structure29

Enquiry29

Quote31

Job33

Finance35

Settings36

Report Issue & Feedback Form36

Troubleshooting Guide36

Frequently Asked Questions36

Resources36

Links36

Introduction

Concursus Yielding Metadata for BUILDing & Real Estate

Purpose

This document aims to outline the core features of CymBuild from the user''''s perspective, ensuring smooth software use and serving as a helpful reference when needed. It starts with an overview of the platform, helping users navigate CymBuild''''s layout with ease. Then, the document introduces essential components like tables, buttons, and filters. This introduction is crucial for two reasons: firstly, these elements are the building blocks of the application, present throughout various sections. Secondly, understanding them ensures that users can utilize them effectively.

Once the basics are understood, users should feel confident navigating the system. The next steps are to:

Explain how to carry out various processes, such as creating an inquiry or quote.

Provide a troubleshooting guide.

Offer answers to frequently asked questions.

Finally, a comprehensive list of available resources will be included.

OverviewWhen launching the application, the user is greeted by the Home/Dashboard page. The navigation menu is located on the left side, while the quick access sections are displayed on the right.

Navigation Bar

Figure 1 – Navigation Bar

Home:

Directs the user to the widget dashboard.

My Work:

Displays all jobs associated with the user.

Projects:

Projects link multiple related Enquires, Quotes and Jobs of a real-world project. These may belong to one of more clients or agents but are part of the same physical construction project.

Schedule:

Opens Team Schedule & Team Availability where the user can add and track upcoming activities in the system. (Note: As of the writing of this document, Outlook Calendar has not yet been synchronised.)

CRM:

Customer Relationship Management: Shows a list of all customers in the system.

Structures:

(Properties/UPRN) Provides a list of sites where work has been conducted by SOCOTEC. It includes site addresses, unique property reference numbers (UPRNs), authorities, and more.

Enquiries:

Displays a list of all received enquiries, regardless of their status. This is the initial stage of '
+ N'job creation and is always required. An enquiry progresses to a quote.

Quoting:

Shows all quotes available in the system. Quotes originate from enquiries and can convert into jobs.

Jobs:

Provides a list of all jobs added

Shows a list of projects with all the relevant information pertaining to them, which are generated from completed quotes.

Authorisation

Grid area where records awaiting approval can be found

Finance:

Lists previous transactions throughout the system, as well as those specific to the user. Users can also export invoices for importing into Sage.

Settings:

Provides access to various system settings.

Quick Access Links

The document is intended to outline the essential features of CymBuild from the user''''s viewpoint, facilitating smoother software utilization and offering reference, as necessary. Starting with the overview of the platform, the user is introduced CymBuild’s layout.

IT Support Section

At the bottom of the page, you will find a section of text that almost blends into the background – this section is dedicated to IT support as it provides information specific to the user environment, which can be used for troubleshooting issues users might encounter (Figure 5).

Figure 2 - Information for IT Support.

Modal View

A modal is a type of user interface component that appears over a web page. It is typically used for entering details related to a record but can also serve as a window for read-only information (Figure 6).

Figure 3 - Modal Window Highlighted in Red

Grid Views

When working with lists, users will typically interact with them via tables (also known as grids). The figure below provides a screenshot of one, with the different sections color-coded (Figure 7).

Figure 4- Table.

.

Dynamic Grid

The outer window that contains all the other components.

Grid Drawers:

Like items in the navigation bar, these organize data into logical sections. They can be expanded or collapsed by clicking the hamburger icon in the top-left corner.

Grid View:

Displays rows of data (as seen in Figure 9).

Grid View Types

There are two types of views the user can encounter: normal, batch, and activities batch, with the difference being the checkbox found next to each item in the latter two grid types. The purpose of these grids is to enable the user to select multiple records & then perform an operation of some sort on them in one go, such as changing common fields, generating documents for them, etc. This can help the user save time by not having to perform the same operation one-by-one.

Figure 5 - Batch Grid View

Here, the user can either select items one-by-one by clicking the desired line in the grid, or alternatively, they may select all items by clicking the checkbox at the very top (figure 6). Please, note that when using “select all,” only items on the current page of the grid will be selected.

Figure 6 - Select all for batch grids.

Example:

Assume there are 5 pages of data for a given grid. Using the “Select All” button will select everything from the first page but not from the remaining pages. You will have to navigate to the correct page in the grid and then make further selection.

After the required selection has been made, the available batch functionality can be accessed by looking for the “Actions” button (coloured blue) which can be found above the grid on the right-hand side.

Grids/Rows

Figure 7 - Grid View

Each grid can be interacted with by double-clicking on it, but the outcome depends on the grid''''s specific configuration. Users can expect one of three behaviours:

The user is redirected to a new page.

A "modal" opens.

Nothing happens.

NOTE:

When a grid is clicked once, it just simply gets highlighted in light blue - Please, refer to Figure 7.

Filters

Tables can be sorted by each column – this means we can use more than one column to sort data. To access the f'
+ N'ilter, simply locate the desired column, and click the filter icon     .  Once clicked, the dropdown below in figure 8 will appear.

Figure 8 - Grid Filter

To understand how this works, let us refer to the diagram below. The dropdown is divided into two halves. We first check if a value has been entered in the second half. If not, only the first half of the filter will be applied. Otherwise, the first and second halves are combined into a single filter, which in this diagram would be: "Contains VALUE and Ends With VALUE."

Figure 9 – Critical Path Diagram for The Filter.

Figure 9 - Filter Example

Take the screenshot above (fig. 12) as an example. Since both halves are filled out, the filter becomes:

“(Looking for values that) Contains ‘F’ and end with 10”.

If the second half is not filled out, the filter will simply search for values containing the letter "F."

NOTE:

The filter is not case-sensitive, therefore entering values in lowercase or uppercase will not affect the results that get returned. After entering the filter values, the user must click the blue "Filter" button.

Filter Options

The previous examples rely on the same search conditions (Contains, And, Ends With, etc.), but there are additional options available. Some of the choice’s users can select include:

Is Equal To

Has No Value

Does Not Contain

Starts With

Regarding the join operator (the "And" dropdown), there are only two values:

And

Or

NOTE:

When using the "And" operator, both conditions must be true.

When using the "Or" operator, either condition can be true.

Getting Started

Multiplatform

CymBuild can run on multiple platforms because it is a progressive web application (PWA). This means that while CymBuild can be accessed via a web browser, it can also be installed locally on both computers and mobile devices.'' WHERE ID = 47')

--
-- Updating data of table SCore.DataClassifications
--
PRINT(N'Updating data of table SCore.DataClassifications')
GO
UPDATE SCore.DataClassifications SET Guid = '31e24091-52b4-480e-9a85-7052f614567a' WHERE ID = -1

--
-- Updating data of table SCore.SecurityClassifications
--
PRINT(N'Updating data of table SCore.SecurityClassifications')
GO
UPDATE SCore.SecurityClassifications SET Guid = 'b4ef7a4d-454b-4c4b-af3d-5996312fd038' WHERE ID = -1

--
-- Creating constraints for [SCore].[EntityQueries]
--
PRINT(N'Creating constraints for [SCore].[EntityQueries]')
GO
ALTER TABLE SCore.EntityQueries WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueries_DataObjects FOREIGN KEY (Guid) REFERENCES SCore.DataObjects(Guid) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityQueries WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueries_EntityHoBTs FOREIGN KEY (EntityHoBTID) REFERENCES SCore.EntityHobts(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityQueries WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueries_EntityTypes FOREIGN KEY (EntityTypeID) REFERENCES SCore.EntityTypes(ID) ON DELETE CASCADE ON UPDATE NO ACTION
ALTER TABLE SCore.EntityQueries WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueries_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridViewDefinitions]
--
PRINT(N'Creating constraints for [SUserInterface].[GridViewDefinitions]')
GO
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinition_GridDefinition FOREIGN KEY (GridDefinitionId) REFERENCES SUserInterface.GridDefinitions(ID) ON DELETE CASCADE ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_DrawerIconId FOREIGN KEY (DrawerIconId) REFERENCES SUserInterface.Icons(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_EntityTypes FOREIGN KEY (EntityTypeID) REFERENCES SCore.EntityTypes(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_LanguageLabelId FOREIGN KEY (LanguageLabelId) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_MetricTypes FOREIGN KEY (MetricTypeID) REFERENCES SUserInterface.MetricTypes(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SUserInterface.GridViewDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewDefinitions_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SAi].[AssistantKnowledgeItems]
--
PRINT(N'Creating constraints for [SAi].[AssistantKnowledgeItems]')
GO
ALTER TABLE SAi.AssistantKnowledgeItems WITH NOCHECK
  ADD CONSTRAINT FK_AssistantKnowledgeItems_Categories FOREIGN KEY (KnowledgeCategoryId) REFERENCES SAi.AssistantKnowledgeCategories(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SAi.AssistantKnowledgeItems WITH NOCHECK
  ADD CONSTRAINT FK_AssistantKnowledgeItems_DataObjects FOREIGN KEY (Guid) REFERENCES SCore.DataObjects(Guid) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SAi.AssistantKnowledgeItems WITH NOCHECK
  ADD CONSTRAINT FK_AssistantKnowledgeItems_Identities_CreatedBy FOREIGN KEY (CreatedByUserId) REFERENCES SCore.Identities(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SAi.AssistantKnowledgeItems WITH NOCHECK
  ADD CONSTRAINT FK_AssistantKnowledgeItems_Identities_UpdatedBy FOREIGN KEY (UpdatedByUserId) REFERENCES SCore.Identities(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SAi.AssistantKnowledgeItems WITH NOCHECK
  ADD CONSTRAINT FK_AssistantKnowledgeItems_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityQueryParameters]
--
PRINT(N'Creating constraints for [SCore].[EntityQueryParameters]')
GO
ALTER TABLE SCore.EntityQueryParameters WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueryParameters_EntityQueries FOREIGN KEY (EntityQueryID) REFERENCES SCore.EntityQueries(ID) ON DELETE CASCADE ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[ActionMenuItems]
--
PRINT(N'Creating constraints for [SUserInterface].[ActionMenuItems]')
GO
ALTER TABLE SUserInterface.ActionMenuItems WITH NOCHECK
  ADD CONSTRAINT FK_ActionMenuItems_EntityQueries FOREIGN KEY (EntityQueryId) REFERENCES SCore.EntityQueries(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridViewActions]
--
PRINT(N'Creating constraints for [SUserInterface].[GridViewActions]')
GO
ALTER TABLE SUserInterface.GridViewActions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewActions_EntityQueries FOREIGN KEY (EntityQueryId) REFERENCES SCore.EntityQueries(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridViewWidgetQueries]
--
PRINT(N'Creating constraints for [SUserInterface].[GridViewWidgetQueries]')
GO
ALTER TABLE SUserInterface.GridViewWidgetQueries WITH NOCHECK
  ADD CONSTRAINT FK_GridViewWidgetQueries_EntityQueries FOREIGN KEY (EntityQueryId) REFERENCES SCore.EntityQueries(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[DataObjectTransition]
--
PRINT(N'Creating constraints for [SCore].[DataObjectTransition]')
GO
ALTER TABLE SCore.DataObjectTransition WITH NOCHECK
  ADD CONSTRAINT FK_DataObjectTransition_OldStatus FOREIGN KEY (OldStatusID) REFERENCES SCore.WorkflowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[WorkflowTransition]
--
PRINT(N'Creating constraints for [SCore].[WorkflowTransition]')
GO
ALTER TABLE SCore.WorkflowTransition WITH NOCHECK
  ADD CONSTRAINT FK_WorkflowTransition_FromStatus FOREIGN KEY (FromStatusID) REFERENCES SCore.WorkflowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SUserInterface].[GridViewColumnDefinitions]
--
PRINT(N'Creating constraints for [SUserInterface].[GridViewColumnDefinitions]')
GO
ALTER TABLE SUserInterface.GridViewColumnDefinitions WITH NOCHECK
  ADD CONSTRAINT FK_GridViewColumnDefinition_GridViewDefinition FOREIGN KEY (GridViewDefinitionId) REFERENCES SUserInterface.GridViewDefinitions(ID) ON DELETE CASCADE ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SAi].[AssistantContentGaps]
--
PRINT(N'Creating constraints for [SAi].[AssistantContentGaps]')
GO
ALTER TABLE SAi.AssistantContentGaps WITH NOCHECK
  ADD CONSTRAINT FK_AssistantContentGaps_KnowledgeItems FOREIGN KEY (SuggestedKnowledgeItemId) REFERENCES SAi.AssistantKnowledgeItems(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SAi].[AssistantKnowledgeItemTags]
--
PRINT(N'Creating constraints for [SAi].[AssistantKnowledgeItemTags]')
GO
ALTER TABLE SAi.AssistantKnowledgeItemTags WITH NOCHECK
  ADD CONSTRAINT FK_AssistantKnowledgeItemTags_Items FOREIGN KEY (KnowledgeItemId) REFERENCES SAi.AssistantKnowledgeItems(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SAi].[AssistantKnowledgeItemVersions]
--
PRINT(N'Creating constraints for [SAi].[AssistantKnowledgeItemVersions]')
GO
ALTER TABLE SAi.AssistantKnowledgeItemVersions WITH NOCHECK
  ADD CONSTRAINT FK_AssistantKnowledgeItemVersions_Items FOREIGN KEY (KnowledgeItemId) REFERENCES SAi.AssistantKnowledgeItems(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SAi].[AssistantUploads]
--
PRINT(N'Creating constraints for [SAi].[AssistantUploads]')
GO
ALTER TABLE SAi.AssistantUploads WITH NOCHECK
  ADD CONSTRAINT FK_AssistantUploads_KnowledgeItems FOREIGN KEY (KnowledgeItemId) REFERENCES SAi.AssistantKnowledgeItems(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SJob].[Jobs]
--
PRINT(N'Creating constraints for [SJob].[Jobs]')
GO
ALTER TABLE SJob.Jobs WITH NOCHECK
  ADD CONSTRAINT FK_Jobs_DataClassifications FOREIGN KEY (DataClassificationID) REFERENCES SCore.DataClassifications(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SSop].[Projects]
--
PRINT(N'Creating constraints for [SSop].[Projects]')
GO
ALTER TABLE SSop.Projects WITH NOCHECK
  ADD CONSTRAINT FK_Projects_DataClassifications FOREIGN KEY (DataClassificationID) REFERENCES SCore.DataClassifications(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SSop].[Quotes]
--
PRINT(N'Creating constraints for [SSop].[Quotes]')
GO
ALTER TABLE SSop.Quotes WITH NOCHECK
  ADD CONSTRAINT FK_Quotes_DataClassifications FOREIGN KEY (DataClassificationID) REFERENCES SCore.DataClassifications(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Enabling DML triggers for [SCore].[EntityQueries]
--
PRINT(N'Enabling DML triggers for [SCore].[EntityQueries]')
GO
ENABLE TRIGGER ALL ON SCore.EntityQueries
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Enabling DML triggers for [SCore].[WorkflowStatus]
--
PRINT(N'Enabling DML triggers for [SCore].[WorkflowStatus]')
GO
ENABLE TRIGGER ALL ON SCore.WorkflowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Enabling DML triggers for [SCore].[DataClassifications]
--
PRINT(N'Enabling DML triggers for [SCore].[DataClassifications]')
GO
ENABLE TRIGGER ALL ON SCore.DataClassifications
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Enabling DML triggers for [SCore].[SecurityClassifications]
--
PRINT(N'Enabling DML triggers for [SCore].[SecurityClassifications]')
GO
ENABLE TRIGGER ALL ON SCore.SecurityClassifications
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END


--
-- Commit Transaction
--
PRINT(N'Commit Transaction')
GO
IF @@TRANCOUNT>0 COMMIT TRANSACTION
SET NOEXEC OFF
GO