CREATE FULLTEXT STOPLIST [Honorifics] AUTHORIZATION [dbo];
GO

ALTER FULLTEXT STOPLIST [Honorifics] ADD 'Dr' LANGUAGE 1033;
GO

ALTER FULLTEXT STOPLIST [Honorifics] ADD 'Lord' LANGUAGE 1033;
GO

ALTER FULLTEXT STOPLIST [Honorifics] ADD 'Mr' LANGUAGE 1033;
GO

ALTER FULLTEXT STOPLIST [Honorifics] ADD 'Mrs' LANGUAGE 1033;
GO

ALTER FULLTEXT STOPLIST [Honorifics] ADD 'Ms' LANGUAGE 1033;
GO

ALTER FULLTEXT STOPLIST [Honorifics] ADD 'Mx' LANGUAGE 1033;
GO

ALTER FULLTEXT STOPLIST [Honorifics] ADD 'Sir' LANGUAGE 1033;
GO