# Build stage
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Copy and restore project
COPY ["Concursus.PWA.csproj", "./"]
RUN dotnet restore "./Concursus.PWA.csproj"

# Copy full solution
COPY . .
RUN dotnet publish "Concursus.PWA.csproj" -c Release -o /app/publish

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_ENVIRONMENT=Production
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

EXPOSE 80
ENTRYPOINT ["dotnet", "Concursus.PWA.dll"]
