/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 66e9443c-e376-42fa-9cfc-f78ab79eeff0
    Object             : Constraint SCore.EntityTypes.DF_EntityTypes_IsOnBoarding
    Difference         : MissingInTarget
    Comparison hash    : 4494E53E4DA90AB183EBBFB907EA7251DC417161CAE0FCC5E1DD2B2A9366C3E2
    Definition SHA-256 : B8523C675A6EE4DEB8D6DEFEB159C59BD0B4B77FDCB424D7CE99ED4C4B7C084C
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:06.5716154Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SCore].[EntityTypes]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SCore.EntityTypes does not exist.', 1;
IF COL_LENGTH(N'[SCore].[EntityTypes]', N'IsOnBoarding') IS NULL
    THROW 51404, 'Default-constraint column SCore.EntityTypes.IsOnBoarding does not exist.', 1;
GO
