/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 1eb09d58-ed21-4baa-8a66-067f11533408
    Object             : Constraint SCore.tvf_WorkflowValidate.DF__tvf_Workf__IsRea__065DC4D6
    Difference         : MissingInTarget
    Comparison hash    : 913A4FFEC21A8C990E21FCA37CF72D5DDBA81B2AE629852DC83F441956B45D5A
    Definition SHA-256 : 33ACABD98491DC316BC9F0A7B14B310B3E725C7867DCC6A05C7329AC0ACD0614
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:06.2261924Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SCore].[tvf_WorkflowValidate]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SCore.tvf_WorkflowValidate does not exist.', 1;
IF COL_LENGTH(N'[SCore].[tvf_WorkflowValidate]', N'IsReadOnly') IS NULL
    THROW 51404, 'Default-constraint column SCore.tvf_WorkflowValidate.IsReadOnly does not exist.', 1;
GO
