/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : cd7dd01f-5c84-4d3e-bcc2-4af048f5bb2d
    Object             : Constraint SCore.tvf_WorkflowValidate.DF__tvf_Workf__Messa__0A2E55BA
    Difference         : MissingInTarget
    Comparison hash    : AE23361C700959395C0E8EAB5A839ABD85DF04F2246652F12AFC7A455D1AFFD5
    Definition SHA-256 : 78AE966C56D426F14E1F10959ECD319E7762C374EA902B8FA29FED6C70EEEC6F
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:06.3197223Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SCore].[tvf_WorkflowValidate]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SCore.tvf_WorkflowValidate does not exist.', 1;
IF COL_LENGTH(N'[SCore].[tvf_WorkflowValidate]', N'Message') IS NULL
    THROW 51404, 'Default-constraint column SCore.tvf_WorkflowValidate.Message does not exist.', 1;
GO
