/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 10943a6b-7d86-4cab-9e4f-df70d8731b61
    Object             : Constraint SCore.tvf_WorkflowStatusValidate.DF__tvf_Workf__Targe__780FA57F
    Difference         : MissingInTarget
    Comparison hash    : FCFDE80E381BF5EDA60434BD53700953F254E3C7480743CF0584BFBF0C230524
    Definition SHA-256 : 85820182A65BBAC21CCA35F8163B626EE57B86D1186635DA5769BEFF2F7B9B2A
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:06.4687669Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SCore].[tvf_WorkflowStatusValidate]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SCore.tvf_WorkflowStatusValidate does not exist.', 1;
IF COL_LENGTH(N'[SCore].[tvf_WorkflowStatusValidate]', N'TargetType') IS NULL
    THROW 51404, 'Default-constraint column SCore.tvf_WorkflowStatusValidate.TargetType does not exist.', 1;
GO
