/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 1423cba9-3ca9-4f6c-8ff0-1e3599ce38cf
    Object             : Constraint SCore.tvf_WorkflowTransitionValidate.DF__tvf_Workf__Targe__7DC87ED5
    Difference         : MissingInTarget
    Comparison hash    : DC8397CCE23522BDB38F8F2530FEE78870948E5374A9E2E496E8E953666845DC
    Definition SHA-256 : 8178317E84A8D7833A1E9851EE9DECA4177C96D4CA65C043F0D6421DB41DEEEA
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:06.4997788Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SCore].[tvf_WorkflowTransitionValidate]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SCore.tvf_WorkflowTransitionValidate does not exist.', 1;
IF COL_LENGTH(N'[SCore].[tvf_WorkflowTransitionValidate]', N'TargetGuid') IS NULL
    THROW 51404, 'Default-constraint column SCore.tvf_WorkflowTransitionValidate.TargetGuid does not exist.', 1;
GO
