/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 2b875235-5549-4086-a900-2bcef9f91e18
    Object             : Constraint SCore.tvf_WorkflowTransitionValidate.DF__tvf_Workf__Messa__0381582B
    Difference         : MissingInTarget
    Comparison hash    : AE23361C700959395C0E8EAB5A839ABD85DF04F2246652F12AFC7A455D1AFFD5
    Definition SHA-256 : 78AE966C56D426F14E1F10959ECD319E7762C374EA902B8FA29FED6C70EEEC6F
    Purpose            : Finalize phase: create the source constraint from the declarative snapshot.
    Generated UTC      : 2026-08-11T08:37:06.3047231Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF NOT EXISTS
(
    SELECT 1
    FROM sys.objects AS constraintObject
    WHERE constraintObject.parent_object_id = OBJECT_ID(N'[SCore].[tvf_WorkflowTransitionValidate]', N'U')
      AND constraintObject.name = N'DF__tvf_Workf__Messa__0381582B'
)
    BEGIN
        ALTER TABLE [SCore].[tvf_WorkflowTransitionValidate] ADD CONSTRAINT [DF__tvf_Workf__Messa__0381582B] DEFAULT ('') FOR [Message];
    END;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
