/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 201071e9-fb41-4fec-b39e-dd2af7fb1f13
    Object             : Constraint SCore.tvf_WorkflowTransitionValidate.DF__tvf_Workf__IsHid__00A4EB80
    Difference         : MissingInTarget
    Comparison hash    : 4C56535AC1DA0D677F77958CF60EA6DCEA4AB40DC473DA768AF95412767B9683
    Definition SHA-256 : A8E3545B05890BC0060027C5A60F46F6EF6CD1AFFC6F6547D6CC7D5AF867B161
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:06.0094615Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SCore].[tvf_WorkflowTransitionValidate]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SCore.tvf_WorkflowTransitionValidate does not exist.', 1;
IF COL_LENGTH(N'[SCore].[tvf_WorkflowTransitionValidate]', N'IsHidden') IS NULL
    THROW 51404, 'Default-constraint column SCore.tvf_WorkflowTransitionValidate.IsHidden does not exist.', 1;
GO
