/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 0f9548c7-c86c-4f6d-b05f-dd2eaefaa6ab
    Object             : Constraint SFin.tvf_InvoiceScheduleMonthConfigurationValidate.DF__tvf_Invoi__Targe__003AD72C
    Difference         : MissingInTarget
    Comparison hash    : DC8397CCE23522BDB38F8F2530FEE78870948E5374A9E2E496E8E953666845DC
    Definition SHA-256 : 8178317E84A8D7833A1E9851EE9DECA4177C96D4CA65C043F0D6421DB41DEEEA
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:07.2346543Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SFin].[tvf_InvoiceScheduleMonthConfigurationValidate]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SFin.tvf_InvoiceScheduleMonthConfigurationValidate does not exist.', 1;
IF COL_LENGTH(N'[SFin].[tvf_InvoiceScheduleMonthConfigurationValidate]', N'TargetGuid') IS NULL
    THROW 51404, 'Default-constraint column SFin.tvf_InvoiceScheduleMonthConfigurationValidate.TargetGuid does not exist.', 1;
GO
