/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 7a2315d9-f988-4d18-9360-220acb87db15
    Object             : Constraint SFin.TransactionDetailsValidate.DF__Transacti__IsInv__473763FA
    Difference         : MissingInTarget
    Comparison hash    : 47FFCB032EC9ABF53490116879B46A434AAB37E57A8BF0C7DDB54C1C9DD0DBC2
    Definition SHA-256 : 7EA15F0FB6F5909E0B1626355BABCEC26C1A846CB48AC9D086463E0FD3AEA5A4
    Purpose            : Finalize phase: create the source constraint from the declarative snapshot.
    Generated UTC      : 2026-08-11T08:37:06.7984269Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF NOT EXISTS
(
    SELECT 1
    FROM sys.objects AS constraintObject
    WHERE constraintObject.parent_object_id = OBJECT_ID(N'[SFin].[TransactionDetailsValidate]', N'U')
      AND constraintObject.name = N'DF__Transacti__IsInv__473763FA'
)
    BEGIN
        ALTER TABLE [SFin].[TransactionDetailsValidate] ADD CONSTRAINT [DF__Transacti__IsInv__473763FA] DEFAULT ((0)) FOR [IsInvalid];
    END;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
