/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 3ca63366-04a2-4e85-8d0f-5ebd57d5d63f
    Object             : Constraint SFin.TransactionsValidate.DF__Transacti__Messa__3AD18D15
    Difference         : MissingInTarget
    Comparison hash    : AE23361C700959395C0E8EAB5A839ABD85DF04F2246652F12AFC7A455D1AFFD5
    Definition SHA-256 : 78AE966C56D426F14E1F10959ECD319E7762C374EA902B8FA29FED6C70EEEC6F
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:06.8739534Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SFin].[TransactionsValidate]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SFin.TransactionsValidate does not exist.', 1;
IF COL_LENGTH(N'[SFin].[TransactionsValidate]', N'Message') IS NULL
    THROW 51404, 'Default-constraint column SFin.TransactionsValidate.Message does not exist.', 1;
GO
