/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 0d1a1b37-6d06-4326-89ba-ccf7d4c96d36
    Object             : Constraint SFin.TransactionDetailsValidate.DF__Transacti__IsRea__454F1B88
    Difference         : MissingInTarget
    Comparison hash    : 913A4FFEC21A8C990E21FCA37CF72D5DDBA81B2AE629852DC83F441956B45D5A
    Definition SHA-256 : 33ACABD98491DC316BC9F0A7B14B310B3E725C7867DCC6A05C7329AC0ACD0614
    Purpose            : Finalize phase: create the source constraint from the declarative snapshot.
    Generated UTC      : 2026-08-11T08:37:06.8544271Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF NOT EXISTS
(
    SELECT 1
    FROM sys.objects AS constraintObject
    WHERE constraintObject.parent_object_id = OBJECT_ID(N'[SFin].[TransactionDetailsValidate]', N'U')
      AND constraintObject.name = N'DF__Transacti__IsRea__454F1B88'
)
    BEGIN
        ALTER TABLE [SFin].[TransactionDetailsValidate] ADD CONSTRAINT [DF__Transacti__IsRea__454F1B88] DEFAULT ((0)) FOR [IsReadOnly];
    END;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
