/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : abd5ccd9-6a3e-4a9a-b22c-e37a33d9b13f
    Object             : Constraint SFin.TransactionDetailsValidate.DF__Transacti__Targe__445AF74F
    Difference         : MissingInTarget
    Comparison hash    : FCFDE80E381BF5EDA60434BD53700953F254E3C7480743CF0584BFBF0C230524
    Definition SHA-256 : 85820182A65BBAC21CCA35F8163B626EE57B86D1186635DA5769BEFF2F7B9B2A
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:07.0216038Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SFin].[TransactionDetailsValidate]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SFin.TransactionDetailsValidate does not exist.', 1;
IF COL_LENGTH(N'[SFin].[TransactionDetailsValidate]', N'TargetType') IS NULL
    THROW 51404, 'Default-constraint column SFin.TransactionDetailsValidate.TargetType does not exist.', 1;
GO
