/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 02128408-e7d3-4bf4-89a0-72e07eb51124
    Object             : Constraint SFin.tvf_InvoiceScheduleMonthConfigurationValidate.DF__tvf_Invoi__IsInf__04FF8C49
    Difference         : MissingInTarget
    Comparison hash    : 5CDDE45AB400547D17C1F511018C11F189CBCD8DED9C3CA918E4D96BBE1C14C9
    Definition SHA-256 : DF261A1223EF9F09F76C7C41470BC5386F345801379AA9711813A997C7B9935C
    Purpose            : Finalize phase: create the source constraint from the declarative snapshot.
    Generated UTC      : 2026-08-11T08:37:07.1001214Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF NOT EXISTS
(
    SELECT 1
    FROM sys.objects AS constraintObject
    WHERE constraintObject.parent_object_id = OBJECT_ID(N'[SFin].[tvf_InvoiceScheduleMonthConfigurationValidate]', N'U')
      AND constraintObject.name = N'DF__tvf_Invoi__IsInf__04FF8C49'
)
    BEGIN
        ALTER TABLE [SFin].[tvf_InvoiceScheduleMonthConfigurationValidate] ADD CONSTRAINT [DF__tvf_Invoi__IsInf__04FF8C49] DEFAULT ((0)) FOR [IsInformationOnly];
    END;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
