/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 3e401705-7cd5-4a65-ac3a-3a77a9f2d715
    Object             : Constraint SFin.TransactionsValidate.DF__Transacti__IsHid__37F5206A
    Difference         : MissingInTarget
    Comparison hash    : 4C56535AC1DA0D677F77958CF60EA6DCEA4AB40DC473DA768AF95412767B9683
    Definition SHA-256 : A8E3545B05890BC0060027C5A60F46F6EF6CD1AFFC6F6547D6CC7D5AF867B161
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:06.6016168Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SFin].[TransactionsValidate]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SFin.TransactionsValidate does not exist.', 1;
IF COL_LENGTH(N'[SFin].[TransactionsValidate]', N'IsHidden') IS NULL
    THROW 51404, 'Default-constraint column SFin.TransactionsValidate.IsHidden does not exist.', 1;
GO
