/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 4aaf2bde-1e15-416a-b582-46c6bf03fa93
    Object             : Constraint SJob.PurchaseOrders.DF_PurchaseOrders_InvoiceRequestId
    Difference         : MissingInTarget
    Comparison hash    : 546A8AC233CDD5BC604E3E4E4A579DACEF34C4F0F38431603060EDD4B92535F0
    Definition SHA-256 : D2AB172997691EB06684B2811C1FDA476AAE981035F6D15B84625C8481EF4275
    Purpose            : Finalize phase: create the source constraint from the declarative snapshot.
    Generated UTC      : 2026-08-11T08:37:07.6899117Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF NOT EXISTS
(
    SELECT 1
    FROM sys.objects AS constraintObject
    WHERE constraintObject.parent_object_id = OBJECT_ID(N'[SJob].[PurchaseOrders]', N'U')
      AND constraintObject.name = N'DF_PurchaseOrders_InvoiceRequestId'
)
    BEGIN
        ALTER TABLE [SJob].[PurchaseOrders] ADD CONSTRAINT [DF_PurchaseOrders_InvoiceRequestId] DEFAULT ((-1)) FOR [InvoiceRequestId];
    END;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
