/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 4e6d429d-02c3-4706-bba1-71d2762a2616
    Object             : Constraint SJob.SubContractorInvoices.DF_SubContractorInvoices_SubContractorId
    Difference         : MissingInTarget
    Comparison hash    : 8C358209B69CE22C7C0A6742A388A68ED49C1B344ECDE2FD5DFBE8EC29BB0910
    Definition SHA-256 : 8439B86679C732E49566BB7D3FFE712E1C8108C10971125B75913411C396BD89
    Purpose            : Finalize phase: create the source constraint from the declarative snapshot.
    Generated UTC      : 2026-08-11T08:37:07.7099115Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF NOT EXISTS
(
    SELECT 1
    FROM sys.objects AS constraintObject
    WHERE constraintObject.parent_object_id = OBJECT_ID(N'[SJob].[SubContractorInvoices]', N'U')
      AND constraintObject.name = N'DF_SubContractorInvoices_SubContractorId'
)
    BEGIN
        ALTER TABLE [SJob].[SubContractorInvoices] ADD CONSTRAINT [DF_SubContractorInvoices_SubContractorId] DEFAULT ((-1)) FOR [SubContractorId];
    END;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
