/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 2e3aabf4-0c2c-48b3-9ac4-c5d6cb96f223
    Object             : Constraint SJob.tvf_JobsValidate.DF__tvf_JobsV__Targe__01D83B84
    Difference         : MissingInTarget
    Comparison hash    : DC8397CCE23522BDB38F8F2530FEE78870948E5374A9E2E496E8E953666845DC
    Definition SHA-256 : 8178317E84A8D7833A1E9851EE9DECA4177C96D4CA65C043F0D6421DB41DEEEA
    Purpose            : Finalize phase: create the source constraint from the declarative snapshot.
    Generated UTC      : 2026-08-11T08:37:07.6423822Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF NOT EXISTS
(
    SELECT 1
    FROM sys.objects AS constraintObject
    WHERE constraintObject.parent_object_id = OBJECT_ID(N'[SJob].[tvf_JobsValidate]', N'U')
      AND constraintObject.name = N'DF__tvf_JobsV__Targe__01D83B84'
)
    BEGIN
        ALTER TABLE [SJob].[tvf_JobsValidate] ADD CONSTRAINT [DF__tvf_JobsV__Targe__01D83B84] DEFAULT ('00000000-0000-0000-0000-000000000000') FOR [TargetGuid];
    END;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
