/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 048b7537-a4d4-4472-adf4-ccefe8f96444
    Object             : Constraint SJob.tvf_JobsValidate.DF__tvf_JobsV__IsInv__05A8CC68
    Difference         : MissingInTarget
    Comparison hash    : 47FFCB032EC9ABF53490116879B46A434AAB37E57A8BF0C7DDB54C1C9DD0DBC2
    Definition SHA-256 : 7EA15F0FB6F5909E0B1626355BABCEC26C1A846CB48AC9D086463E0FD3AEA5A4
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:07.5574661Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SJob].[tvf_JobsValidate]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SJob.tvf_JobsValidate does not exist.', 1;
IF COL_LENGTH(N'[SJob].[tvf_JobsValidate]', N'IsInvalid') IS NULL
    THROW 51404, 'Default-constraint column SJob.tvf_JobsValidate.IsInvalid does not exist.', 1;
GO
