/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 28edf018-87e8-40a7-bfdc-e524fdbc0c27
    Object             : Constraint SJob.tvf_JobsValidate.DF__tvf_JobsV__Targe__02CC5FBD
    Difference         : MissingInTarget
    Comparison hash    : FCFDE80E381BF5EDA60434BD53700953F254E3C7480743CF0584BFBF0C230524
    Definition SHA-256 : 85820182A65BBAC21CCA35F8163B626EE57B86D1186635DA5769BEFF2F7B9B2A
    Purpose            : Finalize phase: create the source constraint from the declarative snapshot.
    Generated UTC      : 2026-08-11T08:37:07.6653904Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF NOT EXISTS
(
    SELECT 1
    FROM sys.objects AS constraintObject
    WHERE constraintObject.parent_object_id = OBJECT_ID(N'[SJob].[tvf_JobsValidate]', N'U')
      AND constraintObject.name = N'DF__tvf_JobsV__Targe__02CC5FBD'
)
    BEGIN
        ALTER TABLE [SJob].[tvf_JobsValidate] ADD CONSTRAINT [DF__tvf_JobsV__Targe__02CC5FBD] DEFAULT ('') FOR [TargetType];
    END;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
