/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : cbea6663-d3b3-42a4-b7e1-b5481ebd44e9
    Object             : Constraint SJob.RibaStagesValidate.DF__RibaStage__IsRea__0A8D7D16
    Difference         : MissingInTarget
    Comparison hash    : 913A4FFEC21A8C990E21FCA37CF72D5DDBA81B2AE629852DC83F441956B45D5A
    Definition SHA-256 : 33ACABD98491DC316BC9F0A7B14B310B3E725C7867DCC6A05C7329AC0ACD0614
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:07.3737425Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SJob].[RibaStagesValidate]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SJob.RibaStagesValidate does not exist.', 1;
IF COL_LENGTH(N'[SJob].[RibaStagesValidate]', N'IsReadOnly') IS NULL
    THROW 51404, 'Default-constraint column SJob.RibaStagesValidate.IsReadOnly does not exist.', 1;
GO
