/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 46c7b62d-9631-4dc1-ab4a-b9afbd6ab00b
    Object             : Constraint SMigration.Onboarding_EntityScope.DF_Onboarding_EntityScope_Category
    Difference         : MissingInTarget
    Comparison hash    : E16EB0077AACCA223A6F244F6EBE9913780406D66DD46D3A2FB44F9870B1C5A9
    Definition SHA-256 : D087160F3FEE5E93955407C6793AD9B5B382A00D68A64FE508ADA9C37AC4DB55
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:07.7629200Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SMigration].[Onboarding_EntityScope]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SMigration.Onboarding_EntityScope does not exist.', 1;
IF COL_LENGTH(N'[SMigration].[Onboarding_EntityScope]', N'Category') IS NULL
    THROW 51404, 'Default-constraint column SMigration.Onboarding_EntityScope.Category does not exist.', 1;
GO
