/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 66cabdb9-a5a0-43cf-ba14-fb61dde73bc1
    Object             : Constraint SMigration.Onboarding_EntityScope.DF_Onboarding_EntityScope_IsImplemented
    Difference         : MissingInTarget
    Comparison hash    : 994E694FC2427D82D154542E7113F7D9AE88735D7DD275ECC25F7D46410C31CE
    Definition SHA-256 : 36042D1B52796A641CE64FEBCF545FEE151630E08B6D8FE16FCD5A41CD1450B0
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:07.8574669Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SMigration].[Onboarding_EntityScope]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SMigration.Onboarding_EntityScope does not exist.', 1;
IF COL_LENGTH(N'[SMigration].[Onboarding_EntityScope]', N'IsImplemented') IS NULL
    THROW 51404, 'Default-constraint column SMigration.Onboarding_EntityScope.IsImplemented does not exist.', 1;
GO
