/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 11a53c02-5cb7-4358-959e-588337676e39
    Object             : Constraint SMigration.Onboarding_RunEntitySelections.UQ_Onboarding_RunEntitySelections_Run_Entity
    Difference         : MissingInTarget
    Comparison hash    : 6200913A4B5F82A2D6C8CEAC7A8ED1094C0B712C3BD5545094FD3FE2AE773373
    Definition SHA-256 : C9376316F7D26EC3DC60724883CBC0D87743E6FAEC9ED861A3E948B544D44419
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:08.3260892Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SMigration].[Onboarding_RunEntitySelections]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SMigration.Onboarding_RunEntitySelections does not exist.', 1;
IF COL_LENGTH(N'[SMigration].[Onboarding_RunEntitySelections]', N'RunGuid') IS NULL
    THROW 51405, 'Key-constraint column SMigration.Onboarding_RunEntitySelections.RunGuid does not exist.', 1;
IF COL_LENGTH(N'[SMigration].[Onboarding_RunEntitySelections]', N'EntityCode') IS NULL
    THROW 51405, 'Key-constraint column SMigration.Onboarding_RunEntitySelections.EntityCode does not exist.', 1;
IF EXISTS (SELECT [RunGuid], [EntityCode] FROM [SMigration].[Onboarding_RunEntitySelections] GROUP BY [RunGuid], [EntityCode] HAVING COUNT_BIG(1) > 1)
    THROW 51407, 'Key constraint UQ_Onboarding_RunEntitySelections_Run_Entity cannot be created because duplicate key values exist.', 1;
GO
