/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : e7ed421c-fe84-4af7-b42c-695cb3d8fc33
    Object             : Constraint SMigration.Onboarding_EntityScope.DF_Onboarding_EntityScope_SourceSchemaName
    Difference         : MissingInTarget
    Comparison hash    : D87E4321CEBB9412952C26BCD7929E90DBB5EED08D5862BDE19B6EADCACDCADD
    Definition SHA-256 : 16B028B0272B51B95FFE7B0ABFD19AB2C7F3E7ED19BEBB5708D0F7D5CE886B22
    Purpose            : Finalize phase: create the source constraint from the declarative snapshot.
    Generated UTC      : 2026-08-11T08:37:07.9854343Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF NOT EXISTS
(
    SELECT 1
    FROM sys.objects AS constraintObject
    WHERE constraintObject.parent_object_id = OBJECT_ID(N'[SMigration].[Onboarding_EntityScope]', N'U')
      AND constraintObject.name = N'DF_Onboarding_EntityScope_SourceSchemaName'
)
    BEGIN
        ALTER TABLE [SMigration].[Onboarding_EntityScope] ADD CONSTRAINT [DF_Onboarding_EntityScope_SourceSchemaName] DEFAULT (N'') FOR [SourceSchemaName];
    END;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
