/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : ae616686-3fb0-454f-ad01-db3241e1248f
    Object             : Constraint SMigration.Onboarding_EntityScope.DF_Onboarding_EntityScope_IsRequired
    Difference         : MissingInTarget
    Comparison hash    : DE3184820FD96731A29E6A0080FB416D89C2028A3B3953384C0D4945BE4EC67C
    Definition SHA-256 : C03BE09E74EA5CB48DA1CCE7DDEEF59C13FA4F9AEBC26DC18DA15878AF6F27D8
    Purpose            : Finalize phase: create the source constraint from the declarative snapshot.
    Generated UTC      : 2026-08-11T08:37:07.8869617Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF NOT EXISTS
(
    SELECT 1
    FROM sys.objects AS constraintObject
    WHERE constraintObject.parent_object_id = OBJECT_ID(N'[SMigration].[Onboarding_EntityScope]', N'U')
      AND constraintObject.name = N'DF_Onboarding_EntityScope_IsRequired'
)
    BEGIN
        ALTER TABLE [SMigration].[Onboarding_EntityScope] ADD CONSTRAINT [DF_Onboarding_EntityScope_IsRequired] DEFAULT ((0)) FOR [IsRequired];
    END;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
