/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 3b307a09-6b13-4a13-bc13-91ee9ab816f1
    Object             : Constraint SMigration.Onboarding_EntityScope.DF_Onboarding_EntityScope_ScopeType
    Difference         : MissingInTarget
    Comparison hash    : 3137D35387CB6DF64E5FBD9E781EED171B19DAAEA2DD34E12A5379F9679B6236
    Definition SHA-256 : C300D75A17C7F229290C989A4BF176C12001D64E6668FED2770DC06789C998E7
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:07.9569811Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SMigration].[Onboarding_EntityScope]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SMigration.Onboarding_EntityScope does not exist.', 1;
IF COL_LENGTH(N'[SMigration].[Onboarding_EntityScope]', N'ScopeType') IS NULL
    THROW 51404, 'Default-constraint column SMigration.Onboarding_EntityScope.ScopeType does not exist.', 1;
GO
