/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 5403c3cd-1c9c-4219-84b0-fc9e30f466b3
    Object             : Constraint SMigration.Onboarding_RunEntitySelections.DF_Onboarding_RunEntitySelections_SelectionSource
    Difference         : MissingInTarget
    Comparison hash    : 4E29BE0C37C65FC9C92D805262351682D9AE0A61A6B6F7183E9E713864E4CD89
    Definition SHA-256 : 4E288F87A052835FFAC9258220F581F2AA55822B937E55A894BECD77BEAB06FF
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:08.1399822Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SMigration].[Onboarding_RunEntitySelections]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SMigration.Onboarding_RunEntitySelections does not exist.', 1;
IF COL_LENGTH(N'[SMigration].[Onboarding_RunEntitySelections]', N'SelectionSource') IS NULL
    THROW 51404, 'Default-constraint column SMigration.Onboarding_RunEntitySelections.SelectionSource does not exist.', 1;
GO
