/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 7d8718d3-2030-47b1-9104-1fa5fbee3ece
    Object             : Constraint SMigration.Onboarding_EntityScope.DF_Onboarding_EntityScope_SourceTableName
    Difference         : MissingInTarget
    Comparison hash    : 23E8566587F7845F5C1CB930DA8047C152C4577F67DE00BDCECD8DEBF86E680A
    Definition SHA-256 : 3E74058DA34823F162FF87448BC2DDFC65A0511F14F82589B81093F973FA61A3
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:08.0014314Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SMigration].[Onboarding_EntityScope]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SMigration.Onboarding_EntityScope does not exist.', 1;
IF COL_LENGTH(N'[SMigration].[Onboarding_EntityScope]', N'SourceTableName') IS NULL
    THROW 51404, 'Default-constraint column SMigration.Onboarding_EntityScope.SourceTableName does not exist.', 1;
GO
