/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 3060c86d-e703-487f-b5c3-50d8122fed32
    Object             : Constraint SMigration.Onboarding_RunEntitySelections.DF_Onboarding_RunEntitySelections_SelectedByUserId
    Difference         : MissingInTarget
    Comparison hash    : BFF6782EADD071D16642556B69A1068378F52BB0319F42F2C5ABAB468B17240C
    Definition SHA-256 : B30D31365ABA6482E567E657D89FBEB48EA30CFEE3CC0076799627CA4FB6A778
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:08.0929921Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SMigration].[Onboarding_RunEntitySelections]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SMigration.Onboarding_RunEntitySelections does not exist.', 1;
IF COL_LENGTH(N'[SMigration].[Onboarding_RunEntitySelections]', N'SelectedByUserId') IS NULL
    THROW 51404, 'Default-constraint column SMigration.Onboarding_RunEntitySelections.SelectedByUserId does not exist.', 1;
GO
