/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 6785d86e-a6ec-4821-902a-9f0d4ea27e34
    Object             : Constraint SMigration.Onboarding_Run.DF_SMigration_Onboarding_Run_SourceServerName
    Difference         : MissingInTarget
    Comparison hash    : 4DF550A341178C0215DD4A993D315B41D96254A26CF5FA575A37CC8EA1A4B5F5
    Definition SHA-256 : 3E6DC16407D6B7B8080D86131D88284D9ED6898D395DF415B05FA256BDD43A8B
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:08.1812249Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SMigration].[Onboarding_Run]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SMigration.Onboarding_Run does not exist.', 1;
IF COL_LENGTH(N'[SMigration].[Onboarding_Run]', N'SourceServerName') IS NULL
    THROW 51404, 'Default-constraint column SMigration.Onboarding_Run.SourceServerName does not exist.', 1;
GO
