/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 9ad88109-c40c-4687-a4f8-6d0ba108e5fa
    Object             : Constraint SSop.tvf_QuotesValidate.DF__tvf_Quote__IsInv__1FBDA426
    Difference         : MissingInTarget
    Comparison hash    : 47FFCB032EC9ABF53490116879B46A434AAB37E57A8BF0C7DDB54C1C9DD0DBC2
    Definition SHA-256 : 7EA15F0FB6F5909E0B1626355BABCEC26C1A846CB48AC9D086463E0FD3AEA5A4
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:08.5421727Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SSop].[tvf_QuotesValidate]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SSop.tvf_QuotesValidate does not exist.', 1;
IF COL_LENGTH(N'[SSop].[tvf_QuotesValidate]', N'IsInvalid') IS NULL
    THROW 51404, 'Default-constraint column SSop.tvf_QuotesValidate.IsInvalid does not exist.', 1;
GO
