/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : d1b6197a-5496-47b5-95ea-29c5eb63a827
    Object             : Constraint SSop.tvf_EnquiriesValidate.DF__tvf_Enqui__Targe__5B09527D
    Difference         : MissingInTarget
    Comparison hash    : FCFDE80E381BF5EDA60434BD53700953F254E3C7480743CF0584BFBF0C230524
    Definition SHA-256 : 85820182A65BBAC21CCA35F8163B626EE57B86D1186635DA5769BEFF2F7B9B2A
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:08.4506177Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SSop].[tvf_EnquiriesValidate]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SSop.tvf_EnquiriesValidate does not exist.', 1;
IF COL_LENGTH(N'[SSop].[tvf_EnquiriesValidate]', N'TargetType') IS NULL
    THROW 51404, 'Default-constraint column SSop.tvf_EnquiriesValidate.TargetType does not exist.', 1;
GO
