/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : a04069ce-c8e3-44bd-af68-80e0c317e2e0
    Object             : Constraint SSop.tvf_QuotesValidate.DF__tvf_Quote__IsInf__20B1C85F
    Difference         : MissingInTarget
    Comparison hash    : 5CDDE45AB400547D17C1F511018C11F189CBCD8DED9C3CA918E4D96BBE1C14C9
    Definition SHA-256 : DF261A1223EF9F09F76C7C41470BC5386F345801379AA9711813A997C7B9935C
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:08.5061668Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SSop].[tvf_QuotesValidate]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SSop.tvf_QuotesValidate does not exist.', 1;
IF COL_LENGTH(N'[SSop].[tvf_QuotesValidate]', N'IsInformationOnly') IS NULL
    THROW 51404, 'Default-constraint column SSop.tvf_QuotesValidate.IsInformationOnly does not exist.', 1;
GO
