/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : c044255b-b9c3-4f52-a68e-06739377e0a2
    Object             : Constraint SSop.tvf_QuotesValidate.DF__tvf_Quote__IsRea__1DD55BB4
    Difference         : MissingInTarget
    Comparison hash    : 913A4FFEC21A8C990E21FCA37CF72D5DDBA81B2AE629852DC83F441956B45D5A
    Definition SHA-256 : 33ACABD98491DC316BC9F0A7B14B310B3E725C7867DCC6A05C7329AC0ACD0614
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:08.5835495Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SSop].[tvf_QuotesValidate]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SSop.tvf_QuotesValidate does not exist.', 1;
IF COL_LENGTH(N'[SSop].[tvf_QuotesValidate]', N'IsReadOnly') IS NULL
    THROW 51404, 'Default-constraint column SSop.tvf_QuotesValidate.IsReadOnly does not exist.', 1;
GO
