/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : e16409f9-5a7e-4f0a-a2b1-f53642815324
    Object             : Constraint SSop.tvf_QuotesValidate.DF__tvf_Quote__IsHid__1EC97FED
    Difference         : MissingInTarget
    Comparison hash    : 4C56535AC1DA0D677F77958CF60EA6DCEA4AB40DC473DA768AF95412767B9683
    Definition SHA-256 : A8E3545B05890BC0060027C5A60F46F6EF6CD1AFFC6F6547D6CC7D5AF867B161
    Purpose            : Finalize phase: create the source constraint from the declarative snapshot.
    Generated UTC      : 2026-08-11T08:37:08.4711702Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF NOT EXISTS
(
    SELECT 1
    FROM sys.objects AS constraintObject
    WHERE constraintObject.parent_object_id = OBJECT_ID(N'[SSop].[tvf_QuotesValidate]', N'U')
      AND constraintObject.name = N'DF__tvf_Quote__IsHid__1EC97FED'
)
    BEGIN
        ALTER TABLE [SSop].[tvf_QuotesValidate] ADD CONSTRAINT [DF__tvf_Quote__IsHid__1EC97FED] DEFAULT ((0)) FOR [IsHidden];
    END;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
