/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 144b4614-c553-4169-8384-6a400a5d5bb1
    Object             : Constraint SSop.CriticalProjectNotes.DF_CriticalProjectNotes_ProjectId
    Difference         : MissingInTarget
    Comparison hash    : D9BA72BAED0404E34000459B798F1CE5903033731B04C747091CEBB0EF7E2DAC
    Definition SHA-256 : 4620C19B13C3ECE49C70D9A9E1A0A6FFD3C571A1A72D66434AE1FB0E9D597392
    Purpose            : Finalize phase: create the source constraint from the declarative snapshot.
    Generated UTC      : 2026-08-11T08:37:08.8126208Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;

BEGIN TRY
    BEGIN TRANSACTION;

    IF NOT EXISTS
(
    SELECT 1
    FROM sys.objects AS constraintObject
    WHERE constraintObject.parent_object_id = OBJECT_ID(N'[SSop].[CriticalProjectNotes]', N'U')
      AND constraintObject.name = N'DF_CriticalProjectNotes_ProjectId'
)
    BEGIN
        ALTER TABLE [SSop].[CriticalProjectNotes] ADD CONSTRAINT [DF_CriticalProjectNotes_ProjectId] DEFAULT ((-1)) FOR [ProjectId];
    END;

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0
        ROLLBACK TRANSACTION;
    THROW;
END CATCH;
GO
