/*
    CymBuild generated canonical schema source.
    Generated by       : CYB-361 R41 schema deployment runner
    Run Guid           : 80b8be8d-b318-4939-a528-bd2ae679d6b9
    Comparison Guid    : 9320e0ea-cec5-4195-b839-0f0dc3c6c3ac
    Object             : Constraint SSop.CriticalProjectNotes.DF_CriticalProjectNotes_ParentGuid
    Difference         : MissingInTarget
    Comparison hash    : B4160BDDA5F0D722C4B4934E6221B17F45462AF24D53653B8CCD22264B9369F5
    Definition SHA-256 : D273F088858285F6071F1D020D20C1C62886504A98EEF68E5C876FB4F0945194
    Purpose            : Read-only preflight for the selected constraint operation.
    Generated UTC      : 2026-08-11T08:37:08.7876157Z

    This file was generated from the accepted declarative schema snapshot. Review and commit it
    through the normal source-control process before promoting the release. It is never executed
    directly from captured database DDL.
*/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET NOCOUNT ON;

IF OBJECT_ID(N'[SSop].[CriticalProjectNotes]', N'U') IS NULL
    THROW 51400, 'Constraint parent table SSop.CriticalProjectNotes does not exist.', 1;
IF COL_LENGTH(N'[SSop].[CriticalProjectNotes]', N'ParentGuid') IS NULL
    THROW 51404, 'Default-constraint column SSop.CriticalProjectNotes.ParentGuid does not exist.', 1;
GO
