--
-- Script was generated by Devart dbForge Data Compare for SQL Server, Version 7.0.249.0
-- Product Home Page: https://www.devart.com/dbforge/sql/datacompare
-- Script date 07/03/2025 11:41:39
-- Source server version: 16.00.1000
-- Source connection string: Data Source=soc-sqldevbre01.esgl.co.uk\General;Integrated Security=True;User ID=ESGL\Richard.Brindley
-- Target server version: 16.00.1000
-- Target connection string: Data Source=soc-sqldevbre01.esgl.co.uk\General;Integrated Security=True;User ID=ESGL\Richard.Brindley
-- Run this script against Concursus_Test to synchronize it with Concursus_Dev
-- Please backup your target database before running this script
--

SET LANGUAGE 'British English'
SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT, XACT_ABORT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS OFF
GO



--
-- Start Transaction
--
BEGIN TRANSACTION

--
-- Disabling DML triggers for [SCore].[EntityProperties]
--
GO
DISABLE TRIGGER ALL ON SCore.EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityProperties]
--
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_DropDownListDefinitions
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_EntityDataTypes
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_EntityHoBTs
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_EntityPropertyGroupID
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_LanguageLabels
ALTER TABLE SCore.EntityProperties
  DROP CONSTRAINT IF EXISTS FK_EntityProperties_RowStatus
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityPropertyActions]
--
ALTER TABLE SCore.EntityPropertyActions
  DROP CONSTRAINT IF EXISTS FK_EntityPropertyActions_EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityPropertyDependants]
--
ALTER TABLE SCore.EntityPropertyDependants
  DROP CONSTRAINT IF EXISTS FK_EntityPropertyDependants_EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[EntityQueryParameters]
--
ALTER TABLE SCore.EntityQueryParameters
  DROP CONSTRAINT IF EXISTS FK_EntityQueryParameters_EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[MergeDocumentItemIncludes]
--
ALTER TABLE SCore.MergeDocumentItemIncludes
  DROP CONSTRAINT IF EXISTS FK_MergeDocumentItemIncludes_EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[RecordHistory]
--
ALTER TABLE SCore.RecordHistory
  DROP CONSTRAINT IF EXISTS FK_RecordHistory_EntityPropertyID
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Dropping constraints from [SCore].[SynchronisationErrors]
--
ALTER TABLE SCore.SynchronisationErrors
  DROP CONSTRAINT IF EXISTS FK_SychronisationErrors_EntityPropertyID
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Updating data of table [SCore].[EntityProperties]
--
UPDATE SCore.EntityProperties SET DoNotTrackChanges = 1 WHERE ID = 1788
UPDATE SCore.EntityProperties SET DoNotTrackChanges = 1 WHERE ID = 2030
UPDATE SCore.EntityProperties SET DoNotTrackChanges = 1 WHERE ID = 2031
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityProperties]
--
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_DropDownListDefinitions FOREIGN KEY (DropDownListDefinitionID) REFERENCES SUserInterface.DropDownListDefinitions(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_EntityDataTypes FOREIGN KEY (EntityDataTypeID) REFERENCES SCore.EntityDataTypes(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_EntityHoBTs FOREIGN KEY (EntityHoBTID) REFERENCES SCore.EntityHobts(ID) ON DELETE CASCADE ON UPDATE NO ACTION
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_EntityPropertyGroupID FOREIGN KEY (EntityPropertyGroupID) REFERENCES SCore.EntityPropertyGroups(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_LanguageLabels FOREIGN KEY (LanguageLabelID) REFERENCES SCore.LanguageLabels(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
ALTER TABLE SCore.EntityProperties WITH NOCHECK
  ADD CONSTRAINT FK_EntityProperties_RowStatus FOREIGN KEY (RowStatus) REFERENCES SCore.RowStatus(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityPropertyActions]
--
ALTER TABLE SCore.EntityPropertyActions WITH NOCHECK
  ADD CONSTRAINT FK_EntityPropertyActions_EntityProperties FOREIGN KEY (EntityPropertyID) REFERENCES SCore.EntityProperties(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityPropertyDependants]
--
ALTER TABLE SCore.EntityPropertyDependants WITH NOCHECK
  ADD CONSTRAINT FK_EntityPropertyDependants_EntityProperties FOREIGN KEY (ParentEntityPropertyID) REFERENCES SCore.EntityProperties(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[EntityQueryParameters]
--
ALTER TABLE SCore.EntityQueryParameters WITH NOCHECK
  ADD CONSTRAINT FK_EntityQueryParameters_EntityProperties FOREIGN KEY (MappedEntityPropertyID) REFERENCES SCore.EntityProperties(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[MergeDocumentItemIncludes]
--
ALTER TABLE SCore.MergeDocumentItemIncludes WITH NOCHECK
  ADD CONSTRAINT FK_MergeDocumentItemIncludes_EntityProperties FOREIGN KEY (SourceDocumentEntityPropertyId) REFERENCES SCore.EntityProperties(ID) ON DELETE NO ACTION ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[RecordHistory]
--
ALTER TABLE SCore.RecordHistory WITH NOCHECK
  ADD CONSTRAINT FK_RecordHistory_EntityPropertyID FOREIGN KEY (EntityPropertyID) REFERENCES SCore.EntityProperties(ID) ON DELETE CASCADE ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Creating constraints for [SCore].[SynchronisationErrors]
--
ALTER TABLE SCore.SynchronisationErrors WITH NOCHECK
  ADD CONSTRAINT FK_SychronisationErrors_EntityPropertyID FOREIGN KEY (EntityPropertyID) REFERENCES SCore.EntityProperties(ID) ON DELETE CASCADE ON UPDATE NO ACTION
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Enabling DML triggers for [SCore].[EntityProperties]
--
GO
ENABLE TRIGGER ALL ON SCore.EntityProperties
GO

IF @@ERROR<>0 OR @@TRANCOUNT=0 BEGIN IF @@TRANCOUNT>0 ROLLBACK SET NOEXEC ON END

--
-- Commit Transaction
--
IF @@TRANCOUNT>0 COMMIT TRANSACTION
SET NOEXEC OFF
GO